/****************************************************************************
 * arch/arm/src/da1470x/hardware/da1470x_memctrl.h
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.  The
 * ASF licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 ****************************************************************************/

/* Generated from the Renesas CMSIS device header DA1470x-00.h (SDK
 * 10.2.6.49).  Do not edit by hand; regenerate with tools/genhdr.py.
 */

#ifndef __ARCH_ARM_SRC_DA1470X_HARDWARE_DA1470X_MEMCTRL_H
#define __ARCH_ARM_SRC_DA1470X_HARDWARE_DA1470X_MEMCTRL_H

/****************************************************************************
 * Included Files
 ****************************************************************************/

#include <nuttx/config.h>
#include "da1470x_memorymap.h"

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

/* Register Offsets *********************************************************/

#define DA1470X_MEMCTRL_MEM_PRIO_ARB1_4_OFFSET 0x0004 /* Priority Control Register for arbiter 1, */
#define DA1470X_MEMCTRL_MEM_PRIO_ARB5_8_OFFSET 0x0008 /* Priority Control Register for arbiter 5, */
#define DA1470X_MEMCTRL_MEM_STALL_OFFSET 0x0010       /* Maximum Stall cycles Control Register */
#define DA1470X_MEMCTRL_MEM_STATUS_OFFSET 0x0014      /* Memory Arbiter Status Register */
#define DA1470X_MEMCTRL_MEM_STATUS2_OFFSET 0x0018     /* RAM cells Status Register */
#define DA1470X_MEMCTRL_CMI_CODE_BASE_OFFSET 0x0020   /* CMAC code Base Address Register */
#define DA1470X_MEMCTRL_CMI_DATA_BASE_OFFSET 0x0024   /* CMAC data Base Address Register */
#define DA1470X_MEMCTRL_CMI_SHARED_BASE_OFFSET 0x0028 /* CMAC shared data Base Address Register */
#define DA1470X_MEMCTRL_CMI_END_OFFSET 0x002c         /* CMAC end Address Register */
#define DA1470X_MEMCTRL_CMAC_STATUS_OFFSET 0x0030     /* Memory Arbiter Status Register */
#define DA1470X_MEMCTRL_BUSY_SET_OFFSET 0x0070        /* BSR Set Register */
#define DA1470X_MEMCTRL_BUSY_SET_REG2_OFFSET 0x0074   /* BSR2 Set Register */
#define DA1470X_MEMCTRL_BUSY_RESET_OFFSET 0x0078      /* BSR Reset Register */
#define DA1470X_MEMCTRL_BUSY_RESET_REG2_OFFSET 0x007c /* BSR2 Reset Register */
#define DA1470X_MEMCTRL_BUSY_STAT_OFFSET 0x0080       /* BSR Status Register */
#define DA1470X_MEMCTRL_BUSY_STAT_REG2_OFFSET 0x0084  /* BSR2 Status Register */

/* Register Addresses *******************************************************/

#define DA1470X_MEMCTRL_MEM_PRIO_ARB1_4 (DA1470X_MEMCTRL_BASE + DA1470X_MEMCTRL_MEM_PRIO_ARB1_4_OFFSET)
#define DA1470X_MEMCTRL_MEM_PRIO_ARB5_8 (DA1470X_MEMCTRL_BASE + DA1470X_MEMCTRL_MEM_PRIO_ARB5_8_OFFSET)
#define DA1470X_MEMCTRL_MEM_STALL (DA1470X_MEMCTRL_BASE + DA1470X_MEMCTRL_MEM_STALL_OFFSET)
#define DA1470X_MEMCTRL_MEM_STATUS (DA1470X_MEMCTRL_BASE + DA1470X_MEMCTRL_MEM_STATUS_OFFSET)
#define DA1470X_MEMCTRL_MEM_STATUS2 (DA1470X_MEMCTRL_BASE + DA1470X_MEMCTRL_MEM_STATUS2_OFFSET)
#define DA1470X_MEMCTRL_CMI_CODE_BASE (DA1470X_MEMCTRL_BASE + DA1470X_MEMCTRL_CMI_CODE_BASE_OFFSET)
#define DA1470X_MEMCTRL_CMI_DATA_BASE (DA1470X_MEMCTRL_BASE + DA1470X_MEMCTRL_CMI_DATA_BASE_OFFSET)
#define DA1470X_MEMCTRL_CMI_SHARED_BASE (DA1470X_MEMCTRL_BASE + DA1470X_MEMCTRL_CMI_SHARED_BASE_OFFSET)
#define DA1470X_MEMCTRL_CMI_END (DA1470X_MEMCTRL_BASE + DA1470X_MEMCTRL_CMI_END_OFFSET)
#define DA1470X_MEMCTRL_CMAC_STATUS (DA1470X_MEMCTRL_BASE + DA1470X_MEMCTRL_CMAC_STATUS_OFFSET)
#define DA1470X_MEMCTRL_BUSY_SET (DA1470X_MEMCTRL_BASE + DA1470X_MEMCTRL_BUSY_SET_OFFSET)
#define DA1470X_MEMCTRL_BUSY_SET_REG2 (DA1470X_MEMCTRL_BASE + DA1470X_MEMCTRL_BUSY_SET_REG2_OFFSET)
#define DA1470X_MEMCTRL_BUSY_RESET (DA1470X_MEMCTRL_BASE + DA1470X_MEMCTRL_BUSY_RESET_OFFSET)
#define DA1470X_MEMCTRL_BUSY_RESET_REG2 (DA1470X_MEMCTRL_BASE + DA1470X_MEMCTRL_BUSY_RESET_REG2_OFFSET)
#define DA1470X_MEMCTRL_BUSY_STAT (DA1470X_MEMCTRL_BASE + DA1470X_MEMCTRL_BUSY_STAT_OFFSET)
#define DA1470X_MEMCTRL_BUSY_STAT_REG2 (DA1470X_MEMCTRL_BASE + DA1470X_MEMCTRL_BUSY_STAT_REG2_OFFSET)

/* Register Bit-field Definitions *******************************************/

/* MEM_PRIO_ARB1_4 register */

#define MEMCTRL_MEM_PRIO_ARB1_4_ARB1_AHB_CPUC_PRIO_SHIFT (0)  /* Bits 0-1 */
#define MEMCTRL_MEM_PRIO_ARB1_4_ARB1_AHB_CPUC_PRIO_MASK (0x3 << MEMCTRL_MEM_PRIO_ARB1_4_ARB1_AHB_CPUC_PRIO_SHIFT)
#  define MEMCTRL_MEM_PRIO_ARB1_4_ARB1_AHB_CPUC_PRIO(n) ((uint32_t)(n) << MEMCTRL_MEM_PRIO_ARB1_4_ARB1_AHB_CPUC_PRIO_SHIFT)
#define MEMCTRL_MEM_PRIO_ARB1_4_ARB1_AHB_CPUS_PRIO_SHIFT (2)  /* Bits 2-3 */
#define MEMCTRL_MEM_PRIO_ARB1_4_ARB1_AHB_CPUS_PRIO_MASK (0x3 << MEMCTRL_MEM_PRIO_ARB1_4_ARB1_AHB_CPUS_PRIO_SHIFT)
#  define MEMCTRL_MEM_PRIO_ARB1_4_ARB1_AHB_CPUS_PRIO(n) ((uint32_t)(n) << MEMCTRL_MEM_PRIO_ARB1_4_ARB1_AHB_CPUS_PRIO_SHIFT)
#define MEMCTRL_MEM_PRIO_ARB1_4_ARB1_AHB_DMA_PRIO_SHIFT (4)   /* Bits 4-5 */
#define MEMCTRL_MEM_PRIO_ARB1_4_ARB1_AHB_DMA_PRIO_MASK (0x3 << MEMCTRL_MEM_PRIO_ARB1_4_ARB1_AHB_DMA_PRIO_SHIFT)
#  define MEMCTRL_MEM_PRIO_ARB1_4_ARB1_AHB_DMA_PRIO(n) ((uint32_t)(n) << MEMCTRL_MEM_PRIO_ARB1_4_ARB1_AHB_DMA_PRIO_SHIFT)
#define MEMCTRL_MEM_PRIO_ARB1_4_ARB1_SNC_PRIO_SHIFT (6)       /* Bits 6-7 */
#define MEMCTRL_MEM_PRIO_ARB1_4_ARB1_SNC_PRIO_MASK (0x3 << MEMCTRL_MEM_PRIO_ARB1_4_ARB1_SNC_PRIO_SHIFT)
#  define MEMCTRL_MEM_PRIO_ARB1_4_ARB1_SNC_PRIO(n) ((uint32_t)(n) << MEMCTRL_MEM_PRIO_ARB1_4_ARB1_SNC_PRIO_SHIFT)
#define MEMCTRL_MEM_PRIO_ARB1_4_ARB2_AHB_CPUC_PRIO_SHIFT (8)  /* Bits 8-9 */
#define MEMCTRL_MEM_PRIO_ARB1_4_ARB2_AHB_CPUC_PRIO_MASK (0x3 << MEMCTRL_MEM_PRIO_ARB1_4_ARB2_AHB_CPUC_PRIO_SHIFT)
#  define MEMCTRL_MEM_PRIO_ARB1_4_ARB2_AHB_CPUC_PRIO(n) ((uint32_t)(n) << MEMCTRL_MEM_PRIO_ARB1_4_ARB2_AHB_CPUC_PRIO_SHIFT)
#define MEMCTRL_MEM_PRIO_ARB1_4_ARB2_AHB_CPUS_PRIO_SHIFT (10) /* Bits 10-11 */
#define MEMCTRL_MEM_PRIO_ARB1_4_ARB2_AHB_CPUS_PRIO_MASK (0x3 << MEMCTRL_MEM_PRIO_ARB1_4_ARB2_AHB_CPUS_PRIO_SHIFT)
#  define MEMCTRL_MEM_PRIO_ARB1_4_ARB2_AHB_CPUS_PRIO(n) ((uint32_t)(n) << MEMCTRL_MEM_PRIO_ARB1_4_ARB2_AHB_CPUS_PRIO_SHIFT)
#define MEMCTRL_MEM_PRIO_ARB1_4_ARB2_AHB_DMA_PRIO_SHIFT (12)  /* Bits 12-13 */
#define MEMCTRL_MEM_PRIO_ARB1_4_ARB2_AHB_DMA_PRIO_MASK (0x3 << MEMCTRL_MEM_PRIO_ARB1_4_ARB2_AHB_DMA_PRIO_SHIFT)
#  define MEMCTRL_MEM_PRIO_ARB1_4_ARB2_AHB_DMA_PRIO(n) ((uint32_t)(n) << MEMCTRL_MEM_PRIO_ARB1_4_ARB2_AHB_DMA_PRIO_SHIFT)
#define MEMCTRL_MEM_PRIO_ARB1_4_ARB2_SNC_PRIO_SHIFT (14)      /* Bits 14-15 */
#define MEMCTRL_MEM_PRIO_ARB1_4_ARB2_SNC_PRIO_MASK (0x3 << MEMCTRL_MEM_PRIO_ARB1_4_ARB2_SNC_PRIO_SHIFT)
#  define MEMCTRL_MEM_PRIO_ARB1_4_ARB2_SNC_PRIO(n) ((uint32_t)(n) << MEMCTRL_MEM_PRIO_ARB1_4_ARB2_SNC_PRIO_SHIFT)
#define MEMCTRL_MEM_PRIO_ARB1_4_ARB3_AHB_CPUC_PRIO_SHIFT (16) /* Bits 16-17 */
#define MEMCTRL_MEM_PRIO_ARB1_4_ARB3_AHB_CPUC_PRIO_MASK (0x3 << MEMCTRL_MEM_PRIO_ARB1_4_ARB3_AHB_CPUC_PRIO_SHIFT)
#  define MEMCTRL_MEM_PRIO_ARB1_4_ARB3_AHB_CPUC_PRIO(n) ((uint32_t)(n) << MEMCTRL_MEM_PRIO_ARB1_4_ARB3_AHB_CPUC_PRIO_SHIFT)
#define MEMCTRL_MEM_PRIO_ARB1_4_ARB3_AHB_CPUS_PRIO_SHIFT (18) /* Bits 18-19 */
#define MEMCTRL_MEM_PRIO_ARB1_4_ARB3_AHB_CPUS_PRIO_MASK (0x3 << MEMCTRL_MEM_PRIO_ARB1_4_ARB3_AHB_CPUS_PRIO_SHIFT)
#  define MEMCTRL_MEM_PRIO_ARB1_4_ARB3_AHB_CPUS_PRIO(n) ((uint32_t)(n) << MEMCTRL_MEM_PRIO_ARB1_4_ARB3_AHB_CPUS_PRIO_SHIFT)
#define MEMCTRL_MEM_PRIO_ARB1_4_ARB3_AHB_DMA_PRIO_SHIFT (20)  /* Bits 20-21 */
#define MEMCTRL_MEM_PRIO_ARB1_4_ARB3_AHB_DMA_PRIO_MASK (0x3 << MEMCTRL_MEM_PRIO_ARB1_4_ARB3_AHB_DMA_PRIO_SHIFT)
#  define MEMCTRL_MEM_PRIO_ARB1_4_ARB3_AHB_DMA_PRIO(n) ((uint32_t)(n) << MEMCTRL_MEM_PRIO_ARB1_4_ARB3_AHB_DMA_PRIO_SHIFT)
#define MEMCTRL_MEM_PRIO_ARB1_4_ARB4_AHB_CPUS_PRIO_SHIFT (26) /* Bits 26-27 */
#define MEMCTRL_MEM_PRIO_ARB1_4_ARB4_AHB_CPUS_PRIO_MASK (0x3 << MEMCTRL_MEM_PRIO_ARB1_4_ARB4_AHB_CPUS_PRIO_SHIFT)
#  define MEMCTRL_MEM_PRIO_ARB1_4_ARB4_AHB_CPUS_PRIO(n) ((uint32_t)(n) << MEMCTRL_MEM_PRIO_ARB1_4_ARB4_AHB_CPUS_PRIO_SHIFT)
#define MEMCTRL_MEM_PRIO_ARB1_4_ARB4_AHB_DMA_PRIO_SHIFT (28)  /* Bits 28-29 */
#define MEMCTRL_MEM_PRIO_ARB1_4_ARB4_AHB_DMA_PRIO_MASK (0x3 << MEMCTRL_MEM_PRIO_ARB1_4_ARB4_AHB_DMA_PRIO_SHIFT)
#  define MEMCTRL_MEM_PRIO_ARB1_4_ARB4_AHB_DMA_PRIO(n) ((uint32_t)(n) << MEMCTRL_MEM_PRIO_ARB1_4_ARB4_AHB_DMA_PRIO_SHIFT)

/* MEM_PRIO_ARB5_8 register */

#define MEMCTRL_MEM_PRIO_ARB5_8_ARB5_AHB_CPUS_PRIO_SHIFT (2)  /* Bits 2-3 */
#define MEMCTRL_MEM_PRIO_ARB5_8_ARB5_AHB_CPUS_PRIO_MASK (0x3 << MEMCTRL_MEM_PRIO_ARB5_8_ARB5_AHB_CPUS_PRIO_SHIFT)
#  define MEMCTRL_MEM_PRIO_ARB5_8_ARB5_AHB_CPUS_PRIO(n) ((uint32_t)(n) << MEMCTRL_MEM_PRIO_ARB5_8_ARB5_AHB_CPUS_PRIO_SHIFT)
#define MEMCTRL_MEM_PRIO_ARB5_8_ARB5_AHB_DMA_PRIO_SHIFT (4)   /* Bits 4-5 */
#define MEMCTRL_MEM_PRIO_ARB5_8_ARB5_AHB_DMA_PRIO_MASK (0x3 << MEMCTRL_MEM_PRIO_ARB5_8_ARB5_AHB_DMA_PRIO_SHIFT)
#  define MEMCTRL_MEM_PRIO_ARB5_8_ARB5_AHB_DMA_PRIO(n) ((uint32_t)(n) << MEMCTRL_MEM_PRIO_ARB5_8_ARB5_AHB_DMA_PRIO_SHIFT)
#define MEMCTRL_MEM_PRIO_ARB5_8_ARB6_AHB_CPUS_PRIO_SHIFT (10) /* Bits 10-11 */
#define MEMCTRL_MEM_PRIO_ARB5_8_ARB6_AHB_CPUS_PRIO_MASK (0x3 << MEMCTRL_MEM_PRIO_ARB5_8_ARB6_AHB_CPUS_PRIO_SHIFT)
#  define MEMCTRL_MEM_PRIO_ARB5_8_ARB6_AHB_CPUS_PRIO(n) ((uint32_t)(n) << MEMCTRL_MEM_PRIO_ARB5_8_ARB6_AHB_CPUS_PRIO_SHIFT)
#define MEMCTRL_MEM_PRIO_ARB5_8_ARB6_AHB_DMA_PRIO_SHIFT (12)  /* Bits 12-13 */
#define MEMCTRL_MEM_PRIO_ARB5_8_ARB6_AHB_DMA_PRIO_MASK (0x3 << MEMCTRL_MEM_PRIO_ARB5_8_ARB6_AHB_DMA_PRIO_SHIFT)
#  define MEMCTRL_MEM_PRIO_ARB5_8_ARB6_AHB_DMA_PRIO(n) ((uint32_t)(n) << MEMCTRL_MEM_PRIO_ARB5_8_ARB6_AHB_DMA_PRIO_SHIFT)
#define MEMCTRL_MEM_PRIO_ARB5_8_ARB7_AHB_CPUS_PRIO_SHIFT (18) /* Bits 18-19 */
#define MEMCTRL_MEM_PRIO_ARB5_8_ARB7_AHB_CPUS_PRIO_MASK (0x3 << MEMCTRL_MEM_PRIO_ARB5_8_ARB7_AHB_CPUS_PRIO_SHIFT)
#  define MEMCTRL_MEM_PRIO_ARB5_8_ARB7_AHB_CPUS_PRIO(n) ((uint32_t)(n) << MEMCTRL_MEM_PRIO_ARB5_8_ARB7_AHB_CPUS_PRIO_SHIFT)
#define MEMCTRL_MEM_PRIO_ARB5_8_ARB7_AHB_DMA_PRIO_SHIFT (20)  /* Bits 20-21 */
#define MEMCTRL_MEM_PRIO_ARB5_8_ARB7_AHB_DMA_PRIO_MASK (0x3 << MEMCTRL_MEM_PRIO_ARB5_8_ARB7_AHB_DMA_PRIO_SHIFT)
#  define MEMCTRL_MEM_PRIO_ARB5_8_ARB7_AHB_DMA_PRIO(n) ((uint32_t)(n) << MEMCTRL_MEM_PRIO_ARB5_8_ARB7_AHB_DMA_PRIO_SHIFT)
#define MEMCTRL_MEM_PRIO_ARB5_8_ARB8_AHB_CPUS_PRIO_SHIFT (26) /* Bits 26-27 */
#define MEMCTRL_MEM_PRIO_ARB5_8_ARB8_AHB_CPUS_PRIO_MASK (0x3 << MEMCTRL_MEM_PRIO_ARB5_8_ARB8_AHB_CPUS_PRIO_SHIFT)
#  define MEMCTRL_MEM_PRIO_ARB5_8_ARB8_AHB_CPUS_PRIO(n) ((uint32_t)(n) << MEMCTRL_MEM_PRIO_ARB5_8_ARB8_AHB_CPUS_PRIO_SHIFT)
#define MEMCTRL_MEM_PRIO_ARB5_8_ARB8_AHB_DMA_PRIO_SHIFT (28)  /* Bits 28-29 */
#define MEMCTRL_MEM_PRIO_ARB5_8_ARB8_AHB_DMA_PRIO_MASK (0x3 << MEMCTRL_MEM_PRIO_ARB5_8_ARB8_AHB_DMA_PRIO_SHIFT)
#  define MEMCTRL_MEM_PRIO_ARB5_8_ARB8_AHB_DMA_PRIO(n) ((uint32_t)(n) << MEMCTRL_MEM_PRIO_ARB5_8_ARB8_AHB_DMA_PRIO_SHIFT)
#define MEMCTRL_MEM_PRIO_ARB5_8_ARB8_SNC_PRIO_SHIFT (30)      /* Bits 30-31 */
#define MEMCTRL_MEM_PRIO_ARB5_8_ARB8_SNC_PRIO_MASK (0x3 << MEMCTRL_MEM_PRIO_ARB5_8_ARB8_SNC_PRIO_SHIFT)
#  define MEMCTRL_MEM_PRIO_ARB5_8_ARB8_SNC_PRIO(n) ((uint32_t)(n) << MEMCTRL_MEM_PRIO_ARB5_8_ARB8_SNC_PRIO_SHIFT)

/* MEM_STALL register */

#define MEMCTRL_MEM_STALL_AHB_CPUC_MAX_STALL_SHIFT (0) /* Bits 0-3 */
#define MEMCTRL_MEM_STALL_AHB_CPUC_MAX_STALL_MASK (0xf << MEMCTRL_MEM_STALL_AHB_CPUC_MAX_STALL_SHIFT)
#  define MEMCTRL_MEM_STALL_AHB_CPUC_MAX_STALL(n) ((uint32_t)(n) << MEMCTRL_MEM_STALL_AHB_CPUC_MAX_STALL_SHIFT)
#define MEMCTRL_MEM_STALL_AHB_CPUS_MAX_STALL_SHIFT (4) /* Bits 4-7 */
#define MEMCTRL_MEM_STALL_AHB_CPUS_MAX_STALL_MASK (0xf << MEMCTRL_MEM_STALL_AHB_CPUS_MAX_STALL_SHIFT)
#  define MEMCTRL_MEM_STALL_AHB_CPUS_MAX_STALL(n) ((uint32_t)(n) << MEMCTRL_MEM_STALL_AHB_CPUS_MAX_STALL_SHIFT)
#define MEMCTRL_MEM_STALL_AHB_DMA_MAX_STALL_SHIFT (8)  /* Bits 8-11 */
#define MEMCTRL_MEM_STALL_AHB_DMA_MAX_STALL_MASK (0xf << MEMCTRL_MEM_STALL_AHB_DMA_MAX_STALL_SHIFT)
#  define MEMCTRL_MEM_STALL_AHB_DMA_MAX_STALL(n) ((uint32_t)(n) << MEMCTRL_MEM_STALL_AHB_DMA_MAX_STALL_SHIFT)
#define MEMCTRL_MEM_STALL_SNC_MAX_STALL_SHIFT (12)     /* Bits 12-15 */
#define MEMCTRL_MEM_STALL_SNC_MAX_STALL_MASK (0xf << MEMCTRL_MEM_STALL_SNC_MAX_STALL_SHIFT)
#  define MEMCTRL_MEM_STALL_SNC_MAX_STALL(n) ((uint32_t)(n) << MEMCTRL_MEM_STALL_SNC_MAX_STALL_SHIFT)

/* MEM_STATUS register */

#define MEMCTRL_MEM_STATUS_AHB_CPUS_WRITE_BUFF (1 << 0)    /* Bit 0 */
#define MEMCTRL_MEM_STATUS_AHB_CPUC_WRITE_BUFF (1 << 1)    /* Bit 1 */
#define MEMCTRL_MEM_STATUS_AHB_DMA_WRITE_BUFF (1 << 2)     /* Bit 2 */
#define MEMCTRL_MEM_STATUS_AHB_SNC_WRITE_BUFF (1 << 3)     /* Bit 3 */
#define MEMCTRL_MEM_STATUS_AHB_CPUS_CLR_WR_BUFF (1 << 4)   /* Bit 4 */
#define MEMCTRL_MEM_STATUS_AHB_CPUC_CLR_WR_BUFF (1 << 5)   /* Bit 5 */
#define MEMCTRL_MEM_STATUS_AHB_DMA_CLR_WR_BUFF (1 << 6)    /* Bit 6 */
#define MEMCTRL_MEM_STATUS_AHB_SNC_CLR_WR_BUFF (1 << 7)    /* Bit 7 */
#define MEMCTRL_MEM_STATUS_AHB_CPUS_WR_BUFF_CNT_SHIFT (8)  /* Bits 8-11 */
#define MEMCTRL_MEM_STATUS_AHB_CPUS_WR_BUFF_CNT_MASK (0xf << MEMCTRL_MEM_STATUS_AHB_CPUS_WR_BUFF_CNT_SHIFT)
#  define MEMCTRL_MEM_STATUS_AHB_CPUS_WR_BUFF_CNT(n) ((uint32_t)(n) << MEMCTRL_MEM_STATUS_AHB_CPUS_WR_BUFF_CNT_SHIFT)
#define MEMCTRL_MEM_STATUS_AHB_CPUC_WR_BUFF_CNT_SHIFT (12) /* Bits 12-15 */
#define MEMCTRL_MEM_STATUS_AHB_CPUC_WR_BUFF_CNT_MASK (0xf << MEMCTRL_MEM_STATUS_AHB_CPUC_WR_BUFF_CNT_SHIFT)
#  define MEMCTRL_MEM_STATUS_AHB_CPUC_WR_BUFF_CNT(n) ((uint32_t)(n) << MEMCTRL_MEM_STATUS_AHB_CPUC_WR_BUFF_CNT_SHIFT)
#define MEMCTRL_MEM_STATUS_AHB_DMA_WR_BUFF_CNT_SHIFT (16)  /* Bits 16-19 */
#define MEMCTRL_MEM_STATUS_AHB_DMA_WR_BUFF_CNT_MASK (0xf << MEMCTRL_MEM_STATUS_AHB_DMA_WR_BUFF_CNT_SHIFT)
#  define MEMCTRL_MEM_STATUS_AHB_DMA_WR_BUFF_CNT(n) ((uint32_t)(n) << MEMCTRL_MEM_STATUS_AHB_DMA_WR_BUFF_CNT_SHIFT)
#define MEMCTRL_MEM_STATUS_AHB_SNC_WR_BUFF_CNT_SHIFT (20)  /* Bits 20-23 */
#define MEMCTRL_MEM_STATUS_AHB_SNC_WR_BUFF_CNT_MASK (0xf << MEMCTRL_MEM_STATUS_AHB_SNC_WR_BUFF_CNT_SHIFT)
#  define MEMCTRL_MEM_STATUS_AHB_SNC_WR_BUFF_CNT(n) ((uint32_t)(n) << MEMCTRL_MEM_STATUS_AHB_SNC_WR_BUFF_CNT_SHIFT)

/* MEM_STATUS2 register */

#define MEMCTRL_MEM_STATUS2_RAM0_OFF_BUT_ACCESS (1 << 0)   /* Bit 0 */
#define MEMCTRL_MEM_STATUS2_RAM1_OFF_BUT_ACCESS (1 << 1)   /* Bit 1 */
#define MEMCTRL_MEM_STATUS2_RAM2_OFF_BUT_ACCESS (1 << 2)   /* Bit 2 */
#define MEMCTRL_MEM_STATUS2_RAM3_OFF_BUT_ACCESS (1 << 3)   /* Bit 3 */
#define MEMCTRL_MEM_STATUS2_RAM4_OFF_BUT_ACCESS (1 << 4)   /* Bit 4 */
#define MEMCTRL_MEM_STATUS2_RAM5_OFF_BUT_ACCESS (1 << 5)   /* Bit 5 */
#define MEMCTRL_MEM_STATUS2_RAM6_OFF_BUT_ACCESS (1 << 6)   /* Bit 6 */
#define MEMCTRL_MEM_STATUS2_RAM7_OFF_BUT_ACCESS (1 << 7)   /* Bit 7 */
#define MEMCTRL_MEM_STATUS2_RAM8_OFF_BUT_ACCESS (1 << 8)   /* Bit 8 */
#define MEMCTRL_MEM_STATUS2_RAM9_OFF_BUT_ACCESS (1 << 9)   /* Bit 9 */
#define MEMCTRL_MEM_STATUS2_RAM10_OFF_BUT_ACCESS (1 << 10) /* Bit 10 */
#define MEMCTRL_MEM_STATUS2_RAM11_OFF_BUT_ACCESS (1 << 11) /* Bit 11 */
#define MEMCTRL_MEM_STATUS2_RAM12_OFF_BUT_ACCESS (1 << 12) /* Bit 12 */
#define MEMCTRL_MEM_STATUS2_RAM13_OFF_BUT_ACCESS (1 << 13) /* Bit 13 */

/* CMI_CODE_BASE register */

#define MEMCTRL_CMI_CODE_BASE_CMI_CODE_BASE_ADDR_SHIFT (0) /* Bits 0-19 */
#define MEMCTRL_CMI_CODE_BASE_CMI_CODE_BASE_ADDR_MASK (0xfffff << MEMCTRL_CMI_CODE_BASE_CMI_CODE_BASE_ADDR_SHIFT)
#  define MEMCTRL_CMI_CODE_BASE_CMI_CODE_BASE_ADDR(n) ((uint32_t)(n) << MEMCTRL_CMI_CODE_BASE_CMI_CODE_BASE_ADDR_SHIFT)

/* CMI_DATA_BASE register */

#define MEMCTRL_CMI_DATA_BASE_CMI_DATA_BASE_ADDR_SHIFT (2) /* Bits 2-19 */
#define MEMCTRL_CMI_DATA_BASE_CMI_DATA_BASE_ADDR_MASK (0x3ffff << MEMCTRL_CMI_DATA_BASE_CMI_DATA_BASE_ADDR_SHIFT)
#  define MEMCTRL_CMI_DATA_BASE_CMI_DATA_BASE_ADDR(n) ((uint32_t)(n) << MEMCTRL_CMI_DATA_BASE_CMI_DATA_BASE_ADDR_SHIFT)

/* CMI_SHARED_BASE register */

#define MEMCTRL_CMI_SHARED_BASE_CMI_SHARED_BASE_ADDR_SHIFT (10) /* Bits 10-19 */
#define MEMCTRL_CMI_SHARED_BASE_CMI_SHARED_BASE_ADDR_MASK (0x3ff << MEMCTRL_CMI_SHARED_BASE_CMI_SHARED_BASE_ADDR_SHIFT)
#  define MEMCTRL_CMI_SHARED_BASE_CMI_SHARED_BASE_ADDR(n) ((uint32_t)(n) << MEMCTRL_CMI_SHARED_BASE_CMI_SHARED_BASE_ADDR_SHIFT)

/* CMI_END register */

#define MEMCTRL_CMI_END_CMI_END_ADDR_SHIFT (10) /* Bits 10-19 */
#define MEMCTRL_CMI_END_CMI_END_ADDR_MASK (0x3ff << MEMCTRL_CMI_END_CMI_END_ADDR_SHIFT)
#  define MEMCTRL_CMI_END_CMI_END_ADDR(n) ((uint32_t)(n) << MEMCTRL_CMI_END_CMI_END_ADDR_SHIFT)

/* CMAC_STATUS register */

#define MEMCTRL_CMAC_STATUS_AHB_SYS2CMAC_WRITE_BUFF (1 << 0)   /* Bit 0 */
#define MEMCTRL_CMAC_STATUS_AHB_RFMON_WRITE_BUFF (1 << 1)      /* Bit 1 */
#define MEMCTRL_CMAC_STATUS_AHB_SYS2CMAC_CLR_WR_BUFF (1 << 2)  /* Bit 2 */
#define MEMCTRL_CMAC_STATUS_AHB_RFMON_CLR_WR_BUFF (1 << 3)     /* Bit 3 */
#define MEMCTRL_CMAC_STATUS_AHB_SYS2CMAC_WR_BUFF_CNT_SHIFT (4) /* Bits 4-7 */
#define MEMCTRL_CMAC_STATUS_AHB_SYS2CMAC_WR_BUFF_CNT_MASK (0xf << MEMCTRL_CMAC_STATUS_AHB_SYS2CMAC_WR_BUFF_CNT_SHIFT)
#  define MEMCTRL_CMAC_STATUS_AHB_SYS2CMAC_WR_BUFF_CNT(n) ((uint32_t)(n) << MEMCTRL_CMAC_STATUS_AHB_SYS2CMAC_WR_BUFF_CNT_SHIFT)
#define MEMCTRL_CMAC_STATUS_AHB_RFMON_WR_BUFF_CNT_SHIFT (8)    /* Bits 8-11 */
#define MEMCTRL_CMAC_STATUS_AHB_RFMON_WR_BUFF_CNT_MASK (0xf << MEMCTRL_CMAC_STATUS_AHB_RFMON_WR_BUFF_CNT_SHIFT)
#  define MEMCTRL_CMAC_STATUS_AHB_RFMON_WR_BUFF_CNT(n) ((uint32_t)(n) << MEMCTRL_CMAC_STATUS_AHB_RFMON_WR_BUFF_CNT_SHIFT)
#define MEMCTRL_CMAC_STATUS_CMI_NOT_READY (1 << 12)            /* Bit 12 */
#define MEMCTRL_CMAC_STATUS_CMI_CLEAR_READY (1 << 13)          /* Bit 13 */

/* BUSY_SET register */

#define MEMCTRL_BUSY_SET_BUSY_UART_SHIFT (0)   /* Bits 0-1 */
#define MEMCTRL_BUSY_SET_BUSY_UART_MASK (0x3 << MEMCTRL_BUSY_SET_BUSY_UART_SHIFT)
#  define MEMCTRL_BUSY_SET_BUSY_UART(n) ((uint32_t)(n) << MEMCTRL_BUSY_SET_BUSY_UART_SHIFT)
#define MEMCTRL_BUSY_SET_BUSY_UART2_SHIFT (2)  /* Bits 2-3 */
#define MEMCTRL_BUSY_SET_BUSY_UART2_MASK (0x3 << MEMCTRL_BUSY_SET_BUSY_UART2_SHIFT)
#  define MEMCTRL_BUSY_SET_BUSY_UART2(n) ((uint32_t)(n) << MEMCTRL_BUSY_SET_BUSY_UART2_SHIFT)
#define MEMCTRL_BUSY_SET_BUSY_UART3_SHIFT (4)  /* Bits 4-5 */
#define MEMCTRL_BUSY_SET_BUSY_UART3_MASK (0x3 << MEMCTRL_BUSY_SET_BUSY_UART3_SHIFT)
#  define MEMCTRL_BUSY_SET_BUSY_UART3(n) ((uint32_t)(n) << MEMCTRL_BUSY_SET_BUSY_UART3_SHIFT)
#define MEMCTRL_BUSY_SET_BUSY_SPI_SHIFT (6)    /* Bits 6-7 */
#define MEMCTRL_BUSY_SET_BUSY_SPI_MASK (0x3 << MEMCTRL_BUSY_SET_BUSY_SPI_SHIFT)
#  define MEMCTRL_BUSY_SET_BUSY_SPI(n) ((uint32_t)(n) << MEMCTRL_BUSY_SET_BUSY_SPI_SHIFT)
#define MEMCTRL_BUSY_SET_BUSY_SPI2_SHIFT (8)   /* Bits 8-9 */
#define MEMCTRL_BUSY_SET_BUSY_SPI2_MASK (0x3 << MEMCTRL_BUSY_SET_BUSY_SPI2_SHIFT)
#  define MEMCTRL_BUSY_SET_BUSY_SPI2(n) ((uint32_t)(n) << MEMCTRL_BUSY_SET_BUSY_SPI2_SHIFT)
#define MEMCTRL_BUSY_SET_BUSY_SPI3_SHIFT (10)  /* Bits 10-11 */
#define MEMCTRL_BUSY_SET_BUSY_SPI3_MASK (0x3 << MEMCTRL_BUSY_SET_BUSY_SPI3_SHIFT)
#  define MEMCTRL_BUSY_SET_BUSY_SPI3(n) ((uint32_t)(n) << MEMCTRL_BUSY_SET_BUSY_SPI3_SHIFT)
#define MEMCTRL_BUSY_SET_BUSY_I2C_SHIFT (12)   /* Bits 12-13 */
#define MEMCTRL_BUSY_SET_BUSY_I2C_MASK (0x3 << MEMCTRL_BUSY_SET_BUSY_I2C_SHIFT)
#  define MEMCTRL_BUSY_SET_BUSY_I2C(n) ((uint32_t)(n) << MEMCTRL_BUSY_SET_BUSY_I2C_SHIFT)
#define MEMCTRL_BUSY_SET_BUSY_I2C2_SHIFT (14)  /* Bits 14-15 */
#define MEMCTRL_BUSY_SET_BUSY_I2C2_MASK (0x3 << MEMCTRL_BUSY_SET_BUSY_I2C2_SHIFT)
#  define MEMCTRL_BUSY_SET_BUSY_I2C2(n) ((uint32_t)(n) << MEMCTRL_BUSY_SET_BUSY_I2C2_SHIFT)
#define MEMCTRL_BUSY_SET_BUSY_I2C3_SHIFT (16)  /* Bits 16-17 */
#define MEMCTRL_BUSY_SET_BUSY_I2C3_MASK (0x3 << MEMCTRL_BUSY_SET_BUSY_I2C3_SHIFT)
#  define MEMCTRL_BUSY_SET_BUSY_I2C3(n) ((uint32_t)(n) << MEMCTRL_BUSY_SET_BUSY_I2C3_SHIFT)
#define MEMCTRL_BUSY_SET_BUSY_I3C_SHIFT (18)   /* Bits 18-19 */
#define MEMCTRL_BUSY_SET_BUSY_I3C_MASK (0x3 << MEMCTRL_BUSY_SET_BUSY_I3C_SHIFT)
#  define MEMCTRL_BUSY_SET_BUSY_I3C(n) ((uint32_t)(n) << MEMCTRL_BUSY_SET_BUSY_I3C_SHIFT)
#define MEMCTRL_BUSY_SET_BUSY_PCM_SHIFT (20)   /* Bits 20-21 */
#define MEMCTRL_BUSY_SET_BUSY_PCM_MASK (0x3 << MEMCTRL_BUSY_SET_BUSY_PCM_SHIFT)
#  define MEMCTRL_BUSY_SET_BUSY_PCM(n) ((uint32_t)(n) << MEMCTRL_BUSY_SET_BUSY_PCM_SHIFT)
#define MEMCTRL_BUSY_SET_BUSY_PDM_SHIFT (22)   /* Bits 22-23 */
#define MEMCTRL_BUSY_SET_BUSY_PDM_MASK (0x3 << MEMCTRL_BUSY_SET_BUSY_PDM_SHIFT)
#  define MEMCTRL_BUSY_SET_BUSY_PDM(n) ((uint32_t)(n) << MEMCTRL_BUSY_SET_BUSY_PDM_SHIFT)
#define MEMCTRL_BUSY_SET_BUSY_SRC_SHIFT (24)   /* Bits 24-25 */
#define MEMCTRL_BUSY_SET_BUSY_SRC_MASK (0x3 << MEMCTRL_BUSY_SET_BUSY_SRC_SHIFT)
#  define MEMCTRL_BUSY_SET_BUSY_SRC(n) ((uint32_t)(n) << MEMCTRL_BUSY_SET_BUSY_SRC_SHIFT)
#define MEMCTRL_BUSY_SET_BUSY_SRC2_SHIFT (26)  /* Bits 26-27 */
#define MEMCTRL_BUSY_SET_BUSY_SRC2_MASK (0x3 << MEMCTRL_BUSY_SET_BUSY_SRC2_SHIFT)
#  define MEMCTRL_BUSY_SET_BUSY_SRC2(n) ((uint32_t)(n) << MEMCTRL_BUSY_SET_BUSY_SRC2_SHIFT)
#define MEMCTRL_BUSY_SET_BUSY_GPADC_SHIFT (28) /* Bits 28-29 */
#define MEMCTRL_BUSY_SET_BUSY_GPADC_MASK (0x3 << MEMCTRL_BUSY_SET_BUSY_GPADC_SHIFT)
#  define MEMCTRL_BUSY_SET_BUSY_GPADC(n) ((uint32_t)(n) << MEMCTRL_BUSY_SET_BUSY_GPADC_SHIFT)
#define MEMCTRL_BUSY_SET_BUSY_SDADC_SHIFT (30) /* Bits 30-31 */
#define MEMCTRL_BUSY_SET_BUSY_SDADC_MASK (0x3 << MEMCTRL_BUSY_SET_BUSY_SDADC_SHIFT)
#  define MEMCTRL_BUSY_SET_BUSY_SDADC(n) ((uint32_t)(n) << MEMCTRL_BUSY_SET_BUSY_SDADC_SHIFT)

/* BUSY_SET_REG2 register */

#define MEMCTRL_BUSY_SET_REG2_BUSY_TIMER_SHIFT (0)   /* Bits 0-1 */
#define MEMCTRL_BUSY_SET_REG2_BUSY_TIMER_MASK (0x3 << MEMCTRL_BUSY_SET_REG2_BUSY_TIMER_SHIFT)
#  define MEMCTRL_BUSY_SET_REG2_BUSY_TIMER(n) ((uint32_t)(n) << MEMCTRL_BUSY_SET_REG2_BUSY_TIMER_SHIFT)
#define MEMCTRL_BUSY_SET_REG2_BUSY_TIMER2_SHIFT (2)  /* Bits 2-3 */
#define MEMCTRL_BUSY_SET_REG2_BUSY_TIMER2_MASK (0x3 << MEMCTRL_BUSY_SET_REG2_BUSY_TIMER2_SHIFT)
#  define MEMCTRL_BUSY_SET_REG2_BUSY_TIMER2(n) ((uint32_t)(n) << MEMCTRL_BUSY_SET_REG2_BUSY_TIMER2_SHIFT)
#define MEMCTRL_BUSY_SET_REG2_BUSY_TIMER3_SHIFT (4)  /* Bits 4-5 */
#define MEMCTRL_BUSY_SET_REG2_BUSY_TIMER3_MASK (0x3 << MEMCTRL_BUSY_SET_REG2_BUSY_TIMER3_SHIFT)
#  define MEMCTRL_BUSY_SET_REG2_BUSY_TIMER3(n) ((uint32_t)(n) << MEMCTRL_BUSY_SET_REG2_BUSY_TIMER3_SHIFT)
#define MEMCTRL_BUSY_SET_REG2_BUSY_TIMER4_SHIFT (6)  /* Bits 6-7 */
#define MEMCTRL_BUSY_SET_REG2_BUSY_TIMER4_MASK (0x3 << MEMCTRL_BUSY_SET_REG2_BUSY_TIMER4_SHIFT)
#  define MEMCTRL_BUSY_SET_REG2_BUSY_TIMER4(n) ((uint32_t)(n) << MEMCTRL_BUSY_SET_REG2_BUSY_TIMER4_SHIFT)
#define MEMCTRL_BUSY_SET_REG2_BUSY_TIMER5_SHIFT (8)  /* Bits 8-9 */
#define MEMCTRL_BUSY_SET_REG2_BUSY_TIMER5_MASK (0x3 << MEMCTRL_BUSY_SET_REG2_BUSY_TIMER5_SHIFT)
#  define MEMCTRL_BUSY_SET_REG2_BUSY_TIMER5(n) ((uint32_t)(n) << MEMCTRL_BUSY_SET_REG2_BUSY_TIMER5_SHIFT)
#define MEMCTRL_BUSY_SET_REG2_BUSY_TIMER6_SHIFT (10) /* Bits 10-11 */
#define MEMCTRL_BUSY_SET_REG2_BUSY_TIMER6_MASK (0x3 << MEMCTRL_BUSY_SET_REG2_BUSY_TIMER6_SHIFT)
#  define MEMCTRL_BUSY_SET_REG2_BUSY_TIMER6(n) ((uint32_t)(n) << MEMCTRL_BUSY_SET_REG2_BUSY_TIMER6_SHIFT)

/* BUSY_RESET register */

#define MEMCTRL_BUSY_RESET_BUSY_UART_SHIFT (0)   /* Bits 0-1 */
#define MEMCTRL_BUSY_RESET_BUSY_UART_MASK (0x3 << MEMCTRL_BUSY_RESET_BUSY_UART_SHIFT)
#  define MEMCTRL_BUSY_RESET_BUSY_UART(n) ((uint32_t)(n) << MEMCTRL_BUSY_RESET_BUSY_UART_SHIFT)
#define MEMCTRL_BUSY_RESET_BUSY_UART2_SHIFT (2)  /* Bits 2-3 */
#define MEMCTRL_BUSY_RESET_BUSY_UART2_MASK (0x3 << MEMCTRL_BUSY_RESET_BUSY_UART2_SHIFT)
#  define MEMCTRL_BUSY_RESET_BUSY_UART2(n) ((uint32_t)(n) << MEMCTRL_BUSY_RESET_BUSY_UART2_SHIFT)
#define MEMCTRL_BUSY_RESET_BUSY_UART3_SHIFT (4)  /* Bits 4-5 */
#define MEMCTRL_BUSY_RESET_BUSY_UART3_MASK (0x3 << MEMCTRL_BUSY_RESET_BUSY_UART3_SHIFT)
#  define MEMCTRL_BUSY_RESET_BUSY_UART3(n) ((uint32_t)(n) << MEMCTRL_BUSY_RESET_BUSY_UART3_SHIFT)
#define MEMCTRL_BUSY_RESET_BUSY_SPI_SHIFT (6)    /* Bits 6-7 */
#define MEMCTRL_BUSY_RESET_BUSY_SPI_MASK (0x3 << MEMCTRL_BUSY_RESET_BUSY_SPI_SHIFT)
#  define MEMCTRL_BUSY_RESET_BUSY_SPI(n) ((uint32_t)(n) << MEMCTRL_BUSY_RESET_BUSY_SPI_SHIFT)
#define MEMCTRL_BUSY_RESET_BUSY_SPI2_SHIFT (8)   /* Bits 8-9 */
#define MEMCTRL_BUSY_RESET_BUSY_SPI2_MASK (0x3 << MEMCTRL_BUSY_RESET_BUSY_SPI2_SHIFT)
#  define MEMCTRL_BUSY_RESET_BUSY_SPI2(n) ((uint32_t)(n) << MEMCTRL_BUSY_RESET_BUSY_SPI2_SHIFT)
#define MEMCTRL_BUSY_RESET_BUSY_SPI3_SHIFT (10)  /* Bits 10-11 */
#define MEMCTRL_BUSY_RESET_BUSY_SPI3_MASK (0x3 << MEMCTRL_BUSY_RESET_BUSY_SPI3_SHIFT)
#  define MEMCTRL_BUSY_RESET_BUSY_SPI3(n) ((uint32_t)(n) << MEMCTRL_BUSY_RESET_BUSY_SPI3_SHIFT)
#define MEMCTRL_BUSY_RESET_BUSY_I2C_SHIFT (12)   /* Bits 12-13 */
#define MEMCTRL_BUSY_RESET_BUSY_I2C_MASK (0x3 << MEMCTRL_BUSY_RESET_BUSY_I2C_SHIFT)
#  define MEMCTRL_BUSY_RESET_BUSY_I2C(n) ((uint32_t)(n) << MEMCTRL_BUSY_RESET_BUSY_I2C_SHIFT)
#define MEMCTRL_BUSY_RESET_BUSY_I2C2_SHIFT (14)  /* Bits 14-15 */
#define MEMCTRL_BUSY_RESET_BUSY_I2C2_MASK (0x3 << MEMCTRL_BUSY_RESET_BUSY_I2C2_SHIFT)
#  define MEMCTRL_BUSY_RESET_BUSY_I2C2(n) ((uint32_t)(n) << MEMCTRL_BUSY_RESET_BUSY_I2C2_SHIFT)
#define MEMCTRL_BUSY_RESET_BUSY_I2C3_SHIFT (16)  /* Bits 16-17 */
#define MEMCTRL_BUSY_RESET_BUSY_I2C3_MASK (0x3 << MEMCTRL_BUSY_RESET_BUSY_I2C3_SHIFT)
#  define MEMCTRL_BUSY_RESET_BUSY_I2C3(n) ((uint32_t)(n) << MEMCTRL_BUSY_RESET_BUSY_I2C3_SHIFT)
#define MEMCTRL_BUSY_RESET_BUSY_I3C_SHIFT (18)   /* Bits 18-19 */
#define MEMCTRL_BUSY_RESET_BUSY_I3C_MASK (0x3 << MEMCTRL_BUSY_RESET_BUSY_I3C_SHIFT)
#  define MEMCTRL_BUSY_RESET_BUSY_I3C(n) ((uint32_t)(n) << MEMCTRL_BUSY_RESET_BUSY_I3C_SHIFT)
#define MEMCTRL_BUSY_RESET_BUSY_PCM_SHIFT (20)   /* Bits 20-21 */
#define MEMCTRL_BUSY_RESET_BUSY_PCM_MASK (0x3 << MEMCTRL_BUSY_RESET_BUSY_PCM_SHIFT)
#  define MEMCTRL_BUSY_RESET_BUSY_PCM(n) ((uint32_t)(n) << MEMCTRL_BUSY_RESET_BUSY_PCM_SHIFT)
#define MEMCTRL_BUSY_RESET_BUSY_PDM_SHIFT (22)   /* Bits 22-23 */
#define MEMCTRL_BUSY_RESET_BUSY_PDM_MASK (0x3 << MEMCTRL_BUSY_RESET_BUSY_PDM_SHIFT)
#  define MEMCTRL_BUSY_RESET_BUSY_PDM(n) ((uint32_t)(n) << MEMCTRL_BUSY_RESET_BUSY_PDM_SHIFT)
#define MEMCTRL_BUSY_RESET_BUSY_SRC_SHIFT (24)   /* Bits 24-25 */
#define MEMCTRL_BUSY_RESET_BUSY_SRC_MASK (0x3 << MEMCTRL_BUSY_RESET_BUSY_SRC_SHIFT)
#  define MEMCTRL_BUSY_RESET_BUSY_SRC(n) ((uint32_t)(n) << MEMCTRL_BUSY_RESET_BUSY_SRC_SHIFT)
#define MEMCTRL_BUSY_RESET_BUSY_SRC2_SHIFT (26)  /* Bits 26-27 */
#define MEMCTRL_BUSY_RESET_BUSY_SRC2_MASK (0x3 << MEMCTRL_BUSY_RESET_BUSY_SRC2_SHIFT)
#  define MEMCTRL_BUSY_RESET_BUSY_SRC2(n) ((uint32_t)(n) << MEMCTRL_BUSY_RESET_BUSY_SRC2_SHIFT)
#define MEMCTRL_BUSY_RESET_BUSY_GPADC_SHIFT (28) /* Bits 28-29 */
#define MEMCTRL_BUSY_RESET_BUSY_GPADC_MASK (0x3 << MEMCTRL_BUSY_RESET_BUSY_GPADC_SHIFT)
#  define MEMCTRL_BUSY_RESET_BUSY_GPADC(n) ((uint32_t)(n) << MEMCTRL_BUSY_RESET_BUSY_GPADC_SHIFT)
#define MEMCTRL_BUSY_RESET_BUSY_SDADC_SHIFT (30) /* Bits 30-31 */
#define MEMCTRL_BUSY_RESET_BUSY_SDADC_MASK (0x3 << MEMCTRL_BUSY_RESET_BUSY_SDADC_SHIFT)
#  define MEMCTRL_BUSY_RESET_BUSY_SDADC(n) ((uint32_t)(n) << MEMCTRL_BUSY_RESET_BUSY_SDADC_SHIFT)

/* BUSY_RESET_REG2 register */

#define MEMCTRL_BUSY_RESET_REG2_BUSY_TIMER_SHIFT (0)   /* Bits 0-1 */
#define MEMCTRL_BUSY_RESET_REG2_BUSY_TIMER_MASK (0x3 << MEMCTRL_BUSY_RESET_REG2_BUSY_TIMER_SHIFT)
#  define MEMCTRL_BUSY_RESET_REG2_BUSY_TIMER(n) ((uint32_t)(n) << MEMCTRL_BUSY_RESET_REG2_BUSY_TIMER_SHIFT)
#define MEMCTRL_BUSY_RESET_REG2_BUSY_TIMER2_SHIFT (2)  /* Bits 2-3 */
#define MEMCTRL_BUSY_RESET_REG2_BUSY_TIMER2_MASK (0x3 << MEMCTRL_BUSY_RESET_REG2_BUSY_TIMER2_SHIFT)
#  define MEMCTRL_BUSY_RESET_REG2_BUSY_TIMER2(n) ((uint32_t)(n) << MEMCTRL_BUSY_RESET_REG2_BUSY_TIMER2_SHIFT)
#define MEMCTRL_BUSY_RESET_REG2_BUSY_TIMER3_SHIFT (4)  /* Bits 4-5 */
#define MEMCTRL_BUSY_RESET_REG2_BUSY_TIMER3_MASK (0x3 << MEMCTRL_BUSY_RESET_REG2_BUSY_TIMER3_SHIFT)
#  define MEMCTRL_BUSY_RESET_REG2_BUSY_TIMER3(n) ((uint32_t)(n) << MEMCTRL_BUSY_RESET_REG2_BUSY_TIMER3_SHIFT)
#define MEMCTRL_BUSY_RESET_REG2_BUSY_TIMER4_SHIFT (6)  /* Bits 6-7 */
#define MEMCTRL_BUSY_RESET_REG2_BUSY_TIMER4_MASK (0x3 << MEMCTRL_BUSY_RESET_REG2_BUSY_TIMER4_SHIFT)
#  define MEMCTRL_BUSY_RESET_REG2_BUSY_TIMER4(n) ((uint32_t)(n) << MEMCTRL_BUSY_RESET_REG2_BUSY_TIMER4_SHIFT)
#define MEMCTRL_BUSY_RESET_REG2_BUSY_TIMER5_SHIFT (8)  /* Bits 8-9 */
#define MEMCTRL_BUSY_RESET_REG2_BUSY_TIMER5_MASK (0x3 << MEMCTRL_BUSY_RESET_REG2_BUSY_TIMER5_SHIFT)
#  define MEMCTRL_BUSY_RESET_REG2_BUSY_TIMER5(n) ((uint32_t)(n) << MEMCTRL_BUSY_RESET_REG2_BUSY_TIMER5_SHIFT)
#define MEMCTRL_BUSY_RESET_REG2_BUSY_TIMER6_SHIFT (10) /* Bits 10-11 */
#define MEMCTRL_BUSY_RESET_REG2_BUSY_TIMER6_MASK (0x3 << MEMCTRL_BUSY_RESET_REG2_BUSY_TIMER6_SHIFT)
#  define MEMCTRL_BUSY_RESET_REG2_BUSY_TIMER6(n) ((uint32_t)(n) << MEMCTRL_BUSY_RESET_REG2_BUSY_TIMER6_SHIFT)

/* BUSY_STAT register */

#define MEMCTRL_BUSY_STAT_BUSY_UART_SHIFT (0)   /* Bits 0-1 */
#define MEMCTRL_BUSY_STAT_BUSY_UART_MASK (0x3 << MEMCTRL_BUSY_STAT_BUSY_UART_SHIFT)
#  define MEMCTRL_BUSY_STAT_BUSY_UART(n) ((uint32_t)(n) << MEMCTRL_BUSY_STAT_BUSY_UART_SHIFT)
#define MEMCTRL_BUSY_STAT_BUSY_UART2_SHIFT (2)  /* Bits 2-3 */
#define MEMCTRL_BUSY_STAT_BUSY_UART2_MASK (0x3 << MEMCTRL_BUSY_STAT_BUSY_UART2_SHIFT)
#  define MEMCTRL_BUSY_STAT_BUSY_UART2(n) ((uint32_t)(n) << MEMCTRL_BUSY_STAT_BUSY_UART2_SHIFT)
#define MEMCTRL_BUSY_STAT_BUSY_UART3_SHIFT (4)  /* Bits 4-5 */
#define MEMCTRL_BUSY_STAT_BUSY_UART3_MASK (0x3 << MEMCTRL_BUSY_STAT_BUSY_UART3_SHIFT)
#  define MEMCTRL_BUSY_STAT_BUSY_UART3(n) ((uint32_t)(n) << MEMCTRL_BUSY_STAT_BUSY_UART3_SHIFT)
#define MEMCTRL_BUSY_STAT_BUSY_SPI_SHIFT (6)    /* Bits 6-7 */
#define MEMCTRL_BUSY_STAT_BUSY_SPI_MASK (0x3 << MEMCTRL_BUSY_STAT_BUSY_SPI_SHIFT)
#  define MEMCTRL_BUSY_STAT_BUSY_SPI(n) ((uint32_t)(n) << MEMCTRL_BUSY_STAT_BUSY_SPI_SHIFT)
#define MEMCTRL_BUSY_STAT_BUSY_SPI2_SHIFT (8)   /* Bits 8-9 */
#define MEMCTRL_BUSY_STAT_BUSY_SPI2_MASK (0x3 << MEMCTRL_BUSY_STAT_BUSY_SPI2_SHIFT)
#  define MEMCTRL_BUSY_STAT_BUSY_SPI2(n) ((uint32_t)(n) << MEMCTRL_BUSY_STAT_BUSY_SPI2_SHIFT)
#define MEMCTRL_BUSY_STAT_BUSY_SPI3_SHIFT (10)  /* Bits 10-11 */
#define MEMCTRL_BUSY_STAT_BUSY_SPI3_MASK (0x3 << MEMCTRL_BUSY_STAT_BUSY_SPI3_SHIFT)
#  define MEMCTRL_BUSY_STAT_BUSY_SPI3(n) ((uint32_t)(n) << MEMCTRL_BUSY_STAT_BUSY_SPI3_SHIFT)
#define MEMCTRL_BUSY_STAT_BUSY_I2C_SHIFT (12)   /* Bits 12-13 */
#define MEMCTRL_BUSY_STAT_BUSY_I2C_MASK (0x3 << MEMCTRL_BUSY_STAT_BUSY_I2C_SHIFT)
#  define MEMCTRL_BUSY_STAT_BUSY_I2C(n) ((uint32_t)(n) << MEMCTRL_BUSY_STAT_BUSY_I2C_SHIFT)
#define MEMCTRL_BUSY_STAT_BUSY_I2C2_SHIFT (14)  /* Bits 14-15 */
#define MEMCTRL_BUSY_STAT_BUSY_I2C2_MASK (0x3 << MEMCTRL_BUSY_STAT_BUSY_I2C2_SHIFT)
#  define MEMCTRL_BUSY_STAT_BUSY_I2C2(n) ((uint32_t)(n) << MEMCTRL_BUSY_STAT_BUSY_I2C2_SHIFT)
#define MEMCTRL_BUSY_STAT_BUSY_I2C3_SHIFT (16)  /* Bits 16-17 */
#define MEMCTRL_BUSY_STAT_BUSY_I2C3_MASK (0x3 << MEMCTRL_BUSY_STAT_BUSY_I2C3_SHIFT)
#  define MEMCTRL_BUSY_STAT_BUSY_I2C3(n) ((uint32_t)(n) << MEMCTRL_BUSY_STAT_BUSY_I2C3_SHIFT)
#define MEMCTRL_BUSY_STAT_BUSY_I3C_SHIFT (18)   /* Bits 18-19 */
#define MEMCTRL_BUSY_STAT_BUSY_I3C_MASK (0x3 << MEMCTRL_BUSY_STAT_BUSY_I3C_SHIFT)
#  define MEMCTRL_BUSY_STAT_BUSY_I3C(n) ((uint32_t)(n) << MEMCTRL_BUSY_STAT_BUSY_I3C_SHIFT)
#define MEMCTRL_BUSY_STAT_BUSY_PCM_SHIFT (20)   /* Bits 20-21 */
#define MEMCTRL_BUSY_STAT_BUSY_PCM_MASK (0x3 << MEMCTRL_BUSY_STAT_BUSY_PCM_SHIFT)
#  define MEMCTRL_BUSY_STAT_BUSY_PCM(n) ((uint32_t)(n) << MEMCTRL_BUSY_STAT_BUSY_PCM_SHIFT)
#define MEMCTRL_BUSY_STAT_BUSY_PDM_SHIFT (22)   /* Bits 22-23 */
#define MEMCTRL_BUSY_STAT_BUSY_PDM_MASK (0x3 << MEMCTRL_BUSY_STAT_BUSY_PDM_SHIFT)
#  define MEMCTRL_BUSY_STAT_BUSY_PDM(n) ((uint32_t)(n) << MEMCTRL_BUSY_STAT_BUSY_PDM_SHIFT)
#define MEMCTRL_BUSY_STAT_BUSY_SRC_SHIFT (24)   /* Bits 24-25 */
#define MEMCTRL_BUSY_STAT_BUSY_SRC_MASK (0x3 << MEMCTRL_BUSY_STAT_BUSY_SRC_SHIFT)
#  define MEMCTRL_BUSY_STAT_BUSY_SRC(n) ((uint32_t)(n) << MEMCTRL_BUSY_STAT_BUSY_SRC_SHIFT)
#define MEMCTRL_BUSY_STAT_BUSY_SRC2_SHIFT (26)  /* Bits 26-27 */
#define MEMCTRL_BUSY_STAT_BUSY_SRC2_MASK (0x3 << MEMCTRL_BUSY_STAT_BUSY_SRC2_SHIFT)
#  define MEMCTRL_BUSY_STAT_BUSY_SRC2(n) ((uint32_t)(n) << MEMCTRL_BUSY_STAT_BUSY_SRC2_SHIFT)
#define MEMCTRL_BUSY_STAT_BUSY_GPADC_SHIFT (28) /* Bits 28-29 */
#define MEMCTRL_BUSY_STAT_BUSY_GPADC_MASK (0x3 << MEMCTRL_BUSY_STAT_BUSY_GPADC_SHIFT)
#  define MEMCTRL_BUSY_STAT_BUSY_GPADC(n) ((uint32_t)(n) << MEMCTRL_BUSY_STAT_BUSY_GPADC_SHIFT)
#define MEMCTRL_BUSY_STAT_BUSY_SDADC_SHIFT (30) /* Bits 30-31 */
#define MEMCTRL_BUSY_STAT_BUSY_SDADC_MASK (0x3 << MEMCTRL_BUSY_STAT_BUSY_SDADC_SHIFT)
#  define MEMCTRL_BUSY_STAT_BUSY_SDADC(n) ((uint32_t)(n) << MEMCTRL_BUSY_STAT_BUSY_SDADC_SHIFT)

/* BUSY_STAT_REG2 register */

#define MEMCTRL_BUSY_STAT_REG2_BUSY_TIMER_SHIFT (0)   /* Bits 0-1 */
#define MEMCTRL_BUSY_STAT_REG2_BUSY_TIMER_MASK (0x3 << MEMCTRL_BUSY_STAT_REG2_BUSY_TIMER_SHIFT)
#  define MEMCTRL_BUSY_STAT_REG2_BUSY_TIMER(n) ((uint32_t)(n) << MEMCTRL_BUSY_STAT_REG2_BUSY_TIMER_SHIFT)
#define MEMCTRL_BUSY_STAT_REG2_BUSY_TIMER2_SHIFT (2)  /* Bits 2-3 */
#define MEMCTRL_BUSY_STAT_REG2_BUSY_TIMER2_MASK (0x3 << MEMCTRL_BUSY_STAT_REG2_BUSY_TIMER2_SHIFT)
#  define MEMCTRL_BUSY_STAT_REG2_BUSY_TIMER2(n) ((uint32_t)(n) << MEMCTRL_BUSY_STAT_REG2_BUSY_TIMER2_SHIFT)
#define MEMCTRL_BUSY_STAT_REG2_BUSY_TIMER3_SHIFT (4)  /* Bits 4-5 */
#define MEMCTRL_BUSY_STAT_REG2_BUSY_TIMER3_MASK (0x3 << MEMCTRL_BUSY_STAT_REG2_BUSY_TIMER3_SHIFT)
#  define MEMCTRL_BUSY_STAT_REG2_BUSY_TIMER3(n) ((uint32_t)(n) << MEMCTRL_BUSY_STAT_REG2_BUSY_TIMER3_SHIFT)
#define MEMCTRL_BUSY_STAT_REG2_BUSY_TIMER4_SHIFT (6)  /* Bits 6-7 */
#define MEMCTRL_BUSY_STAT_REG2_BUSY_TIMER4_MASK (0x3 << MEMCTRL_BUSY_STAT_REG2_BUSY_TIMER4_SHIFT)
#  define MEMCTRL_BUSY_STAT_REG2_BUSY_TIMER4(n) ((uint32_t)(n) << MEMCTRL_BUSY_STAT_REG2_BUSY_TIMER4_SHIFT)
#define MEMCTRL_BUSY_STAT_REG2_BUSY_TIMER5_SHIFT (8)  /* Bits 8-9 */
#define MEMCTRL_BUSY_STAT_REG2_BUSY_TIMER5_MASK (0x3 << MEMCTRL_BUSY_STAT_REG2_BUSY_TIMER5_SHIFT)
#  define MEMCTRL_BUSY_STAT_REG2_BUSY_TIMER5(n) ((uint32_t)(n) << MEMCTRL_BUSY_STAT_REG2_BUSY_TIMER5_SHIFT)
#define MEMCTRL_BUSY_STAT_REG2_BUSY_TIMER6_SHIFT (10) /* Bits 10-11 */
#define MEMCTRL_BUSY_STAT_REG2_BUSY_TIMER6_MASK (0x3 << MEMCTRL_BUSY_STAT_REG2_BUSY_TIMER6_SHIFT)
#  define MEMCTRL_BUSY_STAT_REG2_BUSY_TIMER6(n) ((uint32_t)(n) << MEMCTRL_BUSY_STAT_REG2_BUSY_TIMER6_SHIFT)

#endif /* __ARCH_ARM_SRC_DA1470X_HARDWARE_DA1470X_MEMCTRL_H */
