/****************************************************************************
 * arch/arm/src/da1470x/hardware/da1470x_qspic.h
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.  The
 * ASF licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 ****************************************************************************/

/* Generated from the Renesas CMSIS device header DA1470x-00.h (SDK
 * 10.2.6.49).  Do not edit by hand; regenerate with tools/genhdr.py.
 */

#ifndef __ARCH_ARM_SRC_DA1470X_HARDWARE_DA1470X_QSPIC_H
#define __ARCH_ARM_SRC_DA1470X_HARDWARE_DA1470X_QSPIC_H

/****************************************************************************
 * Included Files
 ****************************************************************************/

#include <nuttx/config.h>
#include "da1470x_memorymap.h"

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

/* Register Offsets *********************************************************/

#define DA1470X_QSPIC_CTRLBUS_OFFSET 0x0000   /* SPI Bus control register for the Manual */
#define DA1470X_QSPIC_CTRLMODE_OFFSET 0x0004  /* Mode control register */
#define DA1470X_QSPIC_RECVDATA_OFFSET 0x0008  /* Received data for the Manual mode */
#define DA1470X_QSPIC_BURSTCMDA_OFFSET 0x000c /* The way of reading in Auto mode (command */
#define DA1470X_QSPIC_BURSTCMDB_OFFSET 0x0010 /* The way of reading in Auto mode (command */
#define DA1470X_QSPIC_STATUS_OFFSET 0x0014    /* The status register of the QSPI controll */
#define DA1470X_QSPIC_WRITEDATA_OFFSET 0x0018 /* Write data to SPI Bus for the Manual mod */
#define DA1470X_QSPIC_READDATA_OFFSET 0x001c  /* Read data from SPI Bus for the Manual mo */
#define DA1470X_QSPIC_DUMMYDATA_OFFSET 0x0020 /* Send dummy clocks to SPI Bus for the Man */
#define DA1470X_QSPIC_ERASECTRL_OFFSET 0x0024 /* Erase control register */
#define DA1470X_QSPIC_ERASECMDA_OFFSET 0x0028 /* The way of erasing in Auto mode (command */
#define DA1470X_QSPIC_ERASECMDB_OFFSET 0x002c /* The way of erasing in Auto mode (command */
#define DA1470X_QSPIC_BURSTBRK_OFFSET 0x0030  /* Read break sequence in Auto mode */
#define DA1470X_QSPIC_STATUSCMD_OFFSET 0x0034 /* The way of reading the status of externa */
#define DA1470X_QSPIC_CHCKERASE_OFFSET 0x0038 /* Check erase progress in Auto mode */
#define DA1470X_QSPIC_GP_OFFSET 0x003c        /* General purpose QSPIC register */
#define DA1470X_QSPIC_AWRITECMD_OFFSET 0x0040 /* The way of writing in Auto mode when the */
#define DA1470X_QSPIC_MEMBLEN_OFFSET 0x0044   /* External memory burst length configurati */

/* Register Addresses *******************************************************/

#define DA1470X_QSPIC_CTRLBUS (DA1470X_QSPIC_BASE + DA1470X_QSPIC_CTRLBUS_OFFSET)
#define DA1470X_QSPIC_CTRLMODE (DA1470X_QSPIC_BASE + DA1470X_QSPIC_CTRLMODE_OFFSET)
#define DA1470X_QSPIC_RECVDATA (DA1470X_QSPIC_BASE + DA1470X_QSPIC_RECVDATA_OFFSET)
#define DA1470X_QSPIC_BURSTCMDA (DA1470X_QSPIC_BASE + DA1470X_QSPIC_BURSTCMDA_OFFSET)
#define DA1470X_QSPIC_BURSTCMDB (DA1470X_QSPIC_BASE + DA1470X_QSPIC_BURSTCMDB_OFFSET)
#define DA1470X_QSPIC_STATUS (DA1470X_QSPIC_BASE + DA1470X_QSPIC_STATUS_OFFSET)
#define DA1470X_QSPIC_WRITEDATA (DA1470X_QSPIC_BASE + DA1470X_QSPIC_WRITEDATA_OFFSET)
#define DA1470X_QSPIC_READDATA (DA1470X_QSPIC_BASE + DA1470X_QSPIC_READDATA_OFFSET)
#define DA1470X_QSPIC_DUMMYDATA (DA1470X_QSPIC_BASE + DA1470X_QSPIC_DUMMYDATA_OFFSET)
#define DA1470X_QSPIC_ERASECTRL (DA1470X_QSPIC_BASE + DA1470X_QSPIC_ERASECTRL_OFFSET)
#define DA1470X_QSPIC_ERASECMDA (DA1470X_QSPIC_BASE + DA1470X_QSPIC_ERASECMDA_OFFSET)
#define DA1470X_QSPIC_ERASECMDB (DA1470X_QSPIC_BASE + DA1470X_QSPIC_ERASECMDB_OFFSET)
#define DA1470X_QSPIC_BURSTBRK (DA1470X_QSPIC_BASE + DA1470X_QSPIC_BURSTBRK_OFFSET)
#define DA1470X_QSPIC_STATUSCMD (DA1470X_QSPIC_BASE + DA1470X_QSPIC_STATUSCMD_OFFSET)
#define DA1470X_QSPIC_CHCKERASE (DA1470X_QSPIC_BASE + DA1470X_QSPIC_CHCKERASE_OFFSET)
#define DA1470X_QSPIC_GP (DA1470X_QSPIC_BASE + DA1470X_QSPIC_GP_OFFSET)
#define DA1470X_QSPIC_AWRITECMD (DA1470X_QSPIC_BASE + DA1470X_QSPIC_AWRITECMD_OFFSET)
#define DA1470X_QSPIC_MEMBLEN (DA1470X_QSPIC_BASE + DA1470X_QSPIC_MEMBLEN_OFFSET)

#define DA1470X_QSPIC2_CTRLBUS (DA1470X_QSPIC2_BASE + DA1470X_QSPIC_CTRLBUS_OFFSET)
#define DA1470X_QSPIC2_CTRLMODE (DA1470X_QSPIC2_BASE + DA1470X_QSPIC_CTRLMODE_OFFSET)
#define DA1470X_QSPIC2_RECVDATA (DA1470X_QSPIC2_BASE + DA1470X_QSPIC_RECVDATA_OFFSET)
#define DA1470X_QSPIC2_BURSTCMDA (DA1470X_QSPIC2_BASE + DA1470X_QSPIC_BURSTCMDA_OFFSET)
#define DA1470X_QSPIC2_BURSTCMDB (DA1470X_QSPIC2_BASE + DA1470X_QSPIC_BURSTCMDB_OFFSET)
#define DA1470X_QSPIC2_STATUS (DA1470X_QSPIC2_BASE + DA1470X_QSPIC_STATUS_OFFSET)
#define DA1470X_QSPIC2_WRITEDATA (DA1470X_QSPIC2_BASE + DA1470X_QSPIC_WRITEDATA_OFFSET)
#define DA1470X_QSPIC2_READDATA (DA1470X_QSPIC2_BASE + DA1470X_QSPIC_READDATA_OFFSET)
#define DA1470X_QSPIC2_DUMMYDATA (DA1470X_QSPIC2_BASE + DA1470X_QSPIC_DUMMYDATA_OFFSET)
#define DA1470X_QSPIC2_ERASECTRL (DA1470X_QSPIC2_BASE + DA1470X_QSPIC_ERASECTRL_OFFSET)
#define DA1470X_QSPIC2_ERASECMDA (DA1470X_QSPIC2_BASE + DA1470X_QSPIC_ERASECMDA_OFFSET)
#define DA1470X_QSPIC2_ERASECMDB (DA1470X_QSPIC2_BASE + DA1470X_QSPIC_ERASECMDB_OFFSET)
#define DA1470X_QSPIC2_BURSTBRK (DA1470X_QSPIC2_BASE + DA1470X_QSPIC_BURSTBRK_OFFSET)
#define DA1470X_QSPIC2_STATUSCMD (DA1470X_QSPIC2_BASE + DA1470X_QSPIC_STATUSCMD_OFFSET)
#define DA1470X_QSPIC2_CHCKERASE (DA1470X_QSPIC2_BASE + DA1470X_QSPIC_CHCKERASE_OFFSET)
#define DA1470X_QSPIC2_GP (DA1470X_QSPIC2_BASE + DA1470X_QSPIC_GP_OFFSET)
#define DA1470X_QSPIC2_AWRITECMD (DA1470X_QSPIC2_BASE + DA1470X_QSPIC_AWRITECMD_OFFSET)
#define DA1470X_QSPIC2_MEMBLEN (DA1470X_QSPIC2_BASE + DA1470X_QSPIC_MEMBLEN_OFFSET)

/* Register Bit-field Definitions *******************************************/

/* CTRLBUS register */

#define QSPIC_CTRLBUS_SET_SINGLE (1 << 0) /* Bit 0 */
#define QSPIC_CTRLBUS_SET_DUAL (1 << 1)   /* Bit 1 */
#define QSPIC_CTRLBUS_SET_QUAD (1 << 2)   /* Bit 2 */
#define QSPIC_CTRLBUS_EN_CS (1 << 3)      /* Bit 3 */
#define QSPIC_CTRLBUS_DIS_CS (1 << 4)     /* Bit 4 */

/* CTRLMODE register */

#define QSPIC_CTRLMODE_AUTO_MD (1 << 0)       /* Bit 0 */
#define QSPIC_CTRLMODE_CLK_MD (1 << 1)        /* Bit 1 */
#define QSPIC_CTRLMODE_IO2_OEN (1 << 2)       /* Bit 2 */
#define QSPIC_CTRLMODE_IO3_OEN (1 << 3)       /* Bit 3 */
#define QSPIC_CTRLMODE_IO2_DAT (1 << 4)       /* Bit 4 */
#define QSPIC_CTRLMODE_IO3_DAT (1 << 5)       /* Bit 5 */
#define QSPIC_CTRLMODE_HRDY_MD (1 << 6)       /* Bit 6 */
#define QSPIC_CTRLMODE_RXD_NEG (1 << 7)       /* Bit 7 */
#define QSPIC_CTRLMODE_RPIPE_EN (1 << 8)      /* Bit 8 */
#define QSPIC_CTRLMODE_PCLK_MD_SHIFT (9)      /* Bits 9-11 */
#define QSPIC_CTRLMODE_PCLK_MD_MASK (0x7 << QSPIC_CTRLMODE_PCLK_MD_SHIFT)
#  define QSPIC_CTRLMODE_PCLK_MD(n) ((uint32_t)(n) << QSPIC_CTRLMODE_PCLK_MD_SHIFT)
#define QSPIC_CTRLMODE_FORCENSEQ_EN (1 << 12) /* Bit 12 */
#define QSPIC_CTRLMODE_USE_32BA (1 << 13)     /* Bit 13 */
#define QSPIC_CTRLMODE_SRAM_EN (1 << 14)      /* Bit 14 */
#define QSPIC_CTRLMODE_CS_MD (1 << 15)        /* Bit 15 */
#define QSPIC_CTRLMODE_CLK_FREE_EN (1 << 16)  /* Bit 16 */

/* RECVDATA register */

#define QSPIC_RECVDATA_RECVDATA_SHIFT (0) /* Bits 0-31 */
#define QSPIC_RECVDATA_RECVDATA_MASK (0xffffffff << QSPIC_RECVDATA_RECVDATA_SHIFT)
#  define QSPIC_RECVDATA_RECVDATA(n) ((uint32_t)(n) << QSPIC_RECVDATA_RECVDATA_SHIFT)

/* BURSTCMDA register */

#define QSPIC_BURSTCMDA_INST_SHIFT (0)        /* Bits 0-7 */
#define QSPIC_BURSTCMDA_INST_MASK (0xff << QSPIC_BURSTCMDA_INST_SHIFT)
#  define QSPIC_BURSTCMDA_INST(n) ((uint32_t)(n) << QSPIC_BURSTCMDA_INST_SHIFT)
#define QSPIC_BURSTCMDA_INST_WB_SHIFT (8)     /* Bits 8-15 */
#define QSPIC_BURSTCMDA_INST_WB_MASK (0xff << QSPIC_BURSTCMDA_INST_WB_SHIFT)
#  define QSPIC_BURSTCMDA_INST_WB(n) ((uint32_t)(n) << QSPIC_BURSTCMDA_INST_WB_SHIFT)
#define QSPIC_BURSTCMDA_EXT_BYTE_SHIFT (16)   /* Bits 16-23 */
#define QSPIC_BURSTCMDA_EXT_BYTE_MASK (0xff << QSPIC_BURSTCMDA_EXT_BYTE_SHIFT)
#  define QSPIC_BURSTCMDA_EXT_BYTE(n) ((uint32_t)(n) << QSPIC_BURSTCMDA_EXT_BYTE_SHIFT)
#define QSPIC_BURSTCMDA_INST_TX_MD_SHIFT (24) /* Bits 24-25 */
#define QSPIC_BURSTCMDA_INST_TX_MD_MASK (0x3 << QSPIC_BURSTCMDA_INST_TX_MD_SHIFT)
#  define QSPIC_BURSTCMDA_INST_TX_MD(n) ((uint32_t)(n) << QSPIC_BURSTCMDA_INST_TX_MD_SHIFT)
#define QSPIC_BURSTCMDA_ADR_TX_MD_SHIFT (26)  /* Bits 26-27 */
#define QSPIC_BURSTCMDA_ADR_TX_MD_MASK (0x3 << QSPIC_BURSTCMDA_ADR_TX_MD_SHIFT)
#  define QSPIC_BURSTCMDA_ADR_TX_MD(n) ((uint32_t)(n) << QSPIC_BURSTCMDA_ADR_TX_MD_SHIFT)
#define QSPIC_BURSTCMDA_EXT_TX_MD_SHIFT (28)  /* Bits 28-29 */
#define QSPIC_BURSTCMDA_EXT_TX_MD_MASK (0x3 << QSPIC_BURSTCMDA_EXT_TX_MD_SHIFT)
#  define QSPIC_BURSTCMDA_EXT_TX_MD(n) ((uint32_t)(n) << QSPIC_BURSTCMDA_EXT_TX_MD_SHIFT)
#define QSPIC_BURSTCMDA_DMY_TX_MD_SHIFT (30)  /* Bits 30-31 */
#define QSPIC_BURSTCMDA_DMY_TX_MD_MASK (0x3 << QSPIC_BURSTCMDA_DMY_TX_MD_SHIFT)
#  define QSPIC_BURSTCMDA_DMY_TX_MD(n) ((uint32_t)(n) << QSPIC_BURSTCMDA_DMY_TX_MD_SHIFT)

/* BURSTCMDB register */

#define QSPIC_BURSTCMDB_DAT_RX_MD_SHIFT (0)    /* Bits 0-1 */
#define QSPIC_BURSTCMDB_DAT_RX_MD_MASK (0x3 << QSPIC_BURSTCMDB_DAT_RX_MD_SHIFT)
#  define QSPIC_BURSTCMDB_DAT_RX_MD(n) ((uint32_t)(n) << QSPIC_BURSTCMDB_DAT_RX_MD_SHIFT)
#define QSPIC_BURSTCMDB_EXT_BYTE_EN (1 << 2)   /* Bit 2 */
#define QSPIC_BURSTCMDB_EXT_HF_DS (1 << 3)     /* Bit 3 */
#define QSPIC_BURSTCMDB_DMY_NUM_SHIFT (4)      /* Bits 4-5 */
#define QSPIC_BURSTCMDB_DMY_NUM_MASK (0x3 << QSPIC_BURSTCMDB_DMY_NUM_SHIFT)
#  define QSPIC_BURSTCMDB_DMY_NUM(n) ((uint32_t)(n) << QSPIC_BURSTCMDB_DMY_NUM_SHIFT)
#define QSPIC_BURSTCMDB_INST_MD (1 << 6)       /* Bit 6 */
#define QSPIC_BURSTCMDB_WRAP_MD (1 << 7)       /* Bit 7 */
#define QSPIC_BURSTCMDB_WRAP_LEN_SHIFT (8)     /* Bits 8-9 */
#define QSPIC_BURSTCMDB_WRAP_LEN_MASK (0x3 << QSPIC_BURSTCMDB_WRAP_LEN_SHIFT)
#  define QSPIC_BURSTCMDB_WRAP_LEN(n) ((uint32_t)(n) << QSPIC_BURSTCMDB_WRAP_LEN_SHIFT)
#define QSPIC_BURSTCMDB_WRAP_SIZE_SHIFT (10)   /* Bits 10-11 */
#define QSPIC_BURSTCMDB_WRAP_SIZE_MASK (0x3 << QSPIC_BURSTCMDB_WRAP_SIZE_SHIFT)
#  define QSPIC_BURSTCMDB_WRAP_SIZE(n) ((uint32_t)(n) << QSPIC_BURSTCMDB_WRAP_SIZE_SHIFT)
#define QSPIC_BURSTCMDB_CS_HIGH_MIN_SHIFT (12) /* Bits 12-14 */
#define QSPIC_BURSTCMDB_CS_HIGH_MIN_MASK (0x7 << QSPIC_BURSTCMDB_CS_HIGH_MIN_SHIFT)
#  define QSPIC_BURSTCMDB_CS_HIGH_MIN(n) ((uint32_t)(n) << QSPIC_BURSTCMDB_CS_HIGH_MIN_SHIFT)
#define QSPIC_BURSTCMDB_DMY_FORCE (1 << 15)    /* Bit 15 */

/* STATUS register */

#define QSPIC_STATUS_BUSY (1 << 0) /* Bit 0 */

/* WRITEDATA register */

#define QSPIC_WRITEDATA_WRITEDATA_SHIFT (0) /* Bits 0-31 */
#define QSPIC_WRITEDATA_WRITEDATA_MASK (0xffffffff << QSPIC_WRITEDATA_WRITEDATA_SHIFT)
#  define QSPIC_WRITEDATA_WRITEDATA(n) ((uint32_t)(n) << QSPIC_WRITEDATA_WRITEDATA_SHIFT)

/* READDATA register */

#define QSPIC_READDATA_READDATA_SHIFT (0) /* Bits 0-31 */
#define QSPIC_READDATA_READDATA_MASK (0xffffffff << QSPIC_READDATA_READDATA_SHIFT)
#  define QSPIC_READDATA_READDATA(n) ((uint32_t)(n) << QSPIC_READDATA_READDATA_SHIFT)

/* DUMMYDATA register */

#define QSPIC_DUMMYDATA_DUMMYDATA_SHIFT (0) /* Bits 0-31 */
#define QSPIC_DUMMYDATA_DUMMYDATA_MASK (0xffffffff << QSPIC_DUMMYDATA_DUMMYDATA_SHIFT)
#  define QSPIC_DUMMYDATA_DUMMYDATA(n) ((uint32_t)(n) << QSPIC_DUMMYDATA_DUMMYDATA_SHIFT)

/* ERASECTRL register */

#define QSPIC_ERASECTRL_ERS_ADDR_SHIFT (4)   /* Bits 4-23 */
#define QSPIC_ERASECTRL_ERS_ADDR_MASK (0xfffff << QSPIC_ERASECTRL_ERS_ADDR_SHIFT)
#  define QSPIC_ERASECTRL_ERS_ADDR(n) ((uint32_t)(n) << QSPIC_ERASECTRL_ERS_ADDR_SHIFT)
#define QSPIC_ERASECTRL_ERASE_EN (1 << 24)   /* Bit 24 */
#define QSPIC_ERASECTRL_ERS_STATE_SHIFT (25) /* Bits 25-27 */
#define QSPIC_ERASECTRL_ERS_STATE_MASK (0x7 << QSPIC_ERASECTRL_ERS_STATE_SHIFT)
#  define QSPIC_ERASECTRL_ERS_STATE(n) ((uint32_t)(n) << QSPIC_ERASECTRL_ERS_STATE_SHIFT)

/* ERASECMDA register */

#define QSPIC_ERASECMDA_ERS_INST_SHIFT (0)  /* Bits 0-7 */
#define QSPIC_ERASECMDA_ERS_INST_MASK (0xff << QSPIC_ERASECMDA_ERS_INST_SHIFT)
#  define QSPIC_ERASECMDA_ERS_INST(n) ((uint32_t)(n) << QSPIC_ERASECMDA_ERS_INST_SHIFT)
#define QSPIC_ERASECMDA_WEN_INST_SHIFT (8)  /* Bits 8-15 */
#define QSPIC_ERASECMDA_WEN_INST_MASK (0xff << QSPIC_ERASECMDA_WEN_INST_SHIFT)
#  define QSPIC_ERASECMDA_WEN_INST(n) ((uint32_t)(n) << QSPIC_ERASECMDA_WEN_INST_SHIFT)
#define QSPIC_ERASECMDA_SUS_INST_SHIFT (16) /* Bits 16-23 */
#define QSPIC_ERASECMDA_SUS_INST_MASK (0xff << QSPIC_ERASECMDA_SUS_INST_SHIFT)
#  define QSPIC_ERASECMDA_SUS_INST(n) ((uint32_t)(n) << QSPIC_ERASECMDA_SUS_INST_SHIFT)
#define QSPIC_ERASECMDA_RES_INST_SHIFT (24) /* Bits 24-31 */
#define QSPIC_ERASECMDA_RES_INST_MASK (0xff << QSPIC_ERASECMDA_RES_INST_SHIFT)
#  define QSPIC_ERASECMDA_RES_INST(n) ((uint32_t)(n) << QSPIC_ERASECMDA_RES_INST_SHIFT)

/* ERASECMDB register */

#define QSPIC_ERASECMDB_ERS_TX_MD_SHIFT (0)   /* Bits 0-1 */
#define QSPIC_ERASECMDB_ERS_TX_MD_MASK (0x3 << QSPIC_ERASECMDB_ERS_TX_MD_SHIFT)
#  define QSPIC_ERASECMDB_ERS_TX_MD(n) ((uint32_t)(n) << QSPIC_ERASECMDB_ERS_TX_MD_SHIFT)
#define QSPIC_ERASECMDB_WEN_TX_MD_SHIFT (2)   /* Bits 2-3 */
#define QSPIC_ERASECMDB_WEN_TX_MD_MASK (0x3 << QSPIC_ERASECMDB_WEN_TX_MD_SHIFT)
#  define QSPIC_ERASECMDB_WEN_TX_MD(n) ((uint32_t)(n) << QSPIC_ERASECMDB_WEN_TX_MD_SHIFT)
#define QSPIC_ERASECMDB_SUS_TX_MD_SHIFT (4)   /* Bits 4-5 */
#define QSPIC_ERASECMDB_SUS_TX_MD_MASK (0x3 << QSPIC_ERASECMDB_SUS_TX_MD_SHIFT)
#  define QSPIC_ERASECMDB_SUS_TX_MD(n) ((uint32_t)(n) << QSPIC_ERASECMDB_SUS_TX_MD_SHIFT)
#define QSPIC_ERASECMDB_RES_TX_MD_SHIFT (6)   /* Bits 6-7 */
#define QSPIC_ERASECMDB_RES_TX_MD_MASK (0x3 << QSPIC_ERASECMDB_RES_TX_MD_SHIFT)
#  define QSPIC_ERASECMDB_RES_TX_MD(n) ((uint32_t)(n) << QSPIC_ERASECMDB_RES_TX_MD_SHIFT)
#define QSPIC_ERASECMDB_EAD_TX_MD_SHIFT (8)   /* Bits 8-9 */
#define QSPIC_ERASECMDB_EAD_TX_MD_MASK (0x3 << QSPIC_ERASECMDB_EAD_TX_MD_SHIFT)
#  define QSPIC_ERASECMDB_EAD_TX_MD(n) ((uint32_t)(n) << QSPIC_ERASECMDB_EAD_TX_MD_SHIFT)
#define QSPIC_ERASECMDB_ERS_CS_HI_SHIFT (10)  /* Bits 10-14 */
#define QSPIC_ERASECMDB_ERS_CS_HI_MASK (0x1f << QSPIC_ERASECMDB_ERS_CS_HI_SHIFT)
#  define QSPIC_ERASECMDB_ERS_CS_HI(n) ((uint32_t)(n) << QSPIC_ERASECMDB_ERS_CS_HI_SHIFT)
#define QSPIC_ERASECMDB_ERSRES_HLD_SHIFT (16) /* Bits 16-19 */
#define QSPIC_ERASECMDB_ERSRES_HLD_MASK (0xf << QSPIC_ERASECMDB_ERSRES_HLD_SHIFT)
#  define QSPIC_ERASECMDB_ERSRES_HLD(n) ((uint32_t)(n) << QSPIC_ERASECMDB_ERSRES_HLD_SHIFT)
#define QSPIC_ERASECMDB_RESSUS_DLY_SHIFT (24) /* Bits 24-29 */
#define QSPIC_ERASECMDB_RESSUS_DLY_MASK (0x3f << QSPIC_ERASECMDB_RESSUS_DLY_SHIFT)
#  define QSPIC_ERASECMDB_RESSUS_DLY(n) ((uint32_t)(n) << QSPIC_ERASECMDB_RESSUS_DLY_SHIFT)

/* BURSTBRK register */

#define QSPIC_BURSTBRK_BRK_WRD_SHIFT (0)    /* Bits 0-15 */
#define QSPIC_BURSTBRK_BRK_WRD_MASK (0xffff << QSPIC_BURSTBRK_BRK_WRD_SHIFT)
#  define QSPIC_BURSTBRK_BRK_WRD(n) ((uint32_t)(n) << QSPIC_BURSTBRK_BRK_WRD_SHIFT)
#define QSPIC_BURSTBRK_BRK_EN (1 << 16)     /* Bit 16 */
#define QSPIC_BURSTBRK_BRK_SZ (1 << 17)     /* Bit 17 */
#define QSPIC_BURSTBRK_BRK_TX_MD_SHIFT (18) /* Bits 18-19 */
#define QSPIC_BURSTBRK_BRK_TX_MD_MASK (0x3 << QSPIC_BURSTBRK_BRK_TX_MD_SHIFT)
#  define QSPIC_BURSTBRK_BRK_TX_MD(n) ((uint32_t)(n) << QSPIC_BURSTBRK_BRK_TX_MD_SHIFT)
#define QSPIC_BURSTBRK_SEC_HF_DS (1 << 20)  /* Bit 20 */

/* STATUSCMD register */

#define QSPIC_STATUSCMD_RSTAT_INST_SHIFT (0)   /* Bits 0-7 */
#define QSPIC_STATUSCMD_RSTAT_INST_MASK (0xff << QSPIC_STATUSCMD_RSTAT_INST_SHIFT)
#  define QSPIC_STATUSCMD_RSTAT_INST(n) ((uint32_t)(n) << QSPIC_STATUSCMD_RSTAT_INST_SHIFT)
#define QSPIC_STATUSCMD_RSTAT_TX_MD_SHIFT (8)  /* Bits 8-9 */
#define QSPIC_STATUSCMD_RSTAT_TX_MD_MASK (0x3 << QSPIC_STATUSCMD_RSTAT_TX_MD_SHIFT)
#  define QSPIC_STATUSCMD_RSTAT_TX_MD(n) ((uint32_t)(n) << QSPIC_STATUSCMD_RSTAT_TX_MD_SHIFT)
#define QSPIC_STATUSCMD_RSTAT_RX_MD_SHIFT (10) /* Bits 10-11 */
#define QSPIC_STATUSCMD_RSTAT_RX_MD_MASK (0x3 << QSPIC_STATUSCMD_RSTAT_RX_MD_SHIFT)
#  define QSPIC_STATUSCMD_RSTAT_RX_MD(n) ((uint32_t)(n) << QSPIC_STATUSCMD_RSTAT_RX_MD_SHIFT)
#define QSPIC_STATUSCMD_BUSY_POS_SHIFT (12)    /* Bits 12-14 */
#define QSPIC_STATUSCMD_BUSY_POS_MASK (0x7 << QSPIC_STATUSCMD_BUSY_POS_SHIFT)
#  define QSPIC_STATUSCMD_BUSY_POS(n) ((uint32_t)(n) << QSPIC_STATUSCMD_BUSY_POS_SHIFT)
#define QSPIC_STATUSCMD_BUSY_VAL (1 << 15)     /* Bit 15 */
#define QSPIC_STATUSCMD_RESSTS_DLY_SHIFT (16)  /* Bits 16-21 */
#define QSPIC_STATUSCMD_RESSTS_DLY_MASK (0x3f << QSPIC_STATUSCMD_RESSTS_DLY_SHIFT)
#  define QSPIC_STATUSCMD_RESSTS_DLY(n) ((uint32_t)(n) << QSPIC_STATUSCMD_RESSTS_DLY_SHIFT)
#define QSPIC_STATUSCMD_STSDLY_SEL (1 << 22)   /* Bit 22 */

/* CHCKERASE register */

#define QSPIC_CHCKERASE_CHCKERASE_SHIFT (0) /* Bits 0-31 */
#define QSPIC_CHCKERASE_CHCKERASE_MASK (0xffffffff << QSPIC_CHCKERASE_CHCKERASE_SHIFT)
#  define QSPIC_CHCKERASE_CHCKERASE(n) ((uint32_t)(n) << QSPIC_CHCKERASE_CHCKERASE_SHIFT)

/* GP register */

#define QSPIC_GP_PADS_DRV_SHIFT (1)  /* Bits 1-2 */
#define QSPIC_GP_PADS_DRV_MASK (0x3 << QSPIC_GP_PADS_DRV_SHIFT)
#  define QSPIC_GP_PADS_DRV(n) ((uint32_t)(n) << QSPIC_GP_PADS_DRV_SHIFT)
#define QSPIC_GP_PADS_SLEW_SHIFT (3) /* Bits 3-4 */
#define QSPIC_GP_PADS_SLEW_MASK (0x3 << QSPIC_GP_PADS_SLEW_SHIFT)
#  define QSPIC_GP_PADS_SLEW(n) ((uint32_t)(n) << QSPIC_GP_PADS_SLEW_SHIFT)

/* AWRITECMD register */

#define QSPIC_AWRITECMD_WR_INST_SHIFT (0)         /* Bits 0-7 */
#define QSPIC_AWRITECMD_WR_INST_MASK (0xff << QSPIC_AWRITECMD_WR_INST_SHIFT)
#  define QSPIC_AWRITECMD_WR_INST(n) ((uint32_t)(n) << QSPIC_AWRITECMD_WR_INST_SHIFT)
#define QSPIC_AWRITECMD_WR_INST_TX_MD_SHIFT (8)   /* Bits 8-9 */
#define QSPIC_AWRITECMD_WR_INST_TX_MD_MASK (0x3 << QSPIC_AWRITECMD_WR_INST_TX_MD_SHIFT)
#  define QSPIC_AWRITECMD_WR_INST_TX_MD(n) ((uint32_t)(n) << QSPIC_AWRITECMD_WR_INST_TX_MD_SHIFT)
#define QSPIC_AWRITECMD_WR_ADR_TX_MD_SHIFT (10)   /* Bits 10-11 */
#define QSPIC_AWRITECMD_WR_ADR_TX_MD_MASK (0x3 << QSPIC_AWRITECMD_WR_ADR_TX_MD_SHIFT)
#  define QSPIC_AWRITECMD_WR_ADR_TX_MD(n) ((uint32_t)(n) << QSPIC_AWRITECMD_WR_ADR_TX_MD_SHIFT)
#define QSPIC_AWRITECMD_WR_DAT_TX_MD_SHIFT (12)   /* Bits 12-13 */
#define QSPIC_AWRITECMD_WR_DAT_TX_MD_MASK (0x3 << QSPIC_AWRITECMD_WR_DAT_TX_MD_SHIFT)
#  define QSPIC_AWRITECMD_WR_DAT_TX_MD(n) ((uint32_t)(n) << QSPIC_AWRITECMD_WR_DAT_TX_MD_SHIFT)
#define QSPIC_AWRITECMD_WR_CS_HIGH_MIN_SHIFT (14) /* Bits 14-18 */
#define QSPIC_AWRITECMD_WR_CS_HIGH_MIN_MASK (0x1f << QSPIC_AWRITECMD_WR_CS_HIGH_MIN_SHIFT)
#  define QSPIC_AWRITECMD_WR_CS_HIGH_MIN(n) ((uint32_t)(n) << QSPIC_AWRITECMD_WR_CS_HIGH_MIN_SHIFT)

/* MEMBLEN register */

#define QSPIC_MEMBLEN_MEMBLEN_SHIFT (0)  /* Bits 0-2 */
#define QSPIC_MEMBLEN_MEMBLEN_MASK (0x7 << QSPIC_MEMBLEN_MEMBLEN_SHIFT)
#  define QSPIC_MEMBLEN_MEMBLEN(n) ((uint32_t)(n) << QSPIC_MEMBLEN_MEMBLEN_SHIFT)
#define QSPIC_MEMBLEN_T_CEM_EN (1 << 3)  /* Bit 3 */
#define QSPIC_MEMBLEN_T_CEM_CC_SHIFT (4) /* Bits 4-13 */
#define QSPIC_MEMBLEN_T_CEM_CC_MASK (0x3ff << QSPIC_MEMBLEN_T_CEM_CC_SHIFT)
#  define QSPIC_MEMBLEN_T_CEM_CC(n) ((uint32_t)(n) << QSPIC_MEMBLEN_T_CEM_CC_SHIFT)

#endif /* __ARCH_ARM_SRC_DA1470X_HARDWARE_DA1470X_QSPIC_H */
