/****************************************************************************
 * arch/arm/src/da1470x/hardware/da1470x_oqspif.h
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.  The
 * ASF licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 ****************************************************************************/

/* Generated from the Renesas CMSIS device header DA1470x-00.h (SDK
 * 10.2.6.49).  Do not edit by hand; regenerate with tools/genhdr.py.
 */

#ifndef __ARCH_ARM_SRC_DA1470X_HARDWARE_DA1470X_OQSPIF_H
#define __ARCH_ARM_SRC_DA1470X_HARDWARE_DA1470X_OQSPIF_H

/****************************************************************************
 * Included Files
 ****************************************************************************/

#include <nuttx/config.h>
#include "da1470x_memorymap.h"

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

/* Register Offsets *********************************************************/

#define DA1470X_OQSPIF_CTRLBUS_OFFSET 0x0000       /* SPI Bus control register for the Manual */
#define DA1470X_OQSPIF_CTRLMODE_OFFSET 0x0004      /* Mode Control register */
#define DA1470X_OQSPIF_RECVDATA_OFFSET 0x0008      /* Received data for the Manual mode */
#define DA1470X_OQSPIF_BURSTCMDA_OFFSET 0x000c     /* The way of reading in Auto mode (command */
#define DA1470X_OQSPIF_BURSTCMDB_OFFSET 0x0010     /* The way of reading in Auto mode (command */
#define DA1470X_OQSPIF_STATUS_OFFSET 0x0014        /* The status register of the OSPI controll */
#define DA1470X_OQSPIF_WRITEDATA_OFFSET 0x0018     /* Write data to SPI Bus for the Manual mod */
#define DA1470X_OQSPIF_READDATA_OFFSET 0x001c      /* Read data from SPI Bus for the Manual mo */
#define DA1470X_OQSPIF_DUMMYDATA_OFFSET 0x0020     /* Send dummy clocks to SPI Bus for the Man */
#define DA1470X_OQSPIF_ERASECTRL_OFFSET 0x0024     /* OSPI Erase control register */
#define DA1470X_OQSPIF_ERASECMDA_OFFSET 0x0028     /* The way of erasing in Auto mode (command */
#define DA1470X_OQSPIF_ERASECMDB_OFFSET 0x002c     /* The way of erasing in Auto mode (command */
#define DA1470X_OQSPIF_ERASECMDC_OFFSET 0x0030     /* The way of erasing in Auto mode (command */
#define DA1470X_OQSPIF_BURSTBRK_OFFSET 0x0034      /* Read break sequence in Auto mode */
#define DA1470X_OQSPIF_STATUSCMD_OFFSET 0x0038     /* The way of reading the status of externa */
#define DA1470X_OQSPIF_CHCKERASE_OFFSET 0x003c     /* Check erase progress in Auto mode */
#define DA1470X_OQSPIF_GP_OFFSET 0x0040            /* OSPI General Purpose control register */
#define DA1470X_OQSPIF_CTR_CTRL_OFFSET 0x0100      /* Control register for the decryption engi */
#define DA1470X_OQSPIF_CTR_SADDR_OFFSET 0x0104     /* Start address of the encrypted content i */
#define DA1470X_OQSPIF_CTR_EADDR_OFFSET 0x0108     /* End address of the encrypted content in */
#define DA1470X_OQSPIF_CTR_NONCE_0_3_OFFSET 0x010c /* Nonce bytes 0 to 3 for the AES-CTR algor */
#define DA1470X_OQSPIF_CTR_NONCE_4_7_OFFSET 0x0110 /* Nonce bytes 4 to 7 for the AES-CTR algor */
#define DA1470X_OQSPIF_CTR_KEY_0_3_OFFSET 0x0114   /* Key bytes 0 to 3 for the AES-CTR algorit */
#define DA1470X_OQSPIF_CTR_KEY_4_7_OFFSET 0x0118   /* Key bytes 4 to 7 for the AES-CTR algorit */
#define DA1470X_OQSPIF_CTR_KEY_8_11_OFFSET 0x011c  /* Key bytes 8 to 11 for the AES-CTR algori */
#define DA1470X_OQSPIF_CTR_KEY_12_15_OFFSET 0x0120 /* Key bytes 12 to 15 for the AES-CTR algor */
#define DA1470X_OQSPIF_CTR_KEY_16_19_OFFSET 0x0124 /* Key bytes 16 to 19 for the AES-CTR algor */
#define DA1470X_OQSPIF_CTR_KEY_20_23_OFFSET 0x0128 /* Key bytes 20 to 23 for the AES-CTR algor */
#define DA1470X_OQSPIF_CTR_KEY_24_27_OFFSET 0x012c /* Key bytes 24 to 27 for the AES-CTR algor */
#define DA1470X_OQSPIF_CTR_KEY_28_31_OFFSET 0x0130 /* Key bytes 28 to 31 for the AES-CTR algor */

/* Register Addresses *******************************************************/

#define DA1470X_OQSPIF_CTRLBUS (DA1470X_OQSPIF_BASE + DA1470X_OQSPIF_CTRLBUS_OFFSET)
#define DA1470X_OQSPIF_CTRLMODE (DA1470X_OQSPIF_BASE + DA1470X_OQSPIF_CTRLMODE_OFFSET)
#define DA1470X_OQSPIF_RECVDATA (DA1470X_OQSPIF_BASE + DA1470X_OQSPIF_RECVDATA_OFFSET)
#define DA1470X_OQSPIF_BURSTCMDA (DA1470X_OQSPIF_BASE + DA1470X_OQSPIF_BURSTCMDA_OFFSET)
#define DA1470X_OQSPIF_BURSTCMDB (DA1470X_OQSPIF_BASE + DA1470X_OQSPIF_BURSTCMDB_OFFSET)
#define DA1470X_OQSPIF_STATUS (DA1470X_OQSPIF_BASE + DA1470X_OQSPIF_STATUS_OFFSET)
#define DA1470X_OQSPIF_WRITEDATA (DA1470X_OQSPIF_BASE + DA1470X_OQSPIF_WRITEDATA_OFFSET)
#define DA1470X_OQSPIF_READDATA (DA1470X_OQSPIF_BASE + DA1470X_OQSPIF_READDATA_OFFSET)
#define DA1470X_OQSPIF_DUMMYDATA (DA1470X_OQSPIF_BASE + DA1470X_OQSPIF_DUMMYDATA_OFFSET)
#define DA1470X_OQSPIF_ERASECTRL (DA1470X_OQSPIF_BASE + DA1470X_OQSPIF_ERASECTRL_OFFSET)
#define DA1470X_OQSPIF_ERASECMDA (DA1470X_OQSPIF_BASE + DA1470X_OQSPIF_ERASECMDA_OFFSET)
#define DA1470X_OQSPIF_ERASECMDB (DA1470X_OQSPIF_BASE + DA1470X_OQSPIF_ERASECMDB_OFFSET)
#define DA1470X_OQSPIF_ERASECMDC (DA1470X_OQSPIF_BASE + DA1470X_OQSPIF_ERASECMDC_OFFSET)
#define DA1470X_OQSPIF_BURSTBRK (DA1470X_OQSPIF_BASE + DA1470X_OQSPIF_BURSTBRK_OFFSET)
#define DA1470X_OQSPIF_STATUSCMD (DA1470X_OQSPIF_BASE + DA1470X_OQSPIF_STATUSCMD_OFFSET)
#define DA1470X_OQSPIF_CHCKERASE (DA1470X_OQSPIF_BASE + DA1470X_OQSPIF_CHCKERASE_OFFSET)
#define DA1470X_OQSPIF_GP (DA1470X_OQSPIF_BASE + DA1470X_OQSPIF_GP_OFFSET)
#define DA1470X_OQSPIF_CTR_CTRL (DA1470X_OQSPIF_BASE + DA1470X_OQSPIF_CTR_CTRL_OFFSET)
#define DA1470X_OQSPIF_CTR_SADDR (DA1470X_OQSPIF_BASE + DA1470X_OQSPIF_CTR_SADDR_OFFSET)
#define DA1470X_OQSPIF_CTR_EADDR (DA1470X_OQSPIF_BASE + DA1470X_OQSPIF_CTR_EADDR_OFFSET)
#define DA1470X_OQSPIF_CTR_NONCE_0_3 (DA1470X_OQSPIF_BASE + DA1470X_OQSPIF_CTR_NONCE_0_3_OFFSET)
#define DA1470X_OQSPIF_CTR_NONCE_4_7 (DA1470X_OQSPIF_BASE + DA1470X_OQSPIF_CTR_NONCE_4_7_OFFSET)
#define DA1470X_OQSPIF_CTR_KEY_0_3 (DA1470X_OQSPIF_BASE + DA1470X_OQSPIF_CTR_KEY_0_3_OFFSET)
#define DA1470X_OQSPIF_CTR_KEY_4_7 (DA1470X_OQSPIF_BASE + DA1470X_OQSPIF_CTR_KEY_4_7_OFFSET)
#define DA1470X_OQSPIF_CTR_KEY_8_11 (DA1470X_OQSPIF_BASE + DA1470X_OQSPIF_CTR_KEY_8_11_OFFSET)
#define DA1470X_OQSPIF_CTR_KEY_12_15 (DA1470X_OQSPIF_BASE + DA1470X_OQSPIF_CTR_KEY_12_15_OFFSET)
#define DA1470X_OQSPIF_CTR_KEY_16_19 (DA1470X_OQSPIF_BASE + DA1470X_OQSPIF_CTR_KEY_16_19_OFFSET)
#define DA1470X_OQSPIF_CTR_KEY_20_23 (DA1470X_OQSPIF_BASE + DA1470X_OQSPIF_CTR_KEY_20_23_OFFSET)
#define DA1470X_OQSPIF_CTR_KEY_24_27 (DA1470X_OQSPIF_BASE + DA1470X_OQSPIF_CTR_KEY_24_27_OFFSET)
#define DA1470X_OQSPIF_CTR_KEY_28_31 (DA1470X_OQSPIF_BASE + DA1470X_OQSPIF_CTR_KEY_28_31_OFFSET)

/* Register Bit-field Definitions *******************************************/

/* CTRLBUS register */

#define OQSPIF_CTRLBUS_OSPIC_SET_SINGLE (1 << 0) /* Bit 0 */
#define OQSPIF_CTRLBUS_OSPIC_SET_DUAL (1 << 1)   /* Bit 1 */
#define OQSPIF_CTRLBUS_OSPIC_SET_QUAD (1 << 2)   /* Bit 2 */
#define OQSPIF_CTRLBUS_OSPIC_SET_OCTAL (1 << 3)  /* Bit 3 */
#define OQSPIF_CTRLBUS_OSPIC_EN_CS (1 << 4)      /* Bit 4 */
#define OQSPIF_CTRLBUS_OSPIC_DIS_CS (1 << 5)     /* Bit 5 */

/* CTRLMODE register */

#define OQSPIF_CTRLMODE_OSPIC_AUTO_MD (1 << 0)        /* Bit 0 */
#define OQSPIF_CTRLMODE_OSPIC_CLK_MD (1 << 1)         /* Bit 1 */
#define OQSPIF_CTRLMODE_OSPIC_IO2_OEN (1 << 2)        /* Bit 2 */
#define OQSPIF_CTRLMODE_OSPIC_IO3_OEN (1 << 3)        /* Bit 3 */
#define OQSPIF_CTRLMODE_OSPIC_IO2_DAT (1 << 4)        /* Bit 4 */
#define OQSPIF_CTRLMODE_OSPIC_IO3_DAT (1 << 5)        /* Bit 5 */
#define OQSPIF_CTRLMODE_OSPIC_HRDY_MD (1 << 6)        /* Bit 6 */
#define OQSPIF_CTRLMODE_OSPIC_RXD_NEG (1 << 7)        /* Bit 7 */
#define OQSPIF_CTRLMODE_OSPIC_RPIPE_EN (1 << 8)       /* Bit 8 */
#define OQSPIF_CTRLMODE_OSPIC_PCLK_MD_SHIFT (9)       /* Bits 9-11 */
#define OQSPIF_CTRLMODE_OSPIC_PCLK_MD_MASK (0x7 << OQSPIF_CTRLMODE_OSPIC_PCLK_MD_SHIFT)
#  define OQSPIF_CTRLMODE_OSPIC_PCLK_MD(n) ((uint32_t)(n) << OQSPIF_CTRLMODE_OSPIC_PCLK_MD_SHIFT)
#define OQSPIF_CTRLMODE_OSPIC_BUF_LIM_EN (1 << 12)    /* Bit 12 */
#define OQSPIF_CTRLMODE_OSPIC_USE_32BA (1 << 13)      /* Bit 13 */
#define OQSPIF_CTRLMODE_OSPIC_CMD_X2_EN (1 << 14)     /* Bit 14 */
#define OQSPIF_CTRLMODE_OSPIC_DMY_MD (1 << 15)        /* Bit 15 */
#define OQSPIF_CTRLMODE_OSPIC_MAN_DIRCHG_MD (1 << 16) /* Bit 16 */
#define OQSPIF_CTRLMODE_OSPIC_RD_ERR_EN (1 << 17)     /* Bit 17 */
#define OQSPIF_CTRLMODE_OSPIC_INC_LIM_EN (1 << 18)    /* Bit 18 */
#define OQSPIF_CTRLMODE_OSPIC_IO_UH_OEN (1 << 27)     /* Bit 27 */
#define OQSPIF_CTRLMODE_OSPIC_IO_UH_DAT_SHIFT (28)    /* Bits 28-31 */
#define OQSPIF_CTRLMODE_OSPIC_IO_UH_DAT_MASK (0xf << OQSPIF_CTRLMODE_OSPIC_IO_UH_DAT_SHIFT)
#  define OQSPIF_CTRLMODE_OSPIC_IO_UH_DAT(n) ((uint32_t)(n) << OQSPIF_CTRLMODE_OSPIC_IO_UH_DAT_SHIFT)

/* RECVDATA register */

#define OQSPIF_RECVDATA_OSPIC_RECVDATA_SHIFT (0) /* Bits 0-31 */
#define OQSPIF_RECVDATA_OSPIC_RECVDATA_MASK (0xffffffff << OQSPIF_RECVDATA_OSPIC_RECVDATA_SHIFT)
#  define OQSPIF_RECVDATA_OSPIC_RECVDATA(n) ((uint32_t)(n) << OQSPIF_RECVDATA_OSPIC_RECVDATA_SHIFT)

/* BURSTCMDA register */

#define OQSPIF_BURSTCMDA_OSPIC_INST_SHIFT (0)        /* Bits 0-7 */
#define OQSPIF_BURSTCMDA_OSPIC_INST_MASK (0xff << OQSPIF_BURSTCMDA_OSPIC_INST_SHIFT)
#  define OQSPIF_BURSTCMDA_OSPIC_INST(n) ((uint32_t)(n) << OQSPIF_BURSTCMDA_OSPIC_INST_SHIFT)
#define OQSPIF_BURSTCMDA_OSPIC_INST_WB_SHIFT (8)     /* Bits 8-15 */
#define OQSPIF_BURSTCMDA_OSPIC_INST_WB_MASK (0xff << OQSPIF_BURSTCMDA_OSPIC_INST_WB_SHIFT)
#  define OQSPIF_BURSTCMDA_OSPIC_INST_WB(n) ((uint32_t)(n) << OQSPIF_BURSTCMDA_OSPIC_INST_WB_SHIFT)
#define OQSPIF_BURSTCMDA_OSPIC_EXT_BYTE_SHIFT (16)   /* Bits 16-23 */
#define OQSPIF_BURSTCMDA_OSPIC_EXT_BYTE_MASK (0xff << OQSPIF_BURSTCMDA_OSPIC_EXT_BYTE_SHIFT)
#  define OQSPIF_BURSTCMDA_OSPIC_EXT_BYTE(n) ((uint32_t)(n) << OQSPIF_BURSTCMDA_OSPIC_EXT_BYTE_SHIFT)
#define OQSPIF_BURSTCMDA_OSPIC_INST_TX_MD_SHIFT (24) /* Bits 24-25 */
#define OQSPIF_BURSTCMDA_OSPIC_INST_TX_MD_MASK (0x3 << OQSPIF_BURSTCMDA_OSPIC_INST_TX_MD_SHIFT)
#  define OQSPIF_BURSTCMDA_OSPIC_INST_TX_MD(n) ((uint32_t)(n) << OQSPIF_BURSTCMDA_OSPIC_INST_TX_MD_SHIFT)
#define OQSPIF_BURSTCMDA_OSPIC_ADR_TX_MD_SHIFT (26)  /* Bits 26-27 */
#define OQSPIF_BURSTCMDA_OSPIC_ADR_TX_MD_MASK (0x3 << OQSPIF_BURSTCMDA_OSPIC_ADR_TX_MD_SHIFT)
#  define OQSPIF_BURSTCMDA_OSPIC_ADR_TX_MD(n) ((uint32_t)(n) << OQSPIF_BURSTCMDA_OSPIC_ADR_TX_MD_SHIFT)
#define OQSPIF_BURSTCMDA_OSPIC_EXT_TX_MD_SHIFT (28)  /* Bits 28-29 */
#define OQSPIF_BURSTCMDA_OSPIC_EXT_TX_MD_MASK (0x3 << OQSPIF_BURSTCMDA_OSPIC_EXT_TX_MD_SHIFT)
#  define OQSPIF_BURSTCMDA_OSPIC_EXT_TX_MD(n) ((uint32_t)(n) << OQSPIF_BURSTCMDA_OSPIC_EXT_TX_MD_SHIFT)
#define OQSPIF_BURSTCMDA_OSPIC_DMY_TX_MD_SHIFT (30)  /* Bits 30-31 */
#define OQSPIF_BURSTCMDA_OSPIC_DMY_TX_MD_MASK (0x3 << OQSPIF_BURSTCMDA_OSPIC_DMY_TX_MD_SHIFT)
#  define OQSPIF_BURSTCMDA_OSPIC_DMY_TX_MD(n) ((uint32_t)(n) << OQSPIF_BURSTCMDA_OSPIC_DMY_TX_MD_SHIFT)

/* BURSTCMDB register */

#define OQSPIF_BURSTCMDB_OSPIC_DAT_RX_MD_SHIFT (0)    /* Bits 0-1 */
#define OQSPIF_BURSTCMDB_OSPIC_DAT_RX_MD_MASK (0x3 << OQSPIF_BURSTCMDB_OSPIC_DAT_RX_MD_SHIFT)
#  define OQSPIF_BURSTCMDB_OSPIC_DAT_RX_MD(n) ((uint32_t)(n) << OQSPIF_BURSTCMDB_OSPIC_DAT_RX_MD_SHIFT)
#define OQSPIF_BURSTCMDB_OSPIC_EXT_BYTE_EN (1 << 2)   /* Bit 2 */
#define OQSPIF_BURSTCMDB_OSPIC_EXT_HF_DS (1 << 3)     /* Bit 3 */
#define OQSPIF_BURSTCMDB_OSPIC_DMY_NUM_SHIFT (4)      /* Bits 4-8 */
#define OQSPIF_BURSTCMDB_OSPIC_DMY_NUM_MASK (0x1f << OQSPIF_BURSTCMDB_OSPIC_DMY_NUM_SHIFT)
#  define OQSPIF_BURSTCMDB_OSPIC_DMY_NUM(n) ((uint32_t)(n) << OQSPIF_BURSTCMDB_OSPIC_DMY_NUM_SHIFT)
#define OQSPIF_BURSTCMDB_OSPIC_DMY_EN (1 << 9)        /* Bit 9 */
#define OQSPIF_BURSTCMDB_OSPIC_INST_MD (1 << 10)      /* Bit 10 */
#define OQSPIF_BURSTCMDB_OSPIC_WRAP_MD (1 << 11)      /* Bit 11 */
#define OQSPIF_BURSTCMDB_OSPIC_WRAP_LEN_SHIFT (12)    /* Bits 12-13 */
#define OQSPIF_BURSTCMDB_OSPIC_WRAP_LEN_MASK (0x3 << OQSPIF_BURSTCMDB_OSPIC_WRAP_LEN_SHIFT)
#  define OQSPIF_BURSTCMDB_OSPIC_WRAP_LEN(n) ((uint32_t)(n) << OQSPIF_BURSTCMDB_OSPIC_WRAP_LEN_SHIFT)
#define OQSPIF_BURSTCMDB_OSPIC_WRAP_SIZE_SHIFT (14)   /* Bits 14-15 */
#define OQSPIF_BURSTCMDB_OSPIC_WRAP_SIZE_MASK (0x3 << OQSPIF_BURSTCMDB_OSPIC_WRAP_SIZE_SHIFT)
#  define OQSPIF_BURSTCMDB_OSPIC_WRAP_SIZE(n) ((uint32_t)(n) << OQSPIF_BURSTCMDB_OSPIC_WRAP_SIZE_SHIFT)
#define OQSPIF_BURSTCMDB_OSPIC_CS_HIGH_MIN_SHIFT (16) /* Bits 16-18 */
#define OQSPIF_BURSTCMDB_OSPIC_CS_HIGH_MIN_MASK (0x7 << OQSPIF_BURSTCMDB_OSPIC_CS_HIGH_MIN_SHIFT)
#  define OQSPIF_BURSTCMDB_OSPIC_CS_HIGH_MIN(n) ((uint32_t)(n) << OQSPIF_BURSTCMDB_OSPIC_CS_HIGH_MIN_SHIFT)

/* STATUS register */

#define OQSPIF_STATUS_OSPIC_BUSY (1 << 0) /* Bit 0 */

/* WRITEDATA register */

#define OQSPIF_WRITEDATA_OSPIC_WRITEDATA_SHIFT (0) /* Bits 0-31 */
#define OQSPIF_WRITEDATA_OSPIC_WRITEDATA_MASK (0xffffffff << OQSPIF_WRITEDATA_OSPIC_WRITEDATA_SHIFT)
#  define OQSPIF_WRITEDATA_OSPIC_WRITEDATA(n) ((uint32_t)(n) << OQSPIF_WRITEDATA_OSPIC_WRITEDATA_SHIFT)

/* READDATA register */

#define OQSPIF_READDATA_OSPIC_READDATA_SHIFT (0) /* Bits 0-31 */
#define OQSPIF_READDATA_OSPIC_READDATA_MASK (0xffffffff << OQSPIF_READDATA_OSPIC_READDATA_SHIFT)
#  define OQSPIF_READDATA_OSPIC_READDATA(n) ((uint32_t)(n) << OQSPIF_READDATA_OSPIC_READDATA_SHIFT)

/* DUMMYDATA register */

#define OQSPIF_DUMMYDATA_OSPIC_DUMMYDATA_SHIFT (0) /* Bits 0-31 */
#define OQSPIF_DUMMYDATA_OSPIC_DUMMYDATA_MASK (0xffffffff << OQSPIF_DUMMYDATA_OSPIC_DUMMYDATA_SHIFT)
#  define OQSPIF_DUMMYDATA_OSPIC_DUMMYDATA(n) ((uint32_t)(n) << OQSPIF_DUMMYDATA_OSPIC_DUMMYDATA_SHIFT)

/* ERASECTRL register */

#define OQSPIF_ERASECTRL_OSPIC_ERS_ADDR_SHIFT (4)    /* Bits 4-23 */
#define OQSPIF_ERASECTRL_OSPIC_ERS_ADDR_MASK (0xfffff << OQSPIF_ERASECTRL_OSPIC_ERS_ADDR_SHIFT)
#  define OQSPIF_ERASECTRL_OSPIC_ERS_ADDR(n) ((uint32_t)(n) << OQSPIF_ERASECTRL_OSPIC_ERS_ADDR_SHIFT)
#define OQSPIF_ERASECTRL_OSPIC_ERASE_EN (1 << 24)    /* Bit 24 */
#define OQSPIF_ERASECTRL_OSPIC_ERS_STATE_SHIFT (25)  /* Bits 25-27 */
#define OQSPIF_ERASECTRL_OSPIC_ERS_STATE_MASK (0x7 << OQSPIF_ERASECTRL_OSPIC_ERS_STATE_SHIFT)
#  define OQSPIF_ERASECTRL_OSPIC_ERS_STATE(n) ((uint32_t)(n) << OQSPIF_ERASECTRL_OSPIC_ERS_STATE_SHIFT)
#define OQSPIF_ERASECTRL_OSPIC_ERS_RES_DIS (1 << 28) /* Bit 28 */

/* ERASECMDA register */

#define OQSPIF_ERASECMDA_OSPIC_ERS_INST_SHIFT (0)  /* Bits 0-7 */
#define OQSPIF_ERASECMDA_OSPIC_ERS_INST_MASK (0xff << OQSPIF_ERASECMDA_OSPIC_ERS_INST_SHIFT)
#  define OQSPIF_ERASECMDA_OSPIC_ERS_INST(n) ((uint32_t)(n) << OQSPIF_ERASECMDA_OSPIC_ERS_INST_SHIFT)
#define OQSPIF_ERASECMDA_OSPIC_WEN_INST_SHIFT (8)  /* Bits 8-15 */
#define OQSPIF_ERASECMDA_OSPIC_WEN_INST_MASK (0xff << OQSPIF_ERASECMDA_OSPIC_WEN_INST_SHIFT)
#  define OQSPIF_ERASECMDA_OSPIC_WEN_INST(n) ((uint32_t)(n) << OQSPIF_ERASECMDA_OSPIC_WEN_INST_SHIFT)
#define OQSPIF_ERASECMDA_OSPIC_SUS_INST_SHIFT (16) /* Bits 16-23 */
#define OQSPIF_ERASECMDA_OSPIC_SUS_INST_MASK (0xff << OQSPIF_ERASECMDA_OSPIC_SUS_INST_SHIFT)
#  define OQSPIF_ERASECMDA_OSPIC_SUS_INST(n) ((uint32_t)(n) << OQSPIF_ERASECMDA_OSPIC_SUS_INST_SHIFT)
#define OQSPIF_ERASECMDA_OSPIC_RES_INST_SHIFT (24) /* Bits 24-31 */
#define OQSPIF_ERASECMDA_OSPIC_RES_INST_MASK (0xff << OQSPIF_ERASECMDA_OSPIC_RES_INST_SHIFT)
#  define OQSPIF_ERASECMDA_OSPIC_RES_INST(n) ((uint32_t)(n) << OQSPIF_ERASECMDA_OSPIC_RES_INST_SHIFT)

/* ERASECMDB register */

#define OQSPIF_ERASECMDB_OSPIC_ERS_TX_MD_SHIFT (0)   /* Bits 0-1 */
#define OQSPIF_ERASECMDB_OSPIC_ERS_TX_MD_MASK (0x3 << OQSPIF_ERASECMDB_OSPIC_ERS_TX_MD_SHIFT)
#  define OQSPIF_ERASECMDB_OSPIC_ERS_TX_MD(n) ((uint32_t)(n) << OQSPIF_ERASECMDB_OSPIC_ERS_TX_MD_SHIFT)
#define OQSPIF_ERASECMDB_OSPIC_WEN_TX_MD_SHIFT (2)   /* Bits 2-3 */
#define OQSPIF_ERASECMDB_OSPIC_WEN_TX_MD_MASK (0x3 << OQSPIF_ERASECMDB_OSPIC_WEN_TX_MD_SHIFT)
#  define OQSPIF_ERASECMDB_OSPIC_WEN_TX_MD(n) ((uint32_t)(n) << OQSPIF_ERASECMDB_OSPIC_WEN_TX_MD_SHIFT)
#define OQSPIF_ERASECMDB_OSPIC_SUS_TX_MD_SHIFT (4)   /* Bits 4-5 */
#define OQSPIF_ERASECMDB_OSPIC_SUS_TX_MD_MASK (0x3 << OQSPIF_ERASECMDB_OSPIC_SUS_TX_MD_SHIFT)
#  define OQSPIF_ERASECMDB_OSPIC_SUS_TX_MD(n) ((uint32_t)(n) << OQSPIF_ERASECMDB_OSPIC_SUS_TX_MD_SHIFT)
#define OQSPIF_ERASECMDB_OSPIC_RES_TX_MD_SHIFT (6)   /* Bits 6-7 */
#define OQSPIF_ERASECMDB_OSPIC_RES_TX_MD_MASK (0x3 << OQSPIF_ERASECMDB_OSPIC_RES_TX_MD_SHIFT)
#  define OQSPIF_ERASECMDB_OSPIC_RES_TX_MD(n) ((uint32_t)(n) << OQSPIF_ERASECMDB_OSPIC_RES_TX_MD_SHIFT)
#define OQSPIF_ERASECMDB_OSPIC_EAD_TX_MD_SHIFT (8)   /* Bits 8-9 */
#define OQSPIF_ERASECMDB_OSPIC_EAD_TX_MD_MASK (0x3 << OQSPIF_ERASECMDB_OSPIC_EAD_TX_MD_SHIFT)
#  define OQSPIF_ERASECMDB_OSPIC_EAD_TX_MD(n) ((uint32_t)(n) << OQSPIF_ERASECMDB_OSPIC_EAD_TX_MD_SHIFT)
#define OQSPIF_ERASECMDB_OSPIC_ERS_CS_HI_SHIFT (10)  /* Bits 10-14 */
#define OQSPIF_ERASECMDB_OSPIC_ERS_CS_HI_MASK (0x1f << OQSPIF_ERASECMDB_OSPIC_ERS_CS_HI_SHIFT)
#  define OQSPIF_ERASECMDB_OSPIC_ERS_CS_HI(n) ((uint32_t)(n) << OQSPIF_ERASECMDB_OSPIC_ERS_CS_HI_SHIFT)
#define OQSPIF_ERASECMDB_OSPIC_ERSRES_HLD_SHIFT (16) /* Bits 16-19 */
#define OQSPIF_ERASECMDB_OSPIC_ERSRES_HLD_MASK (0xf << OQSPIF_ERASECMDB_OSPIC_ERSRES_HLD_SHIFT)
#  define OQSPIF_ERASECMDB_OSPIC_ERSRES_HLD(n) ((uint32_t)(n) << OQSPIF_ERASECMDB_OSPIC_ERSRES_HLD_SHIFT)
#define OQSPIF_ERASECMDB_OSPIC_RESSUS_DLY_SHIFT (24) /* Bits 24-31 */
#define OQSPIF_ERASECMDB_OSPIC_RESSUS_DLY_MASK (0xff << OQSPIF_ERASECMDB_OSPIC_RESSUS_DLY_SHIFT)
#  define OQSPIF_ERASECMDB_OSPIC_RESSUS_DLY(n) ((uint32_t)(n) << OQSPIF_ERASECMDB_OSPIC_RESSUS_DLY_SHIFT)

/* ERASECMDC register */

#define OQSPIF_ERASECMDC_OSPIC_SUSSTS_DLY_SHIFT (0) /* Bits 0-5 */
#define OQSPIF_ERASECMDC_OSPIC_SUSSTS_DLY_MASK (0x3f << OQSPIF_ERASECMDC_OSPIC_SUSSTS_DLY_SHIFT)
#  define OQSPIF_ERASECMDC_OSPIC_SUSSTS_DLY(n) ((uint32_t)(n) << OQSPIF_ERASECMDC_OSPIC_SUSSTS_DLY_SHIFT)

/* BURSTBRK register */

#define OQSPIF_BURSTBRK_OSPIC_BRK_WRD_SHIFT (0)    /* Bits 0-15 */
#define OQSPIF_BURSTBRK_OSPIC_BRK_WRD_MASK (0xffff << OQSPIF_BURSTBRK_OSPIC_BRK_WRD_SHIFT)
#  define OQSPIF_BURSTBRK_OSPIC_BRK_WRD(n) ((uint32_t)(n) << OQSPIF_BURSTBRK_OSPIC_BRK_WRD_SHIFT)
#define OQSPIF_BURSTBRK_OSPIC_BRK_SZ_SHIFT (16)    /* Bits 16-19 */
#define OQSPIF_BURSTBRK_OSPIC_BRK_SZ_MASK (0xf << OQSPIF_BURSTBRK_OSPIC_BRK_SZ_SHIFT)
#  define OQSPIF_BURSTBRK_OSPIC_BRK_SZ(n) ((uint32_t)(n) << OQSPIF_BURSTBRK_OSPIC_BRK_SZ_SHIFT)
#define OQSPIF_BURSTBRK_OSPIC_BRK_TX_MD_SHIFT (20) /* Bits 20-21 */
#define OQSPIF_BURSTBRK_OSPIC_BRK_TX_MD_MASK (0x3 << OQSPIF_BURSTBRK_OSPIC_BRK_TX_MD_SHIFT)
#  define OQSPIF_BURSTBRK_OSPIC_BRK_TX_MD(n) ((uint32_t)(n) << OQSPIF_BURSTBRK_OSPIC_BRK_TX_MD_SHIFT)
#define OQSPIF_BURSTBRK_OSPIC_SEC_HF_DS (1 << 22)  /* Bit 22 */
#define OQSPIF_BURSTBRK_OSPIC_BRK_EN (1 << 23)     /* Bit 23 */

/* STATUSCMD register */

#define OQSPIF_STATUSCMD_OSPIC_RSTAT_INST_SHIFT (0)       /* Bits 0-7 */
#define OQSPIF_STATUSCMD_OSPIC_RSTAT_INST_MASK (0xff << OQSPIF_STATUSCMD_OSPIC_RSTAT_INST_SHIFT)
#  define OQSPIF_STATUSCMD_OSPIC_RSTAT_INST(n) ((uint32_t)(n) << OQSPIF_STATUSCMD_OSPIC_RSTAT_INST_SHIFT)
#define OQSPIF_STATUSCMD_OSPIC_RSTAT_TX_MD_SHIFT (8)      /* Bits 8-9 */
#define OQSPIF_STATUSCMD_OSPIC_RSTAT_TX_MD_MASK (0x3 << OQSPIF_STATUSCMD_OSPIC_RSTAT_TX_MD_SHIFT)
#  define OQSPIF_STATUSCMD_OSPIC_RSTAT_TX_MD(n) ((uint32_t)(n) << OQSPIF_STATUSCMD_OSPIC_RSTAT_TX_MD_SHIFT)
#define OQSPIF_STATUSCMD_OSPIC_RSTAT_RX_MD_SHIFT (10)     /* Bits 10-11 */
#define OQSPIF_STATUSCMD_OSPIC_RSTAT_RX_MD_MASK (0x3 << OQSPIF_STATUSCMD_OSPIC_RSTAT_RX_MD_SHIFT)
#  define OQSPIF_STATUSCMD_OSPIC_RSTAT_RX_MD(n) ((uint32_t)(n) << OQSPIF_STATUSCMD_OSPIC_RSTAT_RX_MD_SHIFT)
#define OQSPIF_STATUSCMD_OSPIC_BUSY_POS_SHIFT (12)        /* Bits 12-14 */
#define OQSPIF_STATUSCMD_OSPIC_BUSY_POS_MASK (0x7 << OQSPIF_STATUSCMD_OSPIC_BUSY_POS_SHIFT)
#  define OQSPIF_STATUSCMD_OSPIC_BUSY_POS(n) ((uint32_t)(n) << OQSPIF_STATUSCMD_OSPIC_BUSY_POS_SHIFT)
#define OQSPIF_STATUSCMD_OSPIC_BUSY_VAL (1 << 15)         /* Bit 15 */
#define OQSPIF_STATUSCMD_OSPIC_RESSTS_DLY_SHIFT (16)      /* Bits 16-21 */
#define OQSPIF_STATUSCMD_OSPIC_RESSTS_DLY_MASK (0x3f << OQSPIF_STATUSCMD_OSPIC_RESSTS_DLY_SHIFT)
#  define OQSPIF_STATUSCMD_OSPIC_RESSTS_DLY(n) ((uint32_t)(n) << OQSPIF_STATUSCMD_OSPIC_RESSTS_DLY_SHIFT)
#define OQSPIF_STATUSCMD_OSPIC_STSDLY_SEL (1 << 22)       /* Bit 22 */
#define OQSPIF_STATUSCMD_OSPIC_RSTAT_DMY_EN (1 << 23)     /* Bit 23 */
#define OQSPIF_STATUSCMD_OSPIC_RSTAT_DMY_NUM_SHIFT (24)   /* Bits 24-27 */
#define OQSPIF_STATUSCMD_OSPIC_RSTAT_DMY_NUM_MASK (0xf << OQSPIF_STATUSCMD_OSPIC_RSTAT_DMY_NUM_SHIFT)
#  define OQSPIF_STATUSCMD_OSPIC_RSTAT_DMY_NUM(n) ((uint32_t)(n) << OQSPIF_STATUSCMD_OSPIC_RSTAT_DMY_NUM_SHIFT)
#define OQSPIF_STATUSCMD_OSPIC_RSTAT_DMY_TX_MD_SHIFT (28) /* Bits 28-29 */
#define OQSPIF_STATUSCMD_OSPIC_RSTAT_DMY_TX_MD_MASK (0x3 << OQSPIF_STATUSCMD_OSPIC_RSTAT_DMY_TX_MD_SHIFT)
#  define OQSPIF_STATUSCMD_OSPIC_RSTAT_DMY_TX_MD(n) ((uint32_t)(n) << OQSPIF_STATUSCMD_OSPIC_RSTAT_DMY_TX_MD_SHIFT)
#define OQSPIF_STATUSCMD_OSPIC_RSTAT_DMY_ZERO (1 << 30)   /* Bit 30 */

/* CHCKERASE register */

#define OQSPIF_CHCKERASE_OSPIC_CHCKERASE_SHIFT (0) /* Bits 0-31 */
#define OQSPIF_CHCKERASE_OSPIC_CHCKERASE_MASK (0xffffffff << OQSPIF_CHCKERASE_OSPIC_CHCKERASE_SHIFT)
#  define OQSPIF_CHCKERASE_OSPIC_CHCKERASE(n) ((uint32_t)(n) << OQSPIF_CHCKERASE_OSPIC_CHCKERASE_SHIFT)

/* GP register */

#define OQSPIF_GP_OSPIC_PADS_DRV_SHIFT (1)  /* Bits 1-2 */
#define OQSPIF_GP_OSPIC_PADS_DRV_MASK (0x3 << OQSPIF_GP_OSPIC_PADS_DRV_SHIFT)
#  define OQSPIF_GP_OSPIC_PADS_DRV(n) ((uint32_t)(n) << OQSPIF_GP_OSPIC_PADS_DRV_SHIFT)
#define OQSPIF_GP_OSPIC_PADS_SLEW_SHIFT (3) /* Bits 3-4 */
#define OQSPIF_GP_OSPIC_PADS_SLEW_MASK (0x3 << OQSPIF_GP_OSPIC_PADS_SLEW_SHIFT)
#  define OQSPIF_GP_OSPIC_PADS_SLEW(n) ((uint32_t)(n) << OQSPIF_GP_OSPIC_PADS_SLEW_SHIFT)

/* CTR_CTRL register */

#define OQSPIF_CTR_CTRL_OSPIC_CTR_EN (1 << 0) /* Bit 0 */

/* CTR_SADDR register */

#define OQSPIF_CTR_SADDR_OSPIC_CTR_SADDR_SHIFT (10) /* Bits 10-31 */
#define OQSPIF_CTR_SADDR_OSPIC_CTR_SADDR_MASK (0x3fffff << OQSPIF_CTR_SADDR_OSPIC_CTR_SADDR_SHIFT)
#  define OQSPIF_CTR_SADDR_OSPIC_CTR_SADDR(n) ((uint32_t)(n) << OQSPIF_CTR_SADDR_OSPIC_CTR_SADDR_SHIFT)

/* CTR_EADDR register */

#define OQSPIF_CTR_EADDR_OSPIC_CTR_EADDR_SHIFT (10) /* Bits 10-31 */
#define OQSPIF_CTR_EADDR_OSPIC_CTR_EADDR_MASK (0x3fffff << OQSPIF_CTR_EADDR_OSPIC_CTR_EADDR_SHIFT)
#  define OQSPIF_CTR_EADDR_OSPIC_CTR_EADDR(n) ((uint32_t)(n) << OQSPIF_CTR_EADDR_OSPIC_CTR_EADDR_SHIFT)

/* CTR_NONCE_0_3 register */

#define OQSPIF_CTR_NONCE_0_3_OSPIC_CTR_NONCE_0_3_SHIFT (0) /* Bits 0-31 */
#define OQSPIF_CTR_NONCE_0_3_OSPIC_CTR_NONCE_0_3_MASK (0xffffffff << OQSPIF_CTR_NONCE_0_3_OSPIC_CTR_NONCE_0_3_SHIFT)
#  define OQSPIF_CTR_NONCE_0_3_OSPIC_CTR_NONCE_0_3(n) ((uint32_t)(n) << OQSPIF_CTR_NONCE_0_3_OSPIC_CTR_NONCE_0_3_SHIFT)

/* CTR_NONCE_4_7 register */

#define OQSPIF_CTR_NONCE_4_7_OSPIC_CTR_NONCE_4_7_SHIFT (0) /* Bits 0-31 */
#define OQSPIF_CTR_NONCE_4_7_OSPIC_CTR_NONCE_4_7_MASK (0xffffffff << OQSPIF_CTR_NONCE_4_7_OSPIC_CTR_NONCE_4_7_SHIFT)
#  define OQSPIF_CTR_NONCE_4_7_OSPIC_CTR_NONCE_4_7(n) ((uint32_t)(n) << OQSPIF_CTR_NONCE_4_7_OSPIC_CTR_NONCE_4_7_SHIFT)

/* CTR_KEY_0_3 register */

#define OQSPIF_CTR_KEY_0_3_OSPIC_CTR_KEY_0_3_SHIFT (0) /* Bits 0-31 */
#define OQSPIF_CTR_KEY_0_3_OSPIC_CTR_KEY_0_3_MASK (0xffffffff << OQSPIF_CTR_KEY_0_3_OSPIC_CTR_KEY_0_3_SHIFT)
#  define OQSPIF_CTR_KEY_0_3_OSPIC_CTR_KEY_0_3(n) ((uint32_t)(n) << OQSPIF_CTR_KEY_0_3_OSPIC_CTR_KEY_0_3_SHIFT)

/* CTR_KEY_4_7 register */

#define OQSPIF_CTR_KEY_4_7_OSPIC_CTR_KEY_4_7_SHIFT (0) /* Bits 0-31 */
#define OQSPIF_CTR_KEY_4_7_OSPIC_CTR_KEY_4_7_MASK (0xffffffff << OQSPIF_CTR_KEY_4_7_OSPIC_CTR_KEY_4_7_SHIFT)
#  define OQSPIF_CTR_KEY_4_7_OSPIC_CTR_KEY_4_7(n) ((uint32_t)(n) << OQSPIF_CTR_KEY_4_7_OSPIC_CTR_KEY_4_7_SHIFT)

/* CTR_KEY_8_11 register */

#define OQSPIF_CTR_KEY_8_11_OSPIC_CTR_KEY_8_11_SHIFT (0) /* Bits 0-31 */
#define OQSPIF_CTR_KEY_8_11_OSPIC_CTR_KEY_8_11_MASK (0xffffffff << OQSPIF_CTR_KEY_8_11_OSPIC_CTR_KEY_8_11_SHIFT)
#  define OQSPIF_CTR_KEY_8_11_OSPIC_CTR_KEY_8_11(n) ((uint32_t)(n) << OQSPIF_CTR_KEY_8_11_OSPIC_CTR_KEY_8_11_SHIFT)

/* CTR_KEY_12_15 register */

#define OQSPIF_CTR_KEY_12_15_OSPIC_CTR_KEY_12_15_SHIFT (0) /* Bits 0-31 */
#define OQSPIF_CTR_KEY_12_15_OSPIC_CTR_KEY_12_15_MASK (0xffffffff << OQSPIF_CTR_KEY_12_15_OSPIC_CTR_KEY_12_15_SHIFT)
#  define OQSPIF_CTR_KEY_12_15_OSPIC_CTR_KEY_12_15(n) ((uint32_t)(n) << OQSPIF_CTR_KEY_12_15_OSPIC_CTR_KEY_12_15_SHIFT)

/* CTR_KEY_16_19 register */

#define OQSPIF_CTR_KEY_16_19_OSPIC_CTR_KEY_16_19_SHIFT (0) /* Bits 0-31 */
#define OQSPIF_CTR_KEY_16_19_OSPIC_CTR_KEY_16_19_MASK (0xffffffff << OQSPIF_CTR_KEY_16_19_OSPIC_CTR_KEY_16_19_SHIFT)
#  define OQSPIF_CTR_KEY_16_19_OSPIC_CTR_KEY_16_19(n) ((uint32_t)(n) << OQSPIF_CTR_KEY_16_19_OSPIC_CTR_KEY_16_19_SHIFT)

/* CTR_KEY_20_23 register */

#define OQSPIF_CTR_KEY_20_23_OSPIC_CTR_KEY_20_23_SHIFT (0) /* Bits 0-31 */
#define OQSPIF_CTR_KEY_20_23_OSPIC_CTR_KEY_20_23_MASK (0xffffffff << OQSPIF_CTR_KEY_20_23_OSPIC_CTR_KEY_20_23_SHIFT)
#  define OQSPIF_CTR_KEY_20_23_OSPIC_CTR_KEY_20_23(n) ((uint32_t)(n) << OQSPIF_CTR_KEY_20_23_OSPIC_CTR_KEY_20_23_SHIFT)

/* CTR_KEY_24_27 register */

#define OQSPIF_CTR_KEY_24_27_OSPIC_CTR_KEY_24_27_SHIFT (0) /* Bits 0-31 */
#define OQSPIF_CTR_KEY_24_27_OSPIC_CTR_KEY_24_27_MASK (0xffffffff << OQSPIF_CTR_KEY_24_27_OSPIC_CTR_KEY_24_27_SHIFT)
#  define OQSPIF_CTR_KEY_24_27_OSPIC_CTR_KEY_24_27(n) ((uint32_t)(n) << OQSPIF_CTR_KEY_24_27_OSPIC_CTR_KEY_24_27_SHIFT)

/* CTR_KEY_28_31 register */

#define OQSPIF_CTR_KEY_28_31_OSPIC_CTR_KEY_28_31_SHIFT (0) /* Bits 0-31 */
#define OQSPIF_CTR_KEY_28_31_OSPIC_CTR_KEY_28_31_MASK (0xffffffff << OQSPIF_CTR_KEY_28_31_OSPIC_CTR_KEY_28_31_SHIFT)
#  define OQSPIF_CTR_KEY_28_31_OSPIC_CTR_KEY_28_31(n) ((uint32_t)(n) << OQSPIF_CTR_KEY_28_31_OSPIC_CTR_KEY_28_31_SHIFT)

#endif /* __ARCH_ARM_SRC_DA1470X_HARDWARE_DA1470X_OQSPIF_H */
