/****************************************************************************
 * arch/arm/src/da1470x/hardware/da1470x_crg_xtal.h
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.  The
 * ASF licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 ****************************************************************************/

/* Generated from the Renesas CMSIS device header DA1470x-00.h (SDK
 * 10.2.6.49).  Do not edit by hand; regenerate with tools/genhdr.py.
 */

#ifndef __ARCH_ARM_SRC_DA1470X_HARDWARE_DA1470X_CRG_XTAL_H
#define __ARCH_ARM_SRC_DA1470X_HARDWARE_DA1470X_CRG_XTAL_H

/****************************************************************************
 * Included Files
 ****************************************************************************/

#include <nuttx/config.h>
#include "da1470x_memorymap.h"

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

/* Register Offsets *********************************************************/

#define DA1470X_CRG_XTAL_XTAL32M_START_OFFSET 0x0000      /* Trim values for XTAL32M in START state o */
#define DA1470X_CRG_XTAL_XTAL32M_SETTLE_OFFSET 0x0004     /* Trim values for XTAL32M in SETTLE state */
#define DA1470X_CRG_XTAL_XTAL32M_TRIM_OFFSET 0x0008       /* Trim values for XTAL32M in RUNNING state */
#define DA1470X_CRG_XTAL_XTAL32M_CAP_MEAS_OFFSET 0x000c   /* Capacitance measure circuit control */
#define DA1470X_CRG_XTAL_XTAL32M_FSM_OFFSET 0x0010        /* Startup state machine configuration */
#define DA1470X_CRG_XTAL_XTAL32M_CTRL_OFFSET 0x0014       /* Xtal32m control register */
#define DA1470X_CRG_XTAL_XTAL32M_IRQ_CTRL_OFFSET 0x0018   /* Xtal32m Interrupt control register */
#define DA1470X_CRG_XTAL_XTAL32M_STAT0_OFFSET 0x0024      /* XTAL32M status register */
#define DA1470X_CRG_XTAL_XTAL32M_IRQ_STAT_OFFSET 0x0028   /* XTAL32M IRQ status register */
#define DA1470X_CRG_XTAL_PLL_SYS_CTRL1_OFFSET 0x0060      /* System PLL control register 1. */
#define DA1470X_CRG_XTAL_PLL_SYS_CTRL2_OFFSET 0x0064      /* System PLL control register 2. */
#define DA1470X_CRG_XTAL_PLL_SYS_CTRL3_OFFSET 0x0068      /* System PLL control register 3. */
#define DA1470X_CRG_XTAL_PLL_SYS_STATUS_OFFSET 0x0070     /* System PLL status register. */
#define DA1470X_CRG_XTAL_PLL_USB_CTRL1_OFFSET 0x0074      /* USB PLL control register 1. */
#define DA1470X_CRG_XTAL_PLL_USB_CTRL2_OFFSET 0x0078      /* USB PLL control register 2. */
#define DA1470X_CRG_XTAL_PLL_USB_CTRL3_OFFSET 0x007c      /* USB PLL control register 3. */
#define DA1470X_CRG_XTAL_PLL_USB_STATUS_OFFSET 0x0080     /* USB PLL status register. */
#define DA1470X_CRG_XTAL_SYS_IRQ_CTRL_OFFSET 0x0090       /* System IRQ control register */
#define DA1470X_CRG_XTAL_SET_SYS_IRQ_CTRL_OFFSET 0x0094   /* System IRQ SET register */
#define DA1470X_CRG_XTAL_RESET_SYS_IRQ_CTRL_OFFSET 0x0098 /* System IRQ RESET register */

/* Register Addresses *******************************************************/

#define DA1470X_CRG_XTAL_XTAL32M_START (DA1470X_CRG_XTAL_BASE + DA1470X_CRG_XTAL_XTAL32M_START_OFFSET)
#define DA1470X_CRG_XTAL_XTAL32M_SETTLE (DA1470X_CRG_XTAL_BASE + DA1470X_CRG_XTAL_XTAL32M_SETTLE_OFFSET)
#define DA1470X_CRG_XTAL_XTAL32M_TRIM (DA1470X_CRG_XTAL_BASE + DA1470X_CRG_XTAL_XTAL32M_TRIM_OFFSET)
#define DA1470X_CRG_XTAL_XTAL32M_CAP_MEAS (DA1470X_CRG_XTAL_BASE + DA1470X_CRG_XTAL_XTAL32M_CAP_MEAS_OFFSET)
#define DA1470X_CRG_XTAL_XTAL32M_FSM (DA1470X_CRG_XTAL_BASE + DA1470X_CRG_XTAL_XTAL32M_FSM_OFFSET)
#define DA1470X_CRG_XTAL_XTAL32M_CTRL (DA1470X_CRG_XTAL_BASE + DA1470X_CRG_XTAL_XTAL32M_CTRL_OFFSET)
#define DA1470X_CRG_XTAL_XTAL32M_IRQ_CTRL (DA1470X_CRG_XTAL_BASE + DA1470X_CRG_XTAL_XTAL32M_IRQ_CTRL_OFFSET)
#define DA1470X_CRG_XTAL_XTAL32M_STAT0 (DA1470X_CRG_XTAL_BASE + DA1470X_CRG_XTAL_XTAL32M_STAT0_OFFSET)
#define DA1470X_CRG_XTAL_XTAL32M_IRQ_STAT (DA1470X_CRG_XTAL_BASE + DA1470X_CRG_XTAL_XTAL32M_IRQ_STAT_OFFSET)
#define DA1470X_CRG_XTAL_PLL_SYS_CTRL1 (DA1470X_CRG_XTAL_BASE + DA1470X_CRG_XTAL_PLL_SYS_CTRL1_OFFSET)
#define DA1470X_CRG_XTAL_PLL_SYS_CTRL2 (DA1470X_CRG_XTAL_BASE + DA1470X_CRG_XTAL_PLL_SYS_CTRL2_OFFSET)
#define DA1470X_CRG_XTAL_PLL_SYS_CTRL3 (DA1470X_CRG_XTAL_BASE + DA1470X_CRG_XTAL_PLL_SYS_CTRL3_OFFSET)
#define DA1470X_CRG_XTAL_PLL_SYS_STATUS (DA1470X_CRG_XTAL_BASE + DA1470X_CRG_XTAL_PLL_SYS_STATUS_OFFSET)
#define DA1470X_CRG_XTAL_PLL_USB_CTRL1 (DA1470X_CRG_XTAL_BASE + DA1470X_CRG_XTAL_PLL_USB_CTRL1_OFFSET)
#define DA1470X_CRG_XTAL_PLL_USB_CTRL2 (DA1470X_CRG_XTAL_BASE + DA1470X_CRG_XTAL_PLL_USB_CTRL2_OFFSET)
#define DA1470X_CRG_XTAL_PLL_USB_CTRL3 (DA1470X_CRG_XTAL_BASE + DA1470X_CRG_XTAL_PLL_USB_CTRL3_OFFSET)
#define DA1470X_CRG_XTAL_PLL_USB_STATUS (DA1470X_CRG_XTAL_BASE + DA1470X_CRG_XTAL_PLL_USB_STATUS_OFFSET)
#define DA1470X_CRG_XTAL_SYS_IRQ_CTRL (DA1470X_CRG_XTAL_BASE + DA1470X_CRG_XTAL_SYS_IRQ_CTRL_OFFSET)
#define DA1470X_CRG_XTAL_SET_SYS_IRQ_CTRL (DA1470X_CRG_XTAL_BASE + DA1470X_CRG_XTAL_SET_SYS_IRQ_CTRL_OFFSET)
#define DA1470X_CRG_XTAL_RESET_SYS_IRQ_CTRL (DA1470X_CRG_XTAL_BASE + DA1470X_CRG_XTAL_RESET_SYS_IRQ_CTRL_OFFSET)

/* Register Bit-field Definitions *******************************************/

/* XTAL32M_START register */

#define CRG_XTAL_XTAL32M_START_XTAL32M_TRIM_SHIFT (0)       /* Bits 0-9 */
#define CRG_XTAL_XTAL32M_START_XTAL32M_TRIM_MASK (0x3ff << CRG_XTAL_XTAL32M_START_XTAL32M_TRIM_SHIFT)
#  define CRG_XTAL_XTAL32M_START_XTAL32M_TRIM(n) ((uint32_t)(n) << CRG_XTAL_XTAL32M_START_XTAL32M_TRIM_SHIFT)
#define CRG_XTAL_XTAL32M_START_XTAL32M_CUR_SET_SHIFT (10)   /* Bits 10-13 */
#define CRG_XTAL_XTAL32M_START_XTAL32M_CUR_SET_MASK (0xf << CRG_XTAL_XTAL32M_START_XTAL32M_CUR_SET_SHIFT)
#  define CRG_XTAL_XTAL32M_START_XTAL32M_CUR_SET(n) ((uint32_t)(n) << CRG_XTAL_XTAL32M_START_XTAL32M_CUR_SET_SHIFT)
#define CRG_XTAL_XTAL32M_START_XTAL32M_AMPL_SET_SHIFT (14)  /* Bits 14-16 */
#define CRG_XTAL_XTAL32M_START_XTAL32M_AMPL_SET_MASK (0x7 << CRG_XTAL_XTAL32M_START_XTAL32M_AMPL_SET_SHIFT)
#  define CRG_XTAL_XTAL32M_START_XTAL32M_AMPL_SET(n) ((uint32_t)(n) << CRG_XTAL_XTAL32M_START_XTAL32M_AMPL_SET_SHIFT)
#define CRG_XTAL_XTAL32M_START_XTAL32M_CMP_LVL_SHIFT (17)   /* Bits 17-18 */
#define CRG_XTAL_XTAL32M_START_XTAL32M_CMP_LVL_MASK (0x3 << CRG_XTAL_XTAL32M_START_XTAL32M_CMP_LVL_SHIFT)
#  define CRG_XTAL_XTAL32M_START_XTAL32M_CMP_LVL(n) ((uint32_t)(n) << CRG_XTAL_XTAL32M_START_XTAL32M_CMP_LVL_SHIFT)
#define CRG_XTAL_XTAL32M_START_XTAL32M_CMP_BLANK_SHIFT (19) /* Bits 19-21 */
#define CRG_XTAL_XTAL32M_START_XTAL32M_CMP_BLANK_MASK (0x7 << CRG_XTAL_XTAL32M_START_XTAL32M_CMP_BLANK_SHIFT)
#  define CRG_XTAL_XTAL32M_START_XTAL32M_CMP_BLANK(n) ((uint32_t)(n) << CRG_XTAL_XTAL32M_START_XTAL32M_CMP_BLANK_SHIFT)
#define CRG_XTAL_XTAL32M_START_XTAL32M_TIMEOUT_SHIFT (22)   /* Bits 22-28 */
#define CRG_XTAL_XTAL32M_START_XTAL32M_TIMEOUT_MASK (0x7f << CRG_XTAL_XTAL32M_START_XTAL32M_TIMEOUT_SHIFT)
#  define CRG_XTAL_XTAL32M_START_XTAL32M_TIMEOUT(n) ((uint32_t)(n) << CRG_XTAL_XTAL32M_START_XTAL32M_TIMEOUT_SHIFT)

/* XTAL32M_SETTLE register */

#define CRG_XTAL_XTAL32M_SETTLE_XTAL32M_TRIM_SHIFT (0)       /* Bits 0-9 */
#define CRG_XTAL_XTAL32M_SETTLE_XTAL32M_TRIM_MASK (0x3ff << CRG_XTAL_XTAL32M_SETTLE_XTAL32M_TRIM_SHIFT)
#  define CRG_XTAL_XTAL32M_SETTLE_XTAL32M_TRIM(n) ((uint32_t)(n) << CRG_XTAL_XTAL32M_SETTLE_XTAL32M_TRIM_SHIFT)
#define CRG_XTAL_XTAL32M_SETTLE_XTAL32M_CUR_SET_SHIFT (10)   /* Bits 10-13 */
#define CRG_XTAL_XTAL32M_SETTLE_XTAL32M_CUR_SET_MASK (0xf << CRG_XTAL_XTAL32M_SETTLE_XTAL32M_CUR_SET_SHIFT)
#  define CRG_XTAL_XTAL32M_SETTLE_XTAL32M_CUR_SET(n) ((uint32_t)(n) << CRG_XTAL_XTAL32M_SETTLE_XTAL32M_CUR_SET_SHIFT)
#define CRG_XTAL_XTAL32M_SETTLE_XTAL32M_AMPL_SET_SHIFT (14)  /* Bits 14-16 */
#define CRG_XTAL_XTAL32M_SETTLE_XTAL32M_AMPL_SET_MASK (0x7 << CRG_XTAL_XTAL32M_SETTLE_XTAL32M_AMPL_SET_SHIFT)
#  define CRG_XTAL_XTAL32M_SETTLE_XTAL32M_AMPL_SET(n) ((uint32_t)(n) << CRG_XTAL_XTAL32M_SETTLE_XTAL32M_AMPL_SET_SHIFT)
#define CRG_XTAL_XTAL32M_SETTLE_XTAL32M_CMP_LVL_SHIFT (17)   /* Bits 17-18 */
#define CRG_XTAL_XTAL32M_SETTLE_XTAL32M_CMP_LVL_MASK (0x3 << CRG_XTAL_XTAL32M_SETTLE_XTAL32M_CMP_LVL_SHIFT)
#  define CRG_XTAL_XTAL32M_SETTLE_XTAL32M_CMP_LVL(n) ((uint32_t)(n) << CRG_XTAL_XTAL32M_SETTLE_XTAL32M_CMP_LVL_SHIFT)
#define CRG_XTAL_XTAL32M_SETTLE_XTAL32M_CMP_BLANK_SHIFT (19) /* Bits 19-21 */
#define CRG_XTAL_XTAL32M_SETTLE_XTAL32M_CMP_BLANK_MASK (0x7 << CRG_XTAL_XTAL32M_SETTLE_XTAL32M_CMP_BLANK_SHIFT)
#  define CRG_XTAL_XTAL32M_SETTLE_XTAL32M_CMP_BLANK(n) ((uint32_t)(n) << CRG_XTAL_XTAL32M_SETTLE_XTAL32M_CMP_BLANK_SHIFT)
#define CRG_XTAL_XTAL32M_SETTLE_XTAL32M_TIMEOUT_SHIFT (22)   /* Bits 22-28 */
#define CRG_XTAL_XTAL32M_SETTLE_XTAL32M_TIMEOUT_MASK (0x7f << CRG_XTAL_XTAL32M_SETTLE_XTAL32M_TIMEOUT_SHIFT)
#  define CRG_XTAL_XTAL32M_SETTLE_XTAL32M_TIMEOUT(n) ((uint32_t)(n) << CRG_XTAL_XTAL32M_SETTLE_XTAL32M_TIMEOUT_SHIFT)

/* XTAL32M_TRIM register */

#define CRG_XTAL_XTAL32M_TRIM_XTAL32M_TRIM_SHIFT (0)        /* Bits 0-9 */
#define CRG_XTAL_XTAL32M_TRIM_XTAL32M_TRIM_MASK (0x3ff << CRG_XTAL_XTAL32M_TRIM_XTAL32M_TRIM_SHIFT)
#  define CRG_XTAL_XTAL32M_TRIM_XTAL32M_TRIM(n) ((uint32_t)(n) << CRG_XTAL_XTAL32M_TRIM_XTAL32M_TRIM_SHIFT)
#define CRG_XTAL_XTAL32M_TRIM_XTAL32M_CUR_SET_SHIFT (10)    /* Bits 10-13 */
#define CRG_XTAL_XTAL32M_TRIM_XTAL32M_CUR_SET_MASK (0xf << CRG_XTAL_XTAL32M_TRIM_XTAL32M_CUR_SET_SHIFT)
#  define CRG_XTAL_XTAL32M_TRIM_XTAL32M_CUR_SET(n) ((uint32_t)(n) << CRG_XTAL_XTAL32M_TRIM_XTAL32M_CUR_SET_SHIFT)
#define CRG_XTAL_XTAL32M_TRIM_XTAL32M_AMPL_SET_SHIFT (14)   /* Bits 14-16 */
#define CRG_XTAL_XTAL32M_TRIM_XTAL32M_AMPL_SET_MASK (0x7 << CRG_XTAL_XTAL32M_TRIM_XTAL32M_AMPL_SET_SHIFT)
#  define CRG_XTAL_XTAL32M_TRIM_XTAL32M_AMPL_SET(n) ((uint32_t)(n) << CRG_XTAL_XTAL32M_TRIM_XTAL32M_AMPL_SET_SHIFT)
#define CRG_XTAL_XTAL32M_TRIM_XTAL32M_CMP_LVL_SHIFT (17)    /* Bits 17-18 */
#define CRG_XTAL_XTAL32M_TRIM_XTAL32M_CMP_LVL_MASK (0x3 << CRG_XTAL_XTAL32M_TRIM_XTAL32M_CMP_LVL_SHIFT)
#  define CRG_XTAL_XTAL32M_TRIM_XTAL32M_CMP_LVL(n) ((uint32_t)(n) << CRG_XTAL_XTAL32M_TRIM_XTAL32M_CMP_LVL_SHIFT)
#define CRG_XTAL_XTAL32M_TRIM_XTAL32M_BOOST_TRIM_SHIFT (19) /* Bits 19-24 */
#define CRG_XTAL_XTAL32M_TRIM_XTAL32M_BOOST_TRIM_MASK (0x3f << CRG_XTAL_XTAL32M_TRIM_XTAL32M_BOOST_TRIM_SHIFT)
#  define CRG_XTAL_XTAL32M_TRIM_XTAL32M_BOOST_TRIM(n) ((uint32_t)(n) << CRG_XTAL_XTAL32M_TRIM_XTAL32M_BOOST_TRIM_SHIFT)

/* XTAL32M_CAP_MEAS register */

#define CRG_XTAL_XTAL32M_CAP_MEAS_XTAL32M_CAP_SELECT_SHIFT (0) /* Bits 0-2 */
#define CRG_XTAL_XTAL32M_CAP_MEAS_XTAL32M_CAP_SELECT_MASK (0x7 << CRG_XTAL_XTAL32M_CAP_MEAS_XTAL32M_CAP_SELECT_SHIFT)
#  define CRG_XTAL_XTAL32M_CAP_MEAS_XTAL32M_CAP_SELECT(n) ((uint32_t)(n) << CRG_XTAL_XTAL32M_CAP_MEAS_XTAL32M_CAP_SELECT_SHIFT)
#define CRG_XTAL_XTAL32M_CAP_MEAS_XTAL32M_MEAS_CUR_SHIFT (3)   /* Bits 3-4 */
#define CRG_XTAL_XTAL32M_CAP_MEAS_XTAL32M_MEAS_CUR_MASK (0x3 << CRG_XTAL_XTAL32M_CAP_MEAS_XTAL32M_MEAS_CUR_SHIFT)
#  define CRG_XTAL_XTAL32M_CAP_MEAS_XTAL32M_MEAS_CUR(n) ((uint32_t)(n) << CRG_XTAL_XTAL32M_CAP_MEAS_XTAL32M_MEAS_CUR_SHIFT)
#define CRG_XTAL_XTAL32M_CAP_MEAS_XTAL32M_MEAS_START (1 << 5)  /* Bit 5 */
#define CRG_XTAL_XTAL32M_CAP_MEAS_XTAL32M_MEAS_TIME_SHIFT (6)  /* Bits 6-8 */
#define CRG_XTAL_XTAL32M_CAP_MEAS_XTAL32M_MEAS_TIME_MASK (0x7 << CRG_XTAL_XTAL32M_CAP_MEAS_XTAL32M_MEAS_TIME_SHIFT)
#  define CRG_XTAL_XTAL32M_CAP_MEAS_XTAL32M_MEAS_TIME(n) ((uint32_t)(n) << CRG_XTAL_XTAL32M_CAP_MEAS_XTAL32M_MEAS_TIME_SHIFT)

/* XTAL32M_FSM register */

#define CRG_XTAL_XTAL32M_FSM_XTAL32M_CUR_MODE (1 << 0)         /* Bit 0 */
#define CRG_XTAL_XTAL32M_FSM_XTAL32M_TRIM_MODE (1 << 1)        /* Bit 1 */
#define CRG_XTAL_XTAL32M_FSM_XTAL32M_CMP_MODE (1 << 2)         /* Bit 2 */
#define CRG_XTAL_XTAL32M_FSM_XTAL32M_FSM_FORCE_IDLE (1 << 3)   /* Bit 3 */
#define CRG_XTAL_XTAL32M_FSM_XTAL32M_FSM_APPLY_CONFIG (1 << 4) /* Bit 4 */
#define CRG_XTAL_XTAL32M_FSM_XTAL32M_BOOST_MODE (1 << 5)       /* Bit 5 */

/* XTAL32M_CTRL register */

#define CRG_XTAL_XTAL32M_CTRL_XTAL32M_BIAS_SAH_SHIFT (0)     /* Bits 0-1 */
#define CRG_XTAL_XTAL32M_CTRL_XTAL32M_BIAS_SAH_MASK (0x3 << CRG_XTAL_XTAL32M_CTRL_XTAL32M_BIAS_SAH_SHIFT)
#  define CRG_XTAL_XTAL32M_CTRL_XTAL32M_BIAS_SAH(n) ((uint32_t)(n) << CRG_XTAL_XTAL32M_CTRL_XTAL32M_BIAS_SAH_SHIFT)
#define CRG_XTAL_XTAL32M_CTRL_XTAL32M_AMPREG_SAH_SHIFT (2)   /* Bits 2-3 */
#define CRG_XTAL_XTAL32M_CTRL_XTAL32M_AMPREG_SAH_MASK (0x3 << CRG_XTAL_XTAL32M_CTRL_XTAL32M_AMPREG_SAH_SHIFT)
#  define CRG_XTAL_XTAL32M_CTRL_XTAL32M_AMPREG_SAH(n) ((uint32_t)(n) << CRG_XTAL_XTAL32M_CTRL_XTAL32M_AMPREG_SAH_SHIFT)
#define CRG_XTAL_XTAL32M_CTRL_XTAL32M_LDO_SAH_SHIFT (4)      /* Bits 4-5 */
#define CRG_XTAL_XTAL32M_CTRL_XTAL32M_LDO_SAH_MASK (0x3 << CRG_XTAL_XTAL32M_CTRL_XTAL32M_LDO_SAH_SHIFT)
#  define CRG_XTAL_XTAL32M_CTRL_XTAL32M_LDO_SAH(n) ((uint32_t)(n) << CRG_XTAL_XTAL32M_CTRL_XTAL32M_LDO_SAH_SHIFT)
#define CRG_XTAL_XTAL32M_CTRL_XTAL32M_BIASPROT_SHIFT (6)     /* Bits 6-7 */
#define CRG_XTAL_XTAL32M_CTRL_XTAL32M_BIASPROT_MASK (0x3 << CRG_XTAL_XTAL32M_CTRL_XTAL32M_BIASPROT_SHIFT)
#  define CRG_XTAL_XTAL32M_CTRL_XTAL32M_BIASPROT(n) ((uint32_t)(n) << CRG_XTAL_XTAL32M_CTRL_XTAL32M_BIASPROT_SHIFT)
#define CRG_XTAL_XTAL32M_CTRL_XTAL32M_ENABLE (1 << 8)        /* Bit 8 */
#define CRG_XTAL_XTAL32M_CTRL_XTAL32M_DRIVE_CYCLES_SHIFT (9) /* Bits 9-11 */
#define CRG_XTAL_XTAL32M_CTRL_XTAL32M_DRIVE_CYCLES_MASK (0x7 << CRG_XTAL_XTAL32M_CTRL_XTAL32M_DRIVE_CYCLES_SHIFT)
#  define CRG_XTAL_XTAL32M_CTRL_XTAL32M_DRIVE_CYCLES(n) ((uint32_t)(n) << CRG_XTAL_XTAL32M_CTRL_XTAL32M_DRIVE_CYCLES_SHIFT)

/* XTAL32M_IRQ_CTRL register */

#define CRG_XTAL_XTAL32M_IRQ_CTRL_XTAL32M_IRQ_CNT_SHIFT (0)       /* Bits 0-7 */
#define CRG_XTAL_XTAL32M_IRQ_CTRL_XTAL32M_IRQ_CNT_MASK (0xff << CRG_XTAL_XTAL32M_IRQ_CTRL_XTAL32M_IRQ_CNT_SHIFT)
#  define CRG_XTAL_XTAL32M_IRQ_CTRL_XTAL32M_IRQ_CNT(n) ((uint32_t)(n) << CRG_XTAL_XTAL32M_IRQ_CTRL_XTAL32M_IRQ_CNT_SHIFT)
#define CRG_XTAL_XTAL32M_IRQ_CTRL_XTAL32M_IRQ_CLK (1 << 8)        /* Bit 8 */
#define CRG_XTAL_XTAL32M_IRQ_CTRL_XTAL32M_IRQ_ENABLE (1 << 9)     /* Bit 9 */
#define CRG_XTAL_XTAL32M_IRQ_CTRL_XTAL32M_IRQ_CAP_CTRL_SHIFT (10) /* Bits 10-11 */
#define CRG_XTAL_XTAL32M_IRQ_CTRL_XTAL32M_IRQ_CAP_CTRL_MASK (0x3 << CRG_XTAL_XTAL32M_IRQ_CTRL_XTAL32M_IRQ_CAP_CTRL_SHIFT)
#  define CRG_XTAL_XTAL32M_IRQ_CTRL_XTAL32M_IRQ_CAP_CTRL(n) ((uint32_t)(n) << CRG_XTAL_XTAL32M_IRQ_CTRL_XTAL32M_IRQ_CAP_CTRL_SHIFT)

/* XTAL32M_STAT0 register */

#define CRG_XTAL_XTAL32M_STAT0_XTAL32M_READY (1 << 0)          /* Bit 0 */
#define CRG_XTAL_XTAL32M_STAT0_XTAL32M_CMP_OUT_HOLD_SHIFT (1)  /* Bits 1-2 */
#define CRG_XTAL_XTAL32M_STAT0_XTAL32M_CMP_OUT_HOLD_MASK (0x3 << CRG_XTAL_XTAL32M_STAT0_XTAL32M_CMP_OUT_HOLD_SHIFT)
#  define CRG_XTAL_XTAL32M_STAT0_XTAL32M_CMP_OUT_HOLD(n) ((uint32_t)(n) << CRG_XTAL_XTAL32M_STAT0_XTAL32M_CMP_OUT_HOLD_SHIFT)
#define CRG_XTAL_XTAL32M_STAT0_XTAL32M_STATE_SHIFT (3)         /* Bits 3-6 */
#define CRG_XTAL_XTAL32M_STAT0_XTAL32M_STATE_MASK (0xf << CRG_XTAL_XTAL32M_STAT0_XTAL32M_STATE_SHIFT)
#  define CRG_XTAL_XTAL32M_STAT0_XTAL32M_STATE(n) ((uint32_t)(n) << CRG_XTAL_XTAL32M_STAT0_XTAL32M_STATE_SHIFT)
#define CRG_XTAL_XTAL32M_STAT0_XTAL32M_CMP_OUT_SHIFT (7)       /* Bits 7-8 */
#define CRG_XTAL_XTAL32M_STAT0_XTAL32M_CMP_OUT_MASK (0x3 << CRG_XTAL_XTAL32M_STAT0_XTAL32M_CMP_OUT_SHIFT)
#  define CRG_XTAL_XTAL32M_STAT0_XTAL32M_CMP_OUT(n) ((uint32_t)(n) << CRG_XTAL_XTAL32M_STAT0_XTAL32M_CMP_OUT_SHIFT)
#define CRG_XTAL_XTAL32M_STAT0_XTAL32M_LDO_OK (1 << 9)         /* Bit 9 */
#define CRG_XTAL_XTAL32M_STAT0_XTAL32M_CUR_SET_STAT_SHIFT (10) /* Bits 10-13 */
#define CRG_XTAL_XTAL32M_STAT0_XTAL32M_CUR_SET_STAT_MASK (0xf << CRG_XTAL_XTAL32M_STAT0_XTAL32M_CUR_SET_STAT_SHIFT)
#  define CRG_XTAL_XTAL32M_STAT0_XTAL32M_CUR_SET_STAT(n) ((uint32_t)(n) << CRG_XTAL_XTAL32M_STAT0_XTAL32M_CUR_SET_STAT_SHIFT)
#define CRG_XTAL_XTAL32M_STAT0_XTAL32M_TRIM_VAL_SHIFT (14)     /* Bits 14-23 */
#define CRG_XTAL_XTAL32M_STAT0_XTAL32M_TRIM_VAL_MASK (0x3ff << CRG_XTAL_XTAL32M_STAT0_XTAL32M_TRIM_VAL_SHIFT)
#  define CRG_XTAL_XTAL32M_STAT0_XTAL32M_TRIM_VAL(n) ((uint32_t)(n) << CRG_XTAL_XTAL32M_STAT0_XTAL32M_TRIM_VAL_SHIFT)
#define CRG_XTAL_XTAL32M_STAT0_XTAL32M_AMPL_TRIM_SHIFT (24)    /* Bits 24-26 */
#define CRG_XTAL_XTAL32M_STAT0_XTAL32M_AMPL_TRIM_MASK (0x7 << CRG_XTAL_XTAL32M_STAT0_XTAL32M_AMPL_TRIM_SHIFT)
#  define CRG_XTAL_XTAL32M_STAT0_XTAL32M_AMPL_TRIM(n) ((uint32_t)(n) << CRG_XTAL_XTAL32M_STAT0_XTAL32M_AMPL_TRIM_SHIFT)
#define CRG_XTAL_XTAL32M_STAT0_XTAL32M_CMP_LVL_STAT_SHIFT (27) /* Bits 27-28 */
#define CRG_XTAL_XTAL32M_STAT0_XTAL32M_CMP_LVL_STAT_MASK (0x3 << CRG_XTAL_XTAL32M_STAT0_XTAL32M_CMP_LVL_STAT_SHIFT)
#  define CRG_XTAL_XTAL32M_STAT0_XTAL32M_CMP_LVL_STAT(n) ((uint32_t)(n) << CRG_XTAL_XTAL32M_STAT0_XTAL32M_CMP_LVL_STAT_SHIFT)
#define CRG_XTAL_XTAL32M_STAT0_XTAL32M_OVERLOAD (1 << 29)      /* Bit 29 */

/* XTAL32M_IRQ_STAT register */

#define CRG_XTAL_XTAL32M_IRQ_STAT_XTAL32M_IRQ_COUNT_STAT_SHIFT (0) /* Bits 0-7 */
#define CRG_XTAL_XTAL32M_IRQ_STAT_XTAL32M_IRQ_COUNT_STAT_MASK (0xff << CRG_XTAL_XTAL32M_IRQ_STAT_XTAL32M_IRQ_COUNT_STAT_SHIFT)
#  define CRG_XTAL_XTAL32M_IRQ_STAT_XTAL32M_IRQ_COUNT_STAT(n) ((uint32_t)(n) << CRG_XTAL_XTAL32M_IRQ_STAT_XTAL32M_IRQ_COUNT_STAT_SHIFT)
#define CRG_XTAL_XTAL32M_IRQ_STAT_XTAL32M_IRQ_COUNT_CAP_SHIFT (8)  /* Bits 8-15 */
#define CRG_XTAL_XTAL32M_IRQ_STAT_XTAL32M_IRQ_COUNT_CAP_MASK (0xff << CRG_XTAL_XTAL32M_IRQ_STAT_XTAL32M_IRQ_COUNT_CAP_SHIFT)
#  define CRG_XTAL_XTAL32M_IRQ_STAT_XTAL32M_IRQ_COUNT_CAP(n) ((uint32_t)(n) << CRG_XTAL_XTAL32M_IRQ_STAT_XTAL32M_IRQ_COUNT_CAP_SHIFT)

/* PLL_SYS_CTRL1 register */

#define CRG_XTAL_PLL_SYS_CTRL1_PLL_EN (1 << 0)               /* Bit 0 */
#define CRG_XTAL_PLL_SYS_CTRL1_PLL_RST_N (1 << 1)            /* Bit 1 */
#define CRG_XTAL_PLL_SYS_CTRL1_LDO_PLL_ENABLE (1 << 2)       /* Bit 2 */
#define CRG_XTAL_PLL_SYS_CTRL1_LDO_PLL_VREF_HOLD (1 << 3)    /* Bit 3 */
#define CRG_XTAL_PLL_SYS_CTRL1_PLL_N_DIV_SHIFT (4)           /* Bits 4-10 */
#define CRG_XTAL_PLL_SYS_CTRL1_PLL_N_DIV_MASK (0x7f << CRG_XTAL_PLL_SYS_CTRL1_PLL_N_DIV_SHIFT)
#  define CRG_XTAL_PLL_SYS_CTRL1_PLL_N_DIV(n) ((uint32_t)(n) << CRG_XTAL_PLL_SYS_CTRL1_PLL_N_DIV_SHIFT)
#define CRG_XTAL_PLL_SYS_CTRL1_PLL_PRE_DIV (1 << 11)         /* Bit 11 */
#define CRG_XTAL_PLL_SYS_CTRL1_PLL_SEL_MIN_CUR_INT (1 << 14) /* Bit 14 */
#define CRG_XTAL_PLL_SYS_CTRL1_PLL_OUT_DIV (1 << 15)         /* Bit 15 */

/* PLL_SYS_CTRL2 register */

#define CRG_XTAL_PLL_SYS_CTRL2_PLL_RECALIB (1 << 15) /* Bit 15 */

/* PLL_SYS_CTRL3 register */

#define CRG_XTAL_PLL_SYS_CTRL3_PLL_MIN_CURRENT_SHIFT (1) /* Bits 1-6 */
#define CRG_XTAL_PLL_SYS_CTRL3_PLL_MIN_CURRENT_MASK (0x3f << CRG_XTAL_PLL_SYS_CTRL3_PLL_MIN_CURRENT_SHIFT)
#  define CRG_XTAL_PLL_SYS_CTRL3_PLL_MIN_CURRENT(n) ((uint32_t)(n) << CRG_XTAL_PLL_SYS_CTRL3_PLL_MIN_CURRENT_SHIFT)

/* PLL_SYS_STATUS register */

#define CRG_XTAL_PLL_SYS_STATUS_PLL_LOCK_FINE (1 << 0)        /* Bit 0 */
#define CRG_XTAL_PLL_SYS_STATUS_PLL_BEST_MIN_CUR_SHIFT (5)    /* Bits 5-10 */
#define CRG_XTAL_PLL_SYS_STATUS_PLL_BEST_MIN_CUR_MASK (0x3f << CRG_XTAL_PLL_SYS_STATUS_PLL_BEST_MIN_CUR_SHIFT)
#  define CRG_XTAL_PLL_SYS_STATUS_PLL_BEST_MIN_CUR(n) ((uint32_t)(n) << CRG_XTAL_PLL_SYS_STATUS_PLL_BEST_MIN_CUR_SHIFT)
#define CRG_XTAL_PLL_SYS_STATUS_PLL_CALIBRATION_END (1 << 11) /* Bit 11 */
#define CRG_XTAL_PLL_SYS_STATUS_LDO_PLL_OK (1 << 15)          /* Bit 15 */

/* PLL_USB_CTRL1 register */

#define CRG_XTAL_PLL_USB_CTRL1_PLL_EN (1 << 0)               /* Bit 0 */
#define CRG_XTAL_PLL_USB_CTRL1_PLL_RST_N (1 << 1)            /* Bit 1 */
#define CRG_XTAL_PLL_USB_CTRL1_LDO_PLL_ENABLE (1 << 2)       /* Bit 2 */
#define CRG_XTAL_PLL_USB_CTRL1_LDO_PLL_VREF_HOLD (1 << 3)    /* Bit 3 */
#define CRG_XTAL_PLL_USB_CTRL1_PLL_N_DIV_SHIFT (4)           /* Bits 4-10 */
#define CRG_XTAL_PLL_USB_CTRL1_PLL_N_DIV_MASK (0x7f << CRG_XTAL_PLL_USB_CTRL1_PLL_N_DIV_SHIFT)
#  define CRG_XTAL_PLL_USB_CTRL1_PLL_N_DIV(n) ((uint32_t)(n) << CRG_XTAL_PLL_USB_CTRL1_PLL_N_DIV_SHIFT)
#define CRG_XTAL_PLL_USB_CTRL1_PLL_PRE_DIV (1 << 11)         /* Bit 11 */
#define CRG_XTAL_PLL_USB_CTRL1_PLL_SEL_MIN_CUR_INT (1 << 14) /* Bit 14 */
#define CRG_XTAL_PLL_USB_CTRL1_PLL_OUT_DIV (1 << 15)         /* Bit 15 */

/* PLL_USB_CTRL2 register */

#define CRG_XTAL_PLL_USB_CTRL2_PLL_RECALIB (1 << 15) /* Bit 15 */

/* PLL_USB_CTRL3 register */

#define CRG_XTAL_PLL_USB_CTRL3_PLL_MIN_CURRENT_SHIFT (1) /* Bits 1-6 */
#define CRG_XTAL_PLL_USB_CTRL3_PLL_MIN_CURRENT_MASK (0x3f << CRG_XTAL_PLL_USB_CTRL3_PLL_MIN_CURRENT_SHIFT)
#  define CRG_XTAL_PLL_USB_CTRL3_PLL_MIN_CURRENT(n) ((uint32_t)(n) << CRG_XTAL_PLL_USB_CTRL3_PLL_MIN_CURRENT_SHIFT)

/* PLL_USB_STATUS register */

#define CRG_XTAL_PLL_USB_STATUS_PLL_LOCK_FINE (1 << 0)        /* Bit 0 */
#define CRG_XTAL_PLL_USB_STATUS_PLL_BEST_MIN_CUR_SHIFT (5)    /* Bits 5-10 */
#define CRG_XTAL_PLL_USB_STATUS_PLL_BEST_MIN_CUR_MASK (0x3f << CRG_XTAL_PLL_USB_STATUS_PLL_BEST_MIN_CUR_SHIFT)
#  define CRG_XTAL_PLL_USB_STATUS_PLL_BEST_MIN_CUR(n) ((uint32_t)(n) << CRG_XTAL_PLL_USB_STATUS_PLL_BEST_MIN_CUR_SHIFT)
#define CRG_XTAL_PLL_USB_STATUS_PLL_CALIBRATION_END (1 << 11) /* Bit 11 */
#define CRG_XTAL_PLL_USB_STATUS_LDO_PLL_OK (1 << 15)          /* Bit 15 */

/* SYS_IRQ_CTRL register */

#define CRG_XTAL_SYS_IRQ_CTRL_SYS2CMAC_IRQ_BIT (1 << 0) /* Bit 0 */
#define CRG_XTAL_SYS_IRQ_CTRL_SYS2SNC_IRQ_BIT (1 << 1)  /* Bit 1 */
#define CRG_XTAL_SYS_IRQ_CTRL_SNC2CMAC_IRQ_BIT (1 << 2) /* Bit 2 */
#define CRG_XTAL_SYS_IRQ_CTRL_SNC2SYS_IRQ_BIT (1 << 3)  /* Bit 3 */
#define CRG_XTAL_SYS_IRQ_CTRL_CMAC2SYS_IRQ_BIT (1 << 4) /* Bit 4 */
#define CRG_XTAL_SYS_IRQ_CTRL_CMAC2SNC_IRQ_BIT (1 << 5) /* Bit 5 */

/* SET_SYS_IRQ_CTRL register */

#define CRG_XTAL_SET_SYS_IRQ_CTRL_SYS2CMAC_IRQ_BIT (1 << 0) /* Bit 0 */
#define CRG_XTAL_SET_SYS_IRQ_CTRL_SYS2SNC_IRQ_BIT (1 << 1)  /* Bit 1 */
#define CRG_XTAL_SET_SYS_IRQ_CTRL_SNC2CMAC_IRQ_BIT (1 << 2) /* Bit 2 */
#define CRG_XTAL_SET_SYS_IRQ_CTRL_SNC2SYS_IRQ_BIT (1 << 3)  /* Bit 3 */
#define CRG_XTAL_SET_SYS_IRQ_CTRL_CMAC2SYS_IRQ_BIT (1 << 4) /* Bit 4 */
#define CRG_XTAL_SET_SYS_IRQ_CTRL_CMAC2SNC_IRQ_BIT (1 << 5) /* Bit 5 */

/* RESET_SYS_IRQ_CTRL register */

#define CRG_XTAL_RESET_SYS_IRQ_CTRL_SYS2CMAC_IRQ_BIT (1 << 0) /* Bit 0 */
#define CRG_XTAL_RESET_SYS_IRQ_CTRL_SYS2SNC_IRQ_BIT (1 << 1)  /* Bit 1 */
#define CRG_XTAL_RESET_SYS_IRQ_CTRL_SNC2CMAC_IRQ_BIT (1 << 2) /* Bit 2 */
#define CRG_XTAL_RESET_SYS_IRQ_CTRL_SNC2SYS_IRQ_BIT (1 << 3)  /* Bit 3 */
#define CRG_XTAL_RESET_SYS_IRQ_CTRL_CMAC2SYS_IRQ_BIT (1 << 4) /* Bit 4 */
#define CRG_XTAL_RESET_SYS_IRQ_CTRL_CMAC2SNC_IRQ_BIT (1 << 5) /* Bit 5 */

#endif /* __ARCH_ARM_SRC_DA1470X_HARDWARE_DA1470X_CRG_XTAL_H */
