/****************************************************************************
 * arch/arm/src/da1470x/hardware/da1470x_charger.h
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.  The
 * ASF licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 ****************************************************************************/

/* Generated from the Renesas CMSIS device header DA1470x-00.h (SDK
 * 10.2.6.49).  Do not edit by hand; regenerate with tools/genhdr.py.
 */

#ifndef __ARCH_ARM_SRC_DA1470X_HARDWARE_DA1470X_CHARGER_H
#define __ARCH_ARM_SRC_DA1470X_HARDWARE_DA1470X_CHARGER_H

/****************************************************************************
 * Included Files
 ****************************************************************************/

#include <nuttx/config.h>
#include "da1470x_memorymap.h"

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

/* Register Offsets *********************************************************/

#define DA1470X_CHARGER_CTRL_OFFSET 0x0000               /* Charger main control register */
#define DA1470X_CHARGER_STATUS_OFFSET 0x0008             /* Charger main status register */
#define DA1470X_CHARGER_VOLTAGE_PARAM_OFFSET 0x000c      /* Charger voltage settings register */
#define DA1470X_CHARGER_CURRENT_PARAM_OFFSET 0x0010      /* Charger current settings register */
#define DA1470X_CHARGER_VOLTAGE_STATUS_OFFSET 0x0014     /* Charger voltage status register */
#define DA1470X_CHARGER_CURRENT_STATUS_OFFSET 0x0018     /* Charger current status register */
#define DA1470X_CHARGER_TEMPSET_PARAM_OFFSET 0x001c      /* Charger battery temperature settings reg */
#define DA1470X_CHARGER_TEMPSET2_PARAM_OFFSET 0x0020     /* Charger battery temperature settings reg */
#define DA1470X_CHARGER_PRE_CHARGE_TIMER_OFFSET 0x0024   /* Maximum pre-charge time limit register */
#define DA1470X_CHARGER_CC_CHARGE_TIMER_OFFSET 0x0028    /* Maximum CC-charge time limit register */
#define DA1470X_CHARGER_CV_CHARGE_TIMER_OFFSET 0x002c    /* Maximum CV-charge time limit register */
#define DA1470X_CHARGER_TOTAL_CHARGE_TIMER_OFFSET 0x0030 /* Maximum total charge time limit register */
#define DA1470X_CHARGER_JEITA_V_CHARGE_OFFSET 0x0034     /* JEITA-compliant Charge voltage settings */
#define DA1470X_CHARGER_JEITA_V_PRECHARGE_OFFSET 0x0038  /* JEITA-compliant Pre-Charge voltage setti */
#define DA1470X_CHARGER_JEITA_V_REPLENISH_OFFSET 0x003c  /* JEITA-compliant Replenish settings regis */
#define DA1470X_CHARGER_JEITA_V_OVP_OFFSET 0x0040        /* JEITA-compliant OVP settings register */
#define DA1470X_CHARGER_JEITA_CURRENT_OFFSET 0x0044      /* JEITA-compliant current settings registe */
#define DA1470X_CHARGER_JEITA_CURRENT2_OFFSET 0x0048     /* JEITA-compliant current settings registe */
#define DA1470X_CHARGER_VBAT_COMP_TIMER_OFFSET 0x004c    /* Main Vbat comparator timer register */
#define DA1470X_CHARGER_VOVP_COMP_TIMER_OFFSET 0x0050    /* Vbat OVP comparator timer register */
#define DA1470X_CHARGER_TDIE_COMP_TIMER_OFFSET 0x0054    /* Die temperature comparator timer registe */
#define DA1470X_CHARGER_TBAT_MON_TIMER_OFFSET 0x0058     /* Battery temperature monitor interval tim */
#define DA1470X_CHARGER_TBAT_COMP_TIMER_OFFSET 0x005c    /* Battery temperature (main) comparator ti */
#define DA1470X_CHARGER_THOT_COMP_TIMER_OFFSET 0x0060    /* Battery temperature comparator timer reg */
#define DA1470X_CHARGER_PWR_UP_TIMER_OFFSET 0x0064       /* Charger power-up settling timer register */
#define DA1470X_CHARGER_STATE_IRQ_MASK_OFFSET 0x0068     /* Mask register of Charger FSM IRQs */
#define DA1470X_CHARGER_ERROR_IRQ_MASK_OFFSET 0x006c     /* Mask register of Charger Error IRQs */
#define DA1470X_CHARGER_STATE_IRQ_STATUS_OFFSET 0x0070   /* Status register of Charger FSM IRQs */
#define DA1470X_CHARGER_ERROR_IRQ_STATUS_OFFSET 0x0074   /* Status register of Charger Error IRQs */
#define DA1470X_CHARGER_STATE_IRQ_CLR_OFFSET 0x0078      /* Interrupt clear register of Charger FSM */
#define DA1470X_CHARGER_ERROR_IRQ_CLR_OFFSET 0x007c      /* Interrupt clear register of Charger Erro */
#define DA1470X_CHARGER_LOCK_OFFSET 0x0080               /* Charger HW lock register */
#define DA1470X_CHARGER_SWLOCK_OFFSET 0x0084             /* Charger SW lock register */

/* Register Addresses *******************************************************/

#define DA1470X_CHARGER_CTRL (DA1470X_CHARGER_BASE + DA1470X_CHARGER_CTRL_OFFSET)
#define DA1470X_CHARGER_STATUS (DA1470X_CHARGER_BASE + DA1470X_CHARGER_STATUS_OFFSET)
#define DA1470X_CHARGER_VOLTAGE_PARAM (DA1470X_CHARGER_BASE + DA1470X_CHARGER_VOLTAGE_PARAM_OFFSET)
#define DA1470X_CHARGER_CURRENT_PARAM (DA1470X_CHARGER_BASE + DA1470X_CHARGER_CURRENT_PARAM_OFFSET)
#define DA1470X_CHARGER_VOLTAGE_STATUS (DA1470X_CHARGER_BASE + DA1470X_CHARGER_VOLTAGE_STATUS_OFFSET)
#define DA1470X_CHARGER_CURRENT_STATUS (DA1470X_CHARGER_BASE + DA1470X_CHARGER_CURRENT_STATUS_OFFSET)
#define DA1470X_CHARGER_TEMPSET_PARAM (DA1470X_CHARGER_BASE + DA1470X_CHARGER_TEMPSET_PARAM_OFFSET)
#define DA1470X_CHARGER_TEMPSET2_PARAM (DA1470X_CHARGER_BASE + DA1470X_CHARGER_TEMPSET2_PARAM_OFFSET)
#define DA1470X_CHARGER_PRE_CHARGE_TIMER (DA1470X_CHARGER_BASE + DA1470X_CHARGER_PRE_CHARGE_TIMER_OFFSET)
#define DA1470X_CHARGER_CC_CHARGE_TIMER (DA1470X_CHARGER_BASE + DA1470X_CHARGER_CC_CHARGE_TIMER_OFFSET)
#define DA1470X_CHARGER_CV_CHARGE_TIMER (DA1470X_CHARGER_BASE + DA1470X_CHARGER_CV_CHARGE_TIMER_OFFSET)
#define DA1470X_CHARGER_TOTAL_CHARGE_TIMER (DA1470X_CHARGER_BASE + DA1470X_CHARGER_TOTAL_CHARGE_TIMER_OFFSET)
#define DA1470X_CHARGER_JEITA_V_CHARGE (DA1470X_CHARGER_BASE + DA1470X_CHARGER_JEITA_V_CHARGE_OFFSET)
#define DA1470X_CHARGER_JEITA_V_PRECHARGE (DA1470X_CHARGER_BASE + DA1470X_CHARGER_JEITA_V_PRECHARGE_OFFSET)
#define DA1470X_CHARGER_JEITA_V_REPLENISH (DA1470X_CHARGER_BASE + DA1470X_CHARGER_JEITA_V_REPLENISH_OFFSET)
#define DA1470X_CHARGER_JEITA_V_OVP (DA1470X_CHARGER_BASE + DA1470X_CHARGER_JEITA_V_OVP_OFFSET)
#define DA1470X_CHARGER_JEITA_CURRENT (DA1470X_CHARGER_BASE + DA1470X_CHARGER_JEITA_CURRENT_OFFSET)
#define DA1470X_CHARGER_JEITA_CURRENT2 (DA1470X_CHARGER_BASE + DA1470X_CHARGER_JEITA_CURRENT2_OFFSET)
#define DA1470X_CHARGER_VBAT_COMP_TIMER (DA1470X_CHARGER_BASE + DA1470X_CHARGER_VBAT_COMP_TIMER_OFFSET)
#define DA1470X_CHARGER_VOVP_COMP_TIMER (DA1470X_CHARGER_BASE + DA1470X_CHARGER_VOVP_COMP_TIMER_OFFSET)
#define DA1470X_CHARGER_TDIE_COMP_TIMER (DA1470X_CHARGER_BASE + DA1470X_CHARGER_TDIE_COMP_TIMER_OFFSET)
#define DA1470X_CHARGER_TBAT_MON_TIMER (DA1470X_CHARGER_BASE + DA1470X_CHARGER_TBAT_MON_TIMER_OFFSET)
#define DA1470X_CHARGER_TBAT_COMP_TIMER (DA1470X_CHARGER_BASE + DA1470X_CHARGER_TBAT_COMP_TIMER_OFFSET)
#define DA1470X_CHARGER_THOT_COMP_TIMER (DA1470X_CHARGER_BASE + DA1470X_CHARGER_THOT_COMP_TIMER_OFFSET)
#define DA1470X_CHARGER_PWR_UP_TIMER (DA1470X_CHARGER_BASE + DA1470X_CHARGER_PWR_UP_TIMER_OFFSET)
#define DA1470X_CHARGER_STATE_IRQ_MASK (DA1470X_CHARGER_BASE + DA1470X_CHARGER_STATE_IRQ_MASK_OFFSET)
#define DA1470X_CHARGER_ERROR_IRQ_MASK (DA1470X_CHARGER_BASE + DA1470X_CHARGER_ERROR_IRQ_MASK_OFFSET)
#define DA1470X_CHARGER_STATE_IRQ_STATUS (DA1470X_CHARGER_BASE + DA1470X_CHARGER_STATE_IRQ_STATUS_OFFSET)
#define DA1470X_CHARGER_ERROR_IRQ_STATUS (DA1470X_CHARGER_BASE + DA1470X_CHARGER_ERROR_IRQ_STATUS_OFFSET)
#define DA1470X_CHARGER_STATE_IRQ_CLR (DA1470X_CHARGER_BASE + DA1470X_CHARGER_STATE_IRQ_CLR_OFFSET)
#define DA1470X_CHARGER_ERROR_IRQ_CLR (DA1470X_CHARGER_BASE + DA1470X_CHARGER_ERROR_IRQ_CLR_OFFSET)
#define DA1470X_CHARGER_LOCK (DA1470X_CHARGER_BASE + DA1470X_CHARGER_LOCK_OFFSET)
#define DA1470X_CHARGER_SWLOCK (DA1470X_CHARGER_BASE + DA1470X_CHARGER_SWLOCK_OFFSET)

/* Register Bit-field Definitions *******************************************/

/* CTRL register */

#define CHARGER_CTRL_ENABLE (1 << 0)                     /* Bit 0 */
#define CHARGER_CTRL_CHARGE_START (1 << 1)               /* Bit 1 */
#define CHARGER_CTRL_BYPASS (1 << 2)                     /* Bit 2 */
#define CHARGER_CTRL_RESUME (1 << 3)                     /* Bit 3 */
#define CHARGER_CTRL_TDIE_PROT_ENABLE (1 << 4)           /* Bit 4 */
#define CHARGER_CTRL_TDIE_ERROR_RESUME (1 << 5)          /* Bit 5 */
#define CHARGER_CTRL_TBAT_PROT_ENABLE (1 << 6)           /* Bit 6 */
#define CHARGER_CTRL_NTC_LOW_DISABLE (1 << 7)            /* Bit 7 */
#define CHARGER_CTRL_STOP_CHARGE_TIMERS (1 << 8)         /* Bit 8 */
#define CHARGER_CTRL_CHARGE_TIMERS_HALT_ENABLE (1 << 9)  /* Bit 9 */
#define CHARGER_CTRL_TBAT_MONITOR_MODE_SHIFT (10)        /* Bits 10-11 */
#define CHARGER_CTRL_TBAT_MONITOR_MODE_MASK (0x3 << CHARGER_CTRL_TBAT_MONITOR_MODE_SHIFT)
#  define CHARGER_CTRL_TBAT_MONITOR_MODE(n) ((uint32_t)(n) << CHARGER_CTRL_TBAT_MONITOR_MODE_SHIFT)
#define CHARGER_CTRL_JEITA_SUPPORT_DISABLED (1 << 12)    /* Bit 12 */
#define CHARGER_CTRL_CHARGE_LOOP_HOLD (1 << 13)          /* Bit 13 */
#define CHARGER_CTRL_PRE_CHARGE_MODE (1 << 14)           /* Bit 14 */
#define CHARGER_CTRL_REPLENISH_MODE (1 << 15)            /* Bit 15 */
#define CHARGER_CTRL_EOC_INTERVAL_CHECK_THRES_SHIFT (16) /* Bits 16-21 */
#define CHARGER_CTRL_EOC_INTERVAL_CHECK_THRES_MASK (0x3f << CHARGER_CTRL_EOC_INTERVAL_CHECK_THRES_SHIFT)
#  define CHARGER_CTRL_EOC_INTERVAL_CHECK_THRES(n) ((uint32_t)(n) << CHARGER_CTRL_EOC_INTERVAL_CHECK_THRES_SHIFT)
#define CHARGER_CTRL_EOC_INTERVAL_CHECK_TIMER_SHIFT (22) /* Bits 22-27 */
#define CHARGER_CTRL_EOC_INTERVAL_CHECK_TIMER_MASK (0x3f << CHARGER_CTRL_EOC_INTERVAL_CHECK_TIMER_SHIFT)
#  define CHARGER_CTRL_EOC_INTERVAL_CHECK_TIMER(n) ((uint32_t)(n) << CHARGER_CTRL_EOC_INTERVAL_CHECK_TIMER_SHIFT)
#define CHARGER_CTRL_EOC_TRIGGER (1 << 28)               /* Bit 28 */

/* STATUS register */

#define CHARGER_STATUS_IS_POWERED_UP (1 << 0)             /* Bit 0 */
#define CHARGER_STATUS_CC_MODE (1 << 1)                   /* Bit 1 */
#define CHARGER_STATUS_CV_MODE (1 << 2)                   /* Bit 2 */
#define CHARGER_STATUS_END_OF_CHARGE (1 << 3)             /* Bit 3 */
#define CHARGER_STATUS_MAIN_VBAT_COMP_OUT (1 << 4)        /* Bit 4 */
#define CHARGER_STATUS_VBAT_OVP_COMP_OUT (1 << 5)         /* Bit 5 */
#define CHARGER_STATUS_TDIE_COMP_OUT (1 << 6)             /* Bit 6 */
#define CHARGER_STATUS_TBAT_HOT_COMP_OUT (1 << 7)         /* Bit 7 */
#define CHARGER_STATUS_MAIN_TBAT_COMP_OUT (1 << 8)        /* Bit 8 */
#define CHARGER_STATUS_TBAT_STATUS_SHIFT (9)              /* Bits 9-11 */
#define CHARGER_STATUS_TBAT_STATUS_MASK (0x7 << CHARGER_STATUS_TBAT_STATUS_SHIFT)
#  define CHARGER_STATUS_TBAT_STATUS(n) ((uint32_t)(n) << CHARGER_STATUS_TBAT_STATUS_SHIFT)
#define CHARGER_STATUS_STATE_SHIFT (12)                   /* Bits 12-15 */
#define CHARGER_STATUS_STATE_MASK (0xf << CHARGER_STATUS_STATE_SHIFT)
#  define CHARGER_STATUS_STATE(n) ((uint32_t)(n) << CHARGER_STATUS_STATE_SHIFT)
#define CHARGER_STATUS_JEITA_STATE_SHIFT (16)             /* Bits 16-19 */
#define CHARGER_STATUS_JEITA_STATE_MASK (0xf << CHARGER_STATUS_JEITA_STATE_SHIFT)
#  define CHARGER_STATUS_JEITA_STATE(n) ((uint32_t)(n) << CHARGER_STATUS_JEITA_STATE_SHIFT)
#define CHARGER_STATUS_TDIE_ERROR_DEBOUNCE_CNT_SHIFT (20) /* Bits 20-22 */
#define CHARGER_STATUS_TDIE_ERROR_DEBOUNCE_CNT_MASK (0x7 << CHARGER_STATUS_TDIE_ERROR_DEBOUNCE_CNT_SHIFT)
#  define CHARGER_STATUS_TDIE_ERROR_DEBOUNCE_CNT(n) ((uint32_t)(n) << CHARGER_STATUS_TDIE_ERROR_DEBOUNCE_CNT_SHIFT)
#define CHARGER_STATUS_EOC_EVENTS_DEBOUNCE_CNT_SHIFT (23) /* Bits 23-25 */
#define CHARGER_STATUS_EOC_EVENTS_DEBOUNCE_CNT_MASK (0x7 << CHARGER_STATUS_EOC_EVENTS_DEBOUNCE_CNT_SHIFT)
#  define CHARGER_STATUS_EOC_EVENTS_DEBOUNCE_CNT(n) ((uint32_t)(n) << CHARGER_STATUS_EOC_EVENTS_DEBOUNCE_CNT_SHIFT)
#define CHARGER_STATUS_OVP_EVENTS_DEBOUNCE_CNT_SHIFT (26) /* Bits 26-28 */
#define CHARGER_STATUS_OVP_EVENTS_DEBOUNCE_CNT_MASK (0x7 << CHARGER_STATUS_OVP_EVENTS_DEBOUNCE_CNT_SHIFT)
#  define CHARGER_STATUS_OVP_EVENTS_DEBOUNCE_CNT(n) ((uint32_t)(n) << CHARGER_STATUS_OVP_EVENTS_DEBOUNCE_CNT_SHIFT)

/* VOLTAGE_PARAM register */

#define CHARGER_VOLTAGE_PARAM_V_CHARGE_SHIFT (0)     /* Bits 0-5 */
#define CHARGER_VOLTAGE_PARAM_V_CHARGE_MASK (0x3f << CHARGER_VOLTAGE_PARAM_V_CHARGE_SHIFT)
#  define CHARGER_VOLTAGE_PARAM_V_CHARGE(n) ((uint32_t)(n) << CHARGER_VOLTAGE_PARAM_V_CHARGE_SHIFT)
#define CHARGER_VOLTAGE_PARAM_V_PRECHARGE_SHIFT (6)  /* Bits 6-11 */
#define CHARGER_VOLTAGE_PARAM_V_PRECHARGE_MASK (0x3f << CHARGER_VOLTAGE_PARAM_V_PRECHARGE_SHIFT)
#  define CHARGER_VOLTAGE_PARAM_V_PRECHARGE(n) ((uint32_t)(n) << CHARGER_VOLTAGE_PARAM_V_PRECHARGE_SHIFT)
#define CHARGER_VOLTAGE_PARAM_V_REPLENISH_SHIFT (12) /* Bits 12-17 */
#define CHARGER_VOLTAGE_PARAM_V_REPLENISH_MASK (0x3f << CHARGER_VOLTAGE_PARAM_V_REPLENISH_SHIFT)
#  define CHARGER_VOLTAGE_PARAM_V_REPLENISH(n) ((uint32_t)(n) << CHARGER_VOLTAGE_PARAM_V_REPLENISH_SHIFT)
#define CHARGER_VOLTAGE_PARAM_V_OVP_SHIFT (18)       /* Bits 18-23 */
#define CHARGER_VOLTAGE_PARAM_V_OVP_MASK (0x3f << CHARGER_VOLTAGE_PARAM_V_OVP_SHIFT)
#  define CHARGER_VOLTAGE_PARAM_V_OVP(n) ((uint32_t)(n) << CHARGER_VOLTAGE_PARAM_V_OVP_SHIFT)

/* CURRENT_PARAM register */

#define CHARGER_CURRENT_PARAM_I_CHARGE_SHIFT (0)           /* Bits 0-5 */
#define CHARGER_CURRENT_PARAM_I_CHARGE_MASK (0x3f << CHARGER_CURRENT_PARAM_I_CHARGE_SHIFT)
#  define CHARGER_CURRENT_PARAM_I_CHARGE(n) ((uint32_t)(n) << CHARGER_CURRENT_PARAM_I_CHARGE_SHIFT)
#define CHARGER_CURRENT_PARAM_I_PRECHARGE_SHIFT (6)        /* Bits 6-11 */
#define CHARGER_CURRENT_PARAM_I_PRECHARGE_MASK (0x3f << CHARGER_CURRENT_PARAM_I_PRECHARGE_SHIFT)
#  define CHARGER_CURRENT_PARAM_I_PRECHARGE(n) ((uint32_t)(n) << CHARGER_CURRENT_PARAM_I_PRECHARGE_SHIFT)
#define CHARGER_CURRENT_PARAM_I_END_OF_CHARGE_SHIFT (12)   /* Bits 12-14 */
#define CHARGER_CURRENT_PARAM_I_END_OF_CHARGE_MASK (0x7 << CHARGER_CURRENT_PARAM_I_END_OF_CHARGE_SHIFT)
#  define CHARGER_CURRENT_PARAM_I_END_OF_CHARGE(n) ((uint32_t)(n) << CHARGER_CURRENT_PARAM_I_END_OF_CHARGE_SHIFT)
#define CHARGER_CURRENT_PARAM_I_EOC_DOUBLE_RANGE (1 << 15) /* Bit 15 */

/* VOLTAGE_STATUS register */

#define CHARGER_VOLTAGE_STATUS_V_CHARGE_SET_SHIFT (0)     /* Bits 0-5 */
#define CHARGER_VOLTAGE_STATUS_V_CHARGE_SET_MASK (0x3f << CHARGER_VOLTAGE_STATUS_V_CHARGE_SET_SHIFT)
#  define CHARGER_VOLTAGE_STATUS_V_CHARGE_SET(n) ((uint32_t)(n) << CHARGER_VOLTAGE_STATUS_V_CHARGE_SET_SHIFT)
#define CHARGER_VOLTAGE_STATUS_V_PRECHARGE_SET_SHIFT (6)  /* Bits 6-11 */
#define CHARGER_VOLTAGE_STATUS_V_PRECHARGE_SET_MASK (0x3f << CHARGER_VOLTAGE_STATUS_V_PRECHARGE_SET_SHIFT)
#  define CHARGER_VOLTAGE_STATUS_V_PRECHARGE_SET(n) ((uint32_t)(n) << CHARGER_VOLTAGE_STATUS_V_PRECHARGE_SET_SHIFT)
#define CHARGER_VOLTAGE_STATUS_V_REPLENISH_SET_SHIFT (12) /* Bits 12-17 */
#define CHARGER_VOLTAGE_STATUS_V_REPLENISH_SET_MASK (0x3f << CHARGER_VOLTAGE_STATUS_V_REPLENISH_SET_SHIFT)
#  define CHARGER_VOLTAGE_STATUS_V_REPLENISH_SET(n) ((uint32_t)(n) << CHARGER_VOLTAGE_STATUS_V_REPLENISH_SET_SHIFT)
#define CHARGER_VOLTAGE_STATUS_V_OVP_SET_SHIFT (18)       /* Bits 18-23 */
#define CHARGER_VOLTAGE_STATUS_V_OVP_SET_MASK (0x3f << CHARGER_VOLTAGE_STATUS_V_OVP_SET_SHIFT)
#  define CHARGER_VOLTAGE_STATUS_V_OVP_SET(n) ((uint32_t)(n) << CHARGER_VOLTAGE_STATUS_V_OVP_SET_SHIFT)

/* CURRENT_STATUS register */

#define CHARGER_CURRENT_STATUS_I_CHARGE_SET_SHIFT (0)    /* Bits 0-5 */
#define CHARGER_CURRENT_STATUS_I_CHARGE_SET_MASK (0x3f << CHARGER_CURRENT_STATUS_I_CHARGE_SET_SHIFT)
#  define CHARGER_CURRENT_STATUS_I_CHARGE_SET(n) ((uint32_t)(n) << CHARGER_CURRENT_STATUS_I_CHARGE_SET_SHIFT)
#define CHARGER_CURRENT_STATUS_I_PRECHARGE_SET_SHIFT (6) /* Bits 6-11 */
#define CHARGER_CURRENT_STATUS_I_PRECHARGE_SET_MASK (0x3f << CHARGER_CURRENT_STATUS_I_PRECHARGE_SET_SHIFT)
#  define CHARGER_CURRENT_STATUS_I_PRECHARGE_SET(n) ((uint32_t)(n) << CHARGER_CURRENT_STATUS_I_PRECHARGE_SET_SHIFT)

/* TEMPSET_PARAM register */

#define CHARGER_TEMPSET_PARAM_TBAT_COLD_SHIFT (0) /* Bits 0-5 */
#define CHARGER_TEMPSET_PARAM_TBAT_COLD_MASK (0x3f << CHARGER_TEMPSET_PARAM_TBAT_COLD_SHIFT)
#  define CHARGER_TEMPSET_PARAM_TBAT_COLD(n) ((uint32_t)(n) << CHARGER_TEMPSET_PARAM_TBAT_COLD_SHIFT)
#define CHARGER_TEMPSET_PARAM_TBAT_HOT_SHIFT (6)  /* Bits 6-11 */
#define CHARGER_TEMPSET_PARAM_TBAT_HOT_MASK (0x3f << CHARGER_TEMPSET_PARAM_TBAT_HOT_SHIFT)
#  define CHARGER_TEMPSET_PARAM_TBAT_HOT(n) ((uint32_t)(n) << CHARGER_TEMPSET_PARAM_TBAT_HOT_SHIFT)
#define CHARGER_TEMPSET_PARAM_TDIE_MAX_SHIFT (12) /* Bits 12-14 */
#define CHARGER_TEMPSET_PARAM_TDIE_MAX_MASK (0x7 << CHARGER_TEMPSET_PARAM_TDIE_MAX_SHIFT)
#  define CHARGER_TEMPSET_PARAM_TDIE_MAX(n) ((uint32_t)(n) << CHARGER_TEMPSET_PARAM_TDIE_MAX_SHIFT)

/* TEMPSET2_PARAM register */

#define CHARGER_TEMPSET2_PARAM_TBAT_COOLER_SHIFT (0)  /* Bits 0-5 */
#define CHARGER_TEMPSET2_PARAM_TBAT_COOLER_MASK (0x3f << CHARGER_TEMPSET2_PARAM_TBAT_COOLER_SHIFT)
#  define CHARGER_TEMPSET2_PARAM_TBAT_COOLER(n) ((uint32_t)(n) << CHARGER_TEMPSET2_PARAM_TBAT_COOLER_SHIFT)
#define CHARGER_TEMPSET2_PARAM_TBAT_COOL_SHIFT (6)    /* Bits 6-11 */
#define CHARGER_TEMPSET2_PARAM_TBAT_COOL_MASK (0x3f << CHARGER_TEMPSET2_PARAM_TBAT_COOL_SHIFT)
#  define CHARGER_TEMPSET2_PARAM_TBAT_COOL(n) ((uint32_t)(n) << CHARGER_TEMPSET2_PARAM_TBAT_COOL_SHIFT)
#define CHARGER_TEMPSET2_PARAM_TBAT_WARM_SHIFT (12)   /* Bits 12-17 */
#define CHARGER_TEMPSET2_PARAM_TBAT_WARM_MASK (0x3f << CHARGER_TEMPSET2_PARAM_TBAT_WARM_SHIFT)
#  define CHARGER_TEMPSET2_PARAM_TBAT_WARM(n) ((uint32_t)(n) << CHARGER_TEMPSET2_PARAM_TBAT_WARM_SHIFT)
#define CHARGER_TEMPSET2_PARAM_TBAT_WARMER_SHIFT (18) /* Bits 18-23 */
#define CHARGER_TEMPSET2_PARAM_TBAT_WARMER_MASK (0x3f << CHARGER_TEMPSET2_PARAM_TBAT_WARMER_SHIFT)
#  define CHARGER_TEMPSET2_PARAM_TBAT_WARMER(n) ((uint32_t)(n) << CHARGER_TEMPSET2_PARAM_TBAT_WARMER_SHIFT)

/* PRE_CHARGE_TIMER register */

#define CHARGER_PRE_CHARGE_TIMER_MAX_PRE_CHARGE_TIME_SHIFT (0) /* Bits 0-14 */
#define CHARGER_PRE_CHARGE_TIMER_MAX_PRE_CHARGE_TIME_MASK (0x7fff << CHARGER_PRE_CHARGE_TIMER_MAX_PRE_CHARGE_TIME_SHIFT)
#  define CHARGER_PRE_CHARGE_TIMER_MAX_PRE_CHARGE_TIME(n) ((uint32_t)(n) << CHARGER_PRE_CHARGE_TIMER_MAX_PRE_CHARGE_TIME_SHIFT)
#define CHARGER_PRE_CHARGE_TIMER_PRE_CHARGE_TIMER_SHIFT (16)   /* Bits 16-30 */
#define CHARGER_PRE_CHARGE_TIMER_PRE_CHARGE_TIMER_MASK (0x7fff << CHARGER_PRE_CHARGE_TIMER_PRE_CHARGE_TIMER_SHIFT)
#  define CHARGER_PRE_CHARGE_TIMER_PRE_CHARGE_TIMER(n) ((uint32_t)(n) << CHARGER_PRE_CHARGE_TIMER_PRE_CHARGE_TIMER_SHIFT)

/* CC_CHARGE_TIMER register */

#define CHARGER_CC_CHARGE_TIMER_MAX_CC_CHARGE_TIME_SHIFT (0) /* Bits 0-14 */
#define CHARGER_CC_CHARGE_TIMER_MAX_CC_CHARGE_TIME_MASK (0x7fff << CHARGER_CC_CHARGE_TIMER_MAX_CC_CHARGE_TIME_SHIFT)
#  define CHARGER_CC_CHARGE_TIMER_MAX_CC_CHARGE_TIME(n) ((uint32_t)(n) << CHARGER_CC_CHARGE_TIMER_MAX_CC_CHARGE_TIME_SHIFT)
#define CHARGER_CC_CHARGE_TIMER_CC_CHARGE_TIMER_SHIFT (16)   /* Bits 16-30 */
#define CHARGER_CC_CHARGE_TIMER_CC_CHARGE_TIMER_MASK (0x7fff << CHARGER_CC_CHARGE_TIMER_CC_CHARGE_TIMER_SHIFT)
#  define CHARGER_CC_CHARGE_TIMER_CC_CHARGE_TIMER(n) ((uint32_t)(n) << CHARGER_CC_CHARGE_TIMER_CC_CHARGE_TIMER_SHIFT)

/* CV_CHARGE_TIMER register */

#define CHARGER_CV_CHARGE_TIMER_MAX_CV_CHARGE_TIME_SHIFT (0) /* Bits 0-14 */
#define CHARGER_CV_CHARGE_TIMER_MAX_CV_CHARGE_TIME_MASK (0x7fff << CHARGER_CV_CHARGE_TIMER_MAX_CV_CHARGE_TIME_SHIFT)
#  define CHARGER_CV_CHARGE_TIMER_MAX_CV_CHARGE_TIME(n) ((uint32_t)(n) << CHARGER_CV_CHARGE_TIMER_MAX_CV_CHARGE_TIME_SHIFT)
#define CHARGER_CV_CHARGE_TIMER_CV_CHARGE_TIMER_SHIFT (16)   /* Bits 16-30 */
#define CHARGER_CV_CHARGE_TIMER_CV_CHARGE_TIMER_MASK (0x7fff << CHARGER_CV_CHARGE_TIMER_CV_CHARGE_TIMER_SHIFT)
#  define CHARGER_CV_CHARGE_TIMER_CV_CHARGE_TIMER(n) ((uint32_t)(n) << CHARGER_CV_CHARGE_TIMER_CV_CHARGE_TIMER_SHIFT)

/* TOTAL_CHARGE_TIMER register */

#define CHARGER_TOTAL_CHARGE_TIMER_MAX_TOTAL_CHARGE_TIME_SHIFT (0) /* Bits 0-15 */
#define CHARGER_TOTAL_CHARGE_TIMER_MAX_TOTAL_CHARGE_TIME_MASK (0xffff << CHARGER_TOTAL_CHARGE_TIMER_MAX_TOTAL_CHARGE_TIME_SHIFT)
#  define CHARGER_TOTAL_CHARGE_TIMER_MAX_TOTAL_CHARGE_TIME(n) ((uint32_t)(n) << CHARGER_TOTAL_CHARGE_TIMER_MAX_TOTAL_CHARGE_TIME_SHIFT)
#define CHARGER_TOTAL_CHARGE_TIMER_TOTAL_CHARGE_TIMER_SHIFT (16)   /* Bits 16-31 */
#define CHARGER_TOTAL_CHARGE_TIMER_TOTAL_CHARGE_TIMER_MASK (0xffff << CHARGER_TOTAL_CHARGE_TIMER_TOTAL_CHARGE_TIMER_SHIFT)
#  define CHARGER_TOTAL_CHARGE_TIMER_TOTAL_CHARGE_TIMER(n) ((uint32_t)(n) << CHARGER_TOTAL_CHARGE_TIMER_TOTAL_CHARGE_TIMER_SHIFT)

/* JEITA_V_CHARGE register */

#define CHARGER_JEITA_V_CHARGE_V_CHARGE_TCOOL_SHIFT (0)    /* Bits 0-5 */
#define CHARGER_JEITA_V_CHARGE_V_CHARGE_TCOOL_MASK (0x3f << CHARGER_JEITA_V_CHARGE_V_CHARGE_TCOOL_SHIFT)
#  define CHARGER_JEITA_V_CHARGE_V_CHARGE_TCOOL(n) ((uint32_t)(n) << CHARGER_JEITA_V_CHARGE_V_CHARGE_TCOOL_SHIFT)
#define CHARGER_JEITA_V_CHARGE_V_CHARGE_TWARM_SHIFT (6)    /* Bits 6-11 */
#define CHARGER_JEITA_V_CHARGE_V_CHARGE_TWARM_MASK (0x3f << CHARGER_JEITA_V_CHARGE_V_CHARGE_TWARM_SHIFT)
#  define CHARGER_JEITA_V_CHARGE_V_CHARGE_TWARM(n) ((uint32_t)(n) << CHARGER_JEITA_V_CHARGE_V_CHARGE_TWARM_SHIFT)
#define CHARGER_JEITA_V_CHARGE_V_CHARGE_TCOOLER_SHIFT (12) /* Bits 12-17 */
#define CHARGER_JEITA_V_CHARGE_V_CHARGE_TCOOLER_MASK (0x3f << CHARGER_JEITA_V_CHARGE_V_CHARGE_TCOOLER_SHIFT)
#  define CHARGER_JEITA_V_CHARGE_V_CHARGE_TCOOLER(n) ((uint32_t)(n) << CHARGER_JEITA_V_CHARGE_V_CHARGE_TCOOLER_SHIFT)
#define CHARGER_JEITA_V_CHARGE_V_CHARGE_TWARMER_SHIFT (18) /* Bits 18-23 */
#define CHARGER_JEITA_V_CHARGE_V_CHARGE_TWARMER_MASK (0x3f << CHARGER_JEITA_V_CHARGE_V_CHARGE_TWARMER_SHIFT)
#  define CHARGER_JEITA_V_CHARGE_V_CHARGE_TWARMER(n) ((uint32_t)(n) << CHARGER_JEITA_V_CHARGE_V_CHARGE_TWARMER_SHIFT)

/* JEITA_V_PRECHARGE register */

#define CHARGER_JEITA_V_PRECHARGE_V_PRECHARGE_TCOOL_SHIFT (0)    /* Bits 0-5 */
#define CHARGER_JEITA_V_PRECHARGE_V_PRECHARGE_TCOOL_MASK (0x3f << CHARGER_JEITA_V_PRECHARGE_V_PRECHARGE_TCOOL_SHIFT)
#  define CHARGER_JEITA_V_PRECHARGE_V_PRECHARGE_TCOOL(n) ((uint32_t)(n) << CHARGER_JEITA_V_PRECHARGE_V_PRECHARGE_TCOOL_SHIFT)
#define CHARGER_JEITA_V_PRECHARGE_V_PRECHARGE_TWARM_SHIFT (6)    /* Bits 6-11 */
#define CHARGER_JEITA_V_PRECHARGE_V_PRECHARGE_TWARM_MASK (0x3f << CHARGER_JEITA_V_PRECHARGE_V_PRECHARGE_TWARM_SHIFT)
#  define CHARGER_JEITA_V_PRECHARGE_V_PRECHARGE_TWARM(n) ((uint32_t)(n) << CHARGER_JEITA_V_PRECHARGE_V_PRECHARGE_TWARM_SHIFT)
#define CHARGER_JEITA_V_PRECHARGE_V_PRECHARGE_TCOOLER_SHIFT (12) /* Bits 12-17 */
#define CHARGER_JEITA_V_PRECHARGE_V_PRECHARGE_TCOOLER_MASK (0x3f << CHARGER_JEITA_V_PRECHARGE_V_PRECHARGE_TCOOLER_SHIFT)
#  define CHARGER_JEITA_V_PRECHARGE_V_PRECHARGE_TCOOLER(n) ((uint32_t)(n) << CHARGER_JEITA_V_PRECHARGE_V_PRECHARGE_TCOOLER_SHIFT)
#define CHARGER_JEITA_V_PRECHARGE_V_PRECHARGE_TWARMER_SHIFT (18) /* Bits 18-23 */
#define CHARGER_JEITA_V_PRECHARGE_V_PRECHARGE_TWARMER_MASK (0x3f << CHARGER_JEITA_V_PRECHARGE_V_PRECHARGE_TWARMER_SHIFT)
#  define CHARGER_JEITA_V_PRECHARGE_V_PRECHARGE_TWARMER(n) ((uint32_t)(n) << CHARGER_JEITA_V_PRECHARGE_V_PRECHARGE_TWARMER_SHIFT)

/* JEITA_V_REPLENISH register */

#define CHARGER_JEITA_V_REPLENISH_V_REPLENISH_TCOOL_SHIFT (0)    /* Bits 0-5 */
#define CHARGER_JEITA_V_REPLENISH_V_REPLENISH_TCOOL_MASK (0x3f << CHARGER_JEITA_V_REPLENISH_V_REPLENISH_TCOOL_SHIFT)
#  define CHARGER_JEITA_V_REPLENISH_V_REPLENISH_TCOOL(n) ((uint32_t)(n) << CHARGER_JEITA_V_REPLENISH_V_REPLENISH_TCOOL_SHIFT)
#define CHARGER_JEITA_V_REPLENISH_V_REPLENISH_TWARM_SHIFT (6)    /* Bits 6-11 */
#define CHARGER_JEITA_V_REPLENISH_V_REPLENISH_TWARM_MASK (0x3f << CHARGER_JEITA_V_REPLENISH_V_REPLENISH_TWARM_SHIFT)
#  define CHARGER_JEITA_V_REPLENISH_V_REPLENISH_TWARM(n) ((uint32_t)(n) << CHARGER_JEITA_V_REPLENISH_V_REPLENISH_TWARM_SHIFT)
#define CHARGER_JEITA_V_REPLENISH_V_REPLENISH_TCOOLER_SHIFT (12) /* Bits 12-17 */
#define CHARGER_JEITA_V_REPLENISH_V_REPLENISH_TCOOLER_MASK (0x3f << CHARGER_JEITA_V_REPLENISH_V_REPLENISH_TCOOLER_SHIFT)
#  define CHARGER_JEITA_V_REPLENISH_V_REPLENISH_TCOOLER(n) ((uint32_t)(n) << CHARGER_JEITA_V_REPLENISH_V_REPLENISH_TCOOLER_SHIFT)
#define CHARGER_JEITA_V_REPLENISH_V_REPLENISH_TWARMER_SHIFT (18) /* Bits 18-23 */
#define CHARGER_JEITA_V_REPLENISH_V_REPLENISH_TWARMER_MASK (0x3f << CHARGER_JEITA_V_REPLENISH_V_REPLENISH_TWARMER_SHIFT)
#  define CHARGER_JEITA_V_REPLENISH_V_REPLENISH_TWARMER(n) ((uint32_t)(n) << CHARGER_JEITA_V_REPLENISH_V_REPLENISH_TWARMER_SHIFT)

/* JEITA_V_OVP register */

#define CHARGER_JEITA_V_OVP_V_OVP_TCOOL_SHIFT (0)    /* Bits 0-5 */
#define CHARGER_JEITA_V_OVP_V_OVP_TCOOL_MASK (0x3f << CHARGER_JEITA_V_OVP_V_OVP_TCOOL_SHIFT)
#  define CHARGER_JEITA_V_OVP_V_OVP_TCOOL(n) ((uint32_t)(n) << CHARGER_JEITA_V_OVP_V_OVP_TCOOL_SHIFT)
#define CHARGER_JEITA_V_OVP_V_OVP_TWARM_SHIFT (6)    /* Bits 6-11 */
#define CHARGER_JEITA_V_OVP_V_OVP_TWARM_MASK (0x3f << CHARGER_JEITA_V_OVP_V_OVP_TWARM_SHIFT)
#  define CHARGER_JEITA_V_OVP_V_OVP_TWARM(n) ((uint32_t)(n) << CHARGER_JEITA_V_OVP_V_OVP_TWARM_SHIFT)
#define CHARGER_JEITA_V_OVP_V_OVP_TCOOLER_SHIFT (12) /* Bits 12-17 */
#define CHARGER_JEITA_V_OVP_V_OVP_TCOOLER_MASK (0x3f << CHARGER_JEITA_V_OVP_V_OVP_TCOOLER_SHIFT)
#  define CHARGER_JEITA_V_OVP_V_OVP_TCOOLER(n) ((uint32_t)(n) << CHARGER_JEITA_V_OVP_V_OVP_TCOOLER_SHIFT)
#define CHARGER_JEITA_V_OVP_V_OVP_TWARMER_SHIFT (18) /* Bits 18-23 */
#define CHARGER_JEITA_V_OVP_V_OVP_TWARMER_MASK (0x3f << CHARGER_JEITA_V_OVP_V_OVP_TWARMER_SHIFT)
#  define CHARGER_JEITA_V_OVP_V_OVP_TWARMER(n) ((uint32_t)(n) << CHARGER_JEITA_V_OVP_V_OVP_TWARMER_SHIFT)

/* JEITA_CURRENT register */

#define CHARGER_JEITA_CURRENT_I_CHARGE_TCOOL_SHIFT (0)     /* Bits 0-5 */
#define CHARGER_JEITA_CURRENT_I_CHARGE_TCOOL_MASK (0x3f << CHARGER_JEITA_CURRENT_I_CHARGE_TCOOL_SHIFT)
#  define CHARGER_JEITA_CURRENT_I_CHARGE_TCOOL(n) ((uint32_t)(n) << CHARGER_JEITA_CURRENT_I_CHARGE_TCOOL_SHIFT)
#define CHARGER_JEITA_CURRENT_I_CHARGE_TWARM_SHIFT (6)     /* Bits 6-11 */
#define CHARGER_JEITA_CURRENT_I_CHARGE_TWARM_MASK (0x3f << CHARGER_JEITA_CURRENT_I_CHARGE_TWARM_SHIFT)
#  define CHARGER_JEITA_CURRENT_I_CHARGE_TWARM(n) ((uint32_t)(n) << CHARGER_JEITA_CURRENT_I_CHARGE_TWARM_SHIFT)
#define CHARGER_JEITA_CURRENT_I_PRECHARGE_TCOOL_SHIFT (12) /* Bits 12-17 */
#define CHARGER_JEITA_CURRENT_I_PRECHARGE_TCOOL_MASK (0x3f << CHARGER_JEITA_CURRENT_I_PRECHARGE_TCOOL_SHIFT)
#  define CHARGER_JEITA_CURRENT_I_PRECHARGE_TCOOL(n) ((uint32_t)(n) << CHARGER_JEITA_CURRENT_I_PRECHARGE_TCOOL_SHIFT)
#define CHARGER_JEITA_CURRENT_I_PRECHARGE_TWARM_SHIFT (18) /* Bits 18-23 */
#define CHARGER_JEITA_CURRENT_I_PRECHARGE_TWARM_MASK (0x3f << CHARGER_JEITA_CURRENT_I_PRECHARGE_TWARM_SHIFT)
#  define CHARGER_JEITA_CURRENT_I_PRECHARGE_TWARM(n) ((uint32_t)(n) << CHARGER_JEITA_CURRENT_I_PRECHARGE_TWARM_SHIFT)

/* JEITA_CURRENT2 register */

#define CHARGER_JEITA_CURRENT2_I_CHARGE_TCOOLER_SHIFT (0)     /* Bits 0-5 */
#define CHARGER_JEITA_CURRENT2_I_CHARGE_TCOOLER_MASK (0x3f << CHARGER_JEITA_CURRENT2_I_CHARGE_TCOOLER_SHIFT)
#  define CHARGER_JEITA_CURRENT2_I_CHARGE_TCOOLER(n) ((uint32_t)(n) << CHARGER_JEITA_CURRENT2_I_CHARGE_TCOOLER_SHIFT)
#define CHARGER_JEITA_CURRENT2_I_CHARGE_TWARMER_SHIFT (6)     /* Bits 6-11 */
#define CHARGER_JEITA_CURRENT2_I_CHARGE_TWARMER_MASK (0x3f << CHARGER_JEITA_CURRENT2_I_CHARGE_TWARMER_SHIFT)
#  define CHARGER_JEITA_CURRENT2_I_CHARGE_TWARMER(n) ((uint32_t)(n) << CHARGER_JEITA_CURRENT2_I_CHARGE_TWARMER_SHIFT)
#define CHARGER_JEITA_CURRENT2_I_PRECHARGE_TCOOLER_SHIFT (12) /* Bits 12-17 */
#define CHARGER_JEITA_CURRENT2_I_PRECHARGE_TCOOLER_MASK (0x3f << CHARGER_JEITA_CURRENT2_I_PRECHARGE_TCOOLER_SHIFT)
#  define CHARGER_JEITA_CURRENT2_I_PRECHARGE_TCOOLER(n) ((uint32_t)(n) << CHARGER_JEITA_CURRENT2_I_PRECHARGE_TCOOLER_SHIFT)
#define CHARGER_JEITA_CURRENT2_I_PRECHARGE_TWARMER_SHIFT (18) /* Bits 18-23 */
#define CHARGER_JEITA_CURRENT2_I_PRECHARGE_TWARMER_MASK (0x3f << CHARGER_JEITA_CURRENT2_I_PRECHARGE_TWARMER_SHIFT)
#  define CHARGER_JEITA_CURRENT2_I_PRECHARGE_TWARMER(n) ((uint32_t)(n) << CHARGER_JEITA_CURRENT2_I_PRECHARGE_TWARMER_SHIFT)

/* VBAT_COMP_TIMER register */

#define CHARGER_VBAT_COMP_TIMER_VBAT_COMP_SETTLING_SHIFT (0) /* Bits 0-9 */
#define CHARGER_VBAT_COMP_TIMER_VBAT_COMP_SETTLING_MASK (0x3ff << CHARGER_VBAT_COMP_TIMER_VBAT_COMP_SETTLING_SHIFT)
#  define CHARGER_VBAT_COMP_TIMER_VBAT_COMP_SETTLING(n) ((uint32_t)(n) << CHARGER_VBAT_COMP_TIMER_VBAT_COMP_SETTLING_SHIFT)
#define CHARGER_VBAT_COMP_TIMER_VBAT_COMP_TIMER_SHIFT (16)   /* Bits 16-25 */
#define CHARGER_VBAT_COMP_TIMER_VBAT_COMP_TIMER_MASK (0x3ff << CHARGER_VBAT_COMP_TIMER_VBAT_COMP_TIMER_SHIFT)
#  define CHARGER_VBAT_COMP_TIMER_VBAT_COMP_TIMER(n) ((uint32_t)(n) << CHARGER_VBAT_COMP_TIMER_VBAT_COMP_TIMER_SHIFT)

/* VOVP_COMP_TIMER register */

#define CHARGER_VOVP_COMP_TIMER_VBAT_OVP_COMP_SETTLING_SHIFT (0)    /* Bits 0-9 */
#define CHARGER_VOVP_COMP_TIMER_VBAT_OVP_COMP_SETTLING_MASK (0x3ff << CHARGER_VOVP_COMP_TIMER_VBAT_OVP_COMP_SETTLING_SHIFT)
#  define CHARGER_VOVP_COMP_TIMER_VBAT_OVP_COMP_SETTLING(n) ((uint32_t)(n) << CHARGER_VOVP_COMP_TIMER_VBAT_OVP_COMP_SETTLING_SHIFT)
#define CHARGER_VOVP_COMP_TIMER_OVP_INTERVAL_CHECK_THRES_SHIFT (10) /* Bits 10-15 */
#define CHARGER_VOVP_COMP_TIMER_OVP_INTERVAL_CHECK_THRES_MASK (0x3f << CHARGER_VOVP_COMP_TIMER_OVP_INTERVAL_CHECK_THRES_SHIFT)
#  define CHARGER_VOVP_COMP_TIMER_OVP_INTERVAL_CHECK_THRES(n) ((uint32_t)(n) << CHARGER_VOVP_COMP_TIMER_OVP_INTERVAL_CHECK_THRES_SHIFT)
#define CHARGER_VOVP_COMP_TIMER_VBAT_OVP_COMP_TIMER_SHIFT (16)      /* Bits 16-25 */
#define CHARGER_VOVP_COMP_TIMER_VBAT_OVP_COMP_TIMER_MASK (0x3ff << CHARGER_VOVP_COMP_TIMER_VBAT_OVP_COMP_TIMER_SHIFT)
#  define CHARGER_VOVP_COMP_TIMER_VBAT_OVP_COMP_TIMER(n) ((uint32_t)(n) << CHARGER_VOVP_COMP_TIMER_VBAT_OVP_COMP_TIMER_SHIFT)
#define CHARGER_VOVP_COMP_TIMER_OVP_INTERVAL_CHECK_TIMER_SHIFT (26) /* Bits 26-31 */
#define CHARGER_VOVP_COMP_TIMER_OVP_INTERVAL_CHECK_TIMER_MASK (0x3f << CHARGER_VOVP_COMP_TIMER_OVP_INTERVAL_CHECK_TIMER_SHIFT)
#  define CHARGER_VOVP_COMP_TIMER_OVP_INTERVAL_CHECK_TIMER(n) ((uint32_t)(n) << CHARGER_VOVP_COMP_TIMER_OVP_INTERVAL_CHECK_TIMER_SHIFT)

/* TDIE_COMP_TIMER register */

#define CHARGER_TDIE_COMP_TIMER_TDIE_COMP_SETTLING_SHIFT (0) /* Bits 0-9 */
#define CHARGER_TDIE_COMP_TIMER_TDIE_COMP_SETTLING_MASK (0x3ff << CHARGER_TDIE_COMP_TIMER_TDIE_COMP_SETTLING_SHIFT)
#  define CHARGER_TDIE_COMP_TIMER_TDIE_COMP_SETTLING(n) ((uint32_t)(n) << CHARGER_TDIE_COMP_TIMER_TDIE_COMP_SETTLING_SHIFT)
#define CHARGER_TDIE_COMP_TIMER_TDIE_COMP_TIMER_SHIFT (16)   /* Bits 16-25 */
#define CHARGER_TDIE_COMP_TIMER_TDIE_COMP_TIMER_MASK (0x3ff << CHARGER_TDIE_COMP_TIMER_TDIE_COMP_TIMER_SHIFT)
#  define CHARGER_TDIE_COMP_TIMER_TDIE_COMP_TIMER(n) ((uint32_t)(n) << CHARGER_TDIE_COMP_TIMER_TDIE_COMP_TIMER_SHIFT)

/* TBAT_MON_TIMER register */

#define CHARGER_TBAT_MON_TIMER_TBAT_MON_INTERVAL_SHIFT (0) /* Bits 0-9 */
#define CHARGER_TBAT_MON_TIMER_TBAT_MON_INTERVAL_MASK (0x3ff << CHARGER_TBAT_MON_TIMER_TBAT_MON_INTERVAL_SHIFT)
#  define CHARGER_TBAT_MON_TIMER_TBAT_MON_INTERVAL(n) ((uint32_t)(n) << CHARGER_TBAT_MON_TIMER_TBAT_MON_INTERVAL_SHIFT)
#define CHARGER_TBAT_MON_TIMER_TBAT_MON_TIMER_SHIFT (16)   /* Bits 16-25 */
#define CHARGER_TBAT_MON_TIMER_TBAT_MON_TIMER_MASK (0x3ff << CHARGER_TBAT_MON_TIMER_TBAT_MON_TIMER_SHIFT)
#  define CHARGER_TBAT_MON_TIMER_TBAT_MON_TIMER(n) ((uint32_t)(n) << CHARGER_TBAT_MON_TIMER_TBAT_MON_TIMER_SHIFT)

/* TBAT_COMP_TIMER register */

#define CHARGER_TBAT_COMP_TIMER_TBAT_COMP_SETTLING_SHIFT (0) /* Bits 0-9 */
#define CHARGER_TBAT_COMP_TIMER_TBAT_COMP_SETTLING_MASK (0x3ff << CHARGER_TBAT_COMP_TIMER_TBAT_COMP_SETTLING_SHIFT)
#  define CHARGER_TBAT_COMP_TIMER_TBAT_COMP_SETTLING(n) ((uint32_t)(n) << CHARGER_TBAT_COMP_TIMER_TBAT_COMP_SETTLING_SHIFT)
#define CHARGER_TBAT_COMP_TIMER_TBAT_COMP_TIMER_SHIFT (16)   /* Bits 16-25 */
#define CHARGER_TBAT_COMP_TIMER_TBAT_COMP_TIMER_MASK (0x3ff << CHARGER_TBAT_COMP_TIMER_TBAT_COMP_TIMER_SHIFT)
#  define CHARGER_TBAT_COMP_TIMER_TBAT_COMP_TIMER(n) ((uint32_t)(n) << CHARGER_TBAT_COMP_TIMER_TBAT_COMP_TIMER_SHIFT)

/* THOT_COMP_TIMER register */

#define CHARGER_THOT_COMP_TIMER_THOT_COMP_SETTLING_SHIFT (0) /* Bits 0-9 */
#define CHARGER_THOT_COMP_TIMER_THOT_COMP_SETTLING_MASK (0x3ff << CHARGER_THOT_COMP_TIMER_THOT_COMP_SETTLING_SHIFT)
#  define CHARGER_THOT_COMP_TIMER_THOT_COMP_SETTLING(n) ((uint32_t)(n) << CHARGER_THOT_COMP_TIMER_THOT_COMP_SETTLING_SHIFT)
#define CHARGER_THOT_COMP_TIMER_THOT_COMP_TIMER_SHIFT (16)   /* Bits 16-25 */
#define CHARGER_THOT_COMP_TIMER_THOT_COMP_TIMER_MASK (0x3ff << CHARGER_THOT_COMP_TIMER_THOT_COMP_TIMER_SHIFT)
#  define CHARGER_THOT_COMP_TIMER_THOT_COMP_TIMER(n) ((uint32_t)(n) << CHARGER_THOT_COMP_TIMER_THOT_COMP_TIMER_SHIFT)

/* PWR_UP_TIMER register */

#define CHARGER_PWR_UP_TIMER_PWR_UP_SETTLING_SHIFT (0) /* Bits 0-4 */
#define CHARGER_PWR_UP_TIMER_PWR_UP_SETTLING_MASK (0x1f << CHARGER_PWR_UP_TIMER_PWR_UP_SETTLING_SHIFT)
#  define CHARGER_PWR_UP_TIMER_PWR_UP_SETTLING(n) ((uint32_t)(n) << CHARGER_PWR_UP_TIMER_PWR_UP_SETTLING_SHIFT)
#define CHARGER_PWR_UP_TIMER_PWR_UP_TIMER_SHIFT (16)   /* Bits 16-20 */
#define CHARGER_PWR_UP_TIMER_PWR_UP_TIMER_MASK (0x1f << CHARGER_PWR_UP_TIMER_PWR_UP_TIMER_SHIFT)
#  define CHARGER_PWR_UP_TIMER_PWR_UP_TIMER(n) ((uint32_t)(n) << CHARGER_PWR_UP_TIMER_PWR_UP_TIMER_SHIFT)

/* STATE_IRQ_MASK register */

#define CHARGER_STATE_IRQ_MASK_DISABLED_TO_PRECHARGE_IRQ_EN (1 << 0)  /* Bit 0 */
#define CHARGER_STATE_IRQ_MASK_PRECHARGE_TO_CC_IRQ_EN (1 << 1)        /* Bit 1 */
#define CHARGER_STATE_IRQ_MASK_CC_TO_CV_IRQ_EN (1 << 2)               /* Bit 2 */
#define CHARGER_STATE_IRQ_MASK_CC_TO_EOC_IRQ_EN (1 << 3)              /* Bit 3 */
#define CHARGER_STATE_IRQ_MASK_CV_TO_EOC_IRQ_EN (1 << 4)              /* Bit 4 */
#define CHARGER_STATE_IRQ_MASK_EOC_TO_PRECHARGE_IRQ_EN (1 << 5)       /* Bit 5 */
#define CHARGER_STATE_IRQ_MASK_TDIE_PROT_TO_PRECHARGE_IRQ_EN (1 << 6) /* Bit 6 */
#define CHARGER_STATE_IRQ_MASK_TBAT_PROT_TO_PRECHARGE_IRQ_EN (1 << 7) /* Bit 7 */
#define CHARGER_STATE_IRQ_MASK_TBAT_STATUS_UPDATE_IRQ_EN (1 << 8)     /* Bit 8 */
#define CHARGER_STATE_IRQ_MASK_CV_TO_CC_IRQ_EN (1 << 9)               /* Bit 9 */
#define CHARGER_STATE_IRQ_MASK_CC_TO_PRECHARGE_IRQ_EN (1 << 10)       /* Bit 10 */
#define CHARGER_STATE_IRQ_MASK_CV_TO_PRECHARGE_IRQ_EN (1 << 11)       /* Bit 11 */

/* ERROR_IRQ_MASK register */

#define CHARGER_ERROR_IRQ_MASK_PRECHARGE_TIMEOUT_IRQ_EN (1 << 0)    /* Bit 0 */
#define CHARGER_ERROR_IRQ_MASK_CC_CHARGE_TIMEOUT_IRQ_EN (1 << 1)    /* Bit 1 */
#define CHARGER_ERROR_IRQ_MASK_CV_CHARGE_TIMEOUT_IRQ_EN (1 << 2)    /* Bit 2 */
#define CHARGER_ERROR_IRQ_MASK_TOTAL_CHARGE_TIMEOUT_IRQ_EN (1 << 3) /* Bit 3 */
#define CHARGER_ERROR_IRQ_MASK_VBAT_OVP_ERROR_IRQ_EN (1 << 4)       /* Bit 4 */
#define CHARGER_ERROR_IRQ_MASK_TDIE_ERROR_IRQ_EN (1 << 5)           /* Bit 5 */
#define CHARGER_ERROR_IRQ_MASK_TBAT_ERROR_IRQ_EN (1 << 6)           /* Bit 6 */

/* STATE_IRQ_STATUS register */

#define CHARGER_STATE_IRQ_STATUS_DISABLED_TO_PRECHARGE_IRQ (1 << 0)  /* Bit 0 */
#define CHARGER_STATE_IRQ_STATUS_PRECHARGE_TO_CC_IRQ (1 << 1)        /* Bit 1 */
#define CHARGER_STATE_IRQ_STATUS_CC_TO_CV_IRQ (1 << 2)               /* Bit 2 */
#define CHARGER_STATE_IRQ_STATUS_CC_TO_EOC_IRQ (1 << 3)              /* Bit 3 */
#define CHARGER_STATE_IRQ_STATUS_CV_TO_EOC_IRQ (1 << 4)              /* Bit 4 */
#define CHARGER_STATE_IRQ_STATUS_EOC_TO_PRECHARGE_IRQ (1 << 5)       /* Bit 5 */
#define CHARGER_STATE_IRQ_STATUS_TDIE_PROT_TO_PRECHARGE_IRQ (1 << 6) /* Bit 6 */
#define CHARGER_STATE_IRQ_STATUS_TBAT_PROT_TO_PRECHARGE_IRQ (1 << 7) /* Bit 7 */
#define CHARGER_STATE_IRQ_STATUS_TBAT_STATUS_UPDATE_IRQ (1 << 8)     /* Bit 8 */
#define CHARGER_STATE_IRQ_STATUS_CV_TO_CC_IRQ (1 << 9)               /* Bit 9 */
#define CHARGER_STATE_IRQ_STATUS_CC_TO_PRECHARGE_IRQ (1 << 10)       /* Bit 10 */
#define CHARGER_STATE_IRQ_STATUS_CV_TO_PRECHARGE_IRQ (1 << 11)       /* Bit 11 */

/* ERROR_IRQ_STATUS register */

#define CHARGER_ERROR_IRQ_STATUS_PRECHARGE_TIMEOUT_IRQ (1 << 0)    /* Bit 0 */
#define CHARGER_ERROR_IRQ_STATUS_CC_CHARGE_TIMEOUT_IRQ (1 << 1)    /* Bit 1 */
#define CHARGER_ERROR_IRQ_STATUS_CV_CHARGE_TIMEOUT_IRQ (1 << 2)    /* Bit 2 */
#define CHARGER_ERROR_IRQ_STATUS_TOTAL_CHARGE_TIMEOUT_IRQ (1 << 3) /* Bit 3 */
#define CHARGER_ERROR_IRQ_STATUS_VBAT_OVP_ERROR_IRQ (1 << 4)       /* Bit 4 */
#define CHARGER_ERROR_IRQ_STATUS_TDIE_ERROR_IRQ (1 << 5)           /* Bit 5 */
#define CHARGER_ERROR_IRQ_STATUS_TBAT_ERROR_IRQ (1 << 6)           /* Bit 6 */

/* STATE_IRQ_CLR register */

#define CHARGER_STATE_IRQ_CLR_DISABLED_TO_PRECHARGE_IRQ_CLR (1 << 0)  /* Bit 0 */
#define CHARGER_STATE_IRQ_CLR_PRECHARGE_TO_CC_IRQ_CLR (1 << 1)        /* Bit 1 */
#define CHARGER_STATE_IRQ_CLR_CC_TO_CV_IRQ_CLR (1 << 2)               /* Bit 2 */
#define CHARGER_STATE_IRQ_CLR_CC_TO_EOC_IRQ_CLR (1 << 3)              /* Bit 3 */
#define CHARGER_STATE_IRQ_CLR_CV_TO_EOC_IRQ_CLR (1 << 4)              /* Bit 4 */
#define CHARGER_STATE_IRQ_CLR_EOC_TO_PRECHARGE_IRQ_CLR (1 << 5)       /* Bit 5 */
#define CHARGER_STATE_IRQ_CLR_TDIE_PROT_TO_PRECHARGE_IRQ_CLR (1 << 6) /* Bit 6 */
#define CHARGER_STATE_IRQ_CLR_TBAT_PROT_TO_PRECHARGE_IRQ_CLR (1 << 7) /* Bit 7 */
#define CHARGER_STATE_IRQ_CLR_TBAT_STATUS_UPDATE_IRQ_CLR (1 << 8)     /* Bit 8 */
#define CHARGER_STATE_IRQ_CLR_CV_TO_CC_IRQ_CLR (1 << 9)               /* Bit 9 */
#define CHARGER_STATE_IRQ_CLR_CC_TO_PRECHARGE_IRQ_CLR (1 << 10)       /* Bit 10 */
#define CHARGER_STATE_IRQ_CLR_CV_TO_PRECHARGE_IRQ_CLR (1 << 11)       /* Bit 11 */

/* ERROR_IRQ_CLR register */

#define CHARGER_ERROR_IRQ_CLR_PRECHARGE_TIMEOUT_IRQ_CLR (1 << 0)    /* Bit 0 */
#define CHARGER_ERROR_IRQ_CLR_CC_CHARGE_TIMEOUT_IRQ_CLR (1 << 1)    /* Bit 1 */
#define CHARGER_ERROR_IRQ_CLR_CV_CHARGE_TIMEOUT_IRQ_CLR (1 << 2)    /* Bit 2 */
#define CHARGER_ERROR_IRQ_CLR_TOTAL_CHARGE_TIMEOUT_IRQ_CLR (1 << 3) /* Bit 3 */
#define CHARGER_ERROR_IRQ_CLR_VBAT_OVP_ERROR_IRQ_CLR (1 << 4)       /* Bit 4 */
#define CHARGER_ERROR_IRQ_CLR_TDIE_ERROR_IRQ_CLR (1 << 5)           /* Bit 5 */
#define CHARGER_ERROR_IRQ_CLR_TBAT_ERROR_IRQ_CLR (1 << 6)           /* Bit 6 */

/* LOCK register */

#define CHARGER_LOCK_CTRL_LOCK (1 << 0)                 /* Bit 0 */
#define CHARGER_LOCK_TEST_CTRL_LOCK (1 << 1)            /* Bit 1 */
#define CHARGER_LOCK_VOLTAGE_PARAM_LOCK (1 << 2)        /* Bit 2 */
#define CHARGER_LOCK_CURRENT_PARAM_LOCK (1 << 3)        /* Bit 3 */
#define CHARGER_LOCK_TEMPSET_PARAM_LOCK (1 << 4)        /* Bit 4 */
#define CHARGER_LOCK_TEMPSET2_PARAM_LOCK (1 << 5)       /* Bit 5 */
#define CHARGER_LOCK_PRECHARGE_TIMEOUT_LOCK (1 << 6)    /* Bit 6 */
#define CHARGER_LOCK_CC_CHARGE_TIMEOUT_LOCK (1 << 7)    /* Bit 7 */
#define CHARGER_LOCK_CV_CHARGE_TIMEOUT_LOCK (1 << 8)    /* Bit 8 */
#define CHARGER_LOCK_TOTAL_CHARGE_TIMEOUT_LOCK (1 << 9) /* Bit 9 */
#define CHARGER_LOCK_JEITA_V_CHARGE_LOCK (1 << 10)      /* Bit 10 */
#define CHARGER_LOCK_JEITA_V_PRECHARGE_LOCK (1 << 11)   /* Bit 11 */
#define CHARGER_LOCK_JEITA_V_OVP_LOCK (1 << 12)         /* Bit 12 */
#define CHARGER_LOCK_JEITA_I_CHARGE_LOCK (1 << 13)      /* Bit 13 */
#define CHARGER_LOCK_JEITA_I_CHARGE2_LOCK (1 << 14)     /* Bit 14 */
#define CHARGER_LOCK_SWLOCK_EN (1 << 15)                /* Bit 15 */

/* SWLOCK register */

#define CHARGER_SWLOCK_SWLOCK_STATUS (1 << 0)     /* Bit 0 */
#define CHARGER_SWLOCK_SWLOCK_FSM_STATE_SHIFT (1) /* Bits 1-2 */
#define CHARGER_SWLOCK_SWLOCK_FSM_STATE_MASK (0x3 << CHARGER_SWLOCK_SWLOCK_FSM_STATE_SHIFT)
#  define CHARGER_SWLOCK_SWLOCK_FSM_STATE(n) ((uint32_t)(n) << CHARGER_SWLOCK_SWLOCK_FSM_STATE_SHIFT)

#endif /* __ARCH_ARM_SRC_DA1470X_HARDWARE_DA1470X_CHARGER_H */
