/****************************************************************************
 * arch/arm/src/da1470x/hardware/da1470x_gpu_core.h
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.  The
 * ASF licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 ****************************************************************************/

/* Generated from the Renesas CMSIS device header DA1470x-00.h (SDK
 * 10.2.6.49).  Do not edit by hand; regenerate with tools/genhdr.py.
 */

#ifndef __ARCH_ARM_SRC_DA1470X_HARDWARE_DA1470X_GPU_CORE_H
#define __ARCH_ARM_SRC_DA1470X_HARDWARE_DA1470X_GPU_CORE_H

/****************************************************************************
 * Included Files
 ****************************************************************************/

#include <nuttx/config.h>
#include "da1470x_memorymap.h"

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

/* Register Offsets *********************************************************/

#define DA1470X_GPU_CORE_D2_CONTROL_OFFSET 0x0000      /* #0: Geometry control register. This regi */
#define DA1470X_GPU_CORE_D2_CONTROL2_OFFSET 0x0004     /* #1: Surface control register. This regis */
#define DA1470X_GPU_CORE_D2_CONTROL3_OFFSET 0x0008     /* #2: Burst length limit control register. */
#define DA1470X_GPU_CORE_D2_L1START_OFFSET 0x0010      /* #4: Limiter1 start value. All limiter re */
#define DA1470X_GPU_CORE_D2_L2START_OFFSET 0x0014      /* #5: Limiter2 start value. See D2_L1START */
#define DA1470X_GPU_CORE_D2_L3START_OFFSET 0x0018      /* #6: Limiter3 start value. See D2_L1START */
#define DA1470X_GPU_CORE_D2_L4START_OFFSET 0x001c      /* #7: Limiter4 start value. See D2_L1START */
#define DA1470X_GPU_CORE_D2_L5START_OFFSET 0x0020      /* #8: Limiter5 start value. See D2_L1START */
#define DA1470X_GPU_CORE_D2_L6START_OFFSET 0x0024      /* #9: Limiter6 start value. See D2_L1START */
#define DA1470X_GPU_CORE_D2_L1XADD_OFFSET 0x0028       /* #10: Limiter1 X-Axis increment. The xadd */
#define DA1470X_GPU_CORE_D2_L2XADD_OFFSET 0x002c       /* #11: Limiter2 X-Axis increment. See D2_L */
#define DA1470X_GPU_CORE_D2_L3XADD_OFFSET 0x0030       /* #12: Limiter3 X-Axis increment */
#define DA1470X_GPU_CORE_D2_L4XADD_OFFSET 0x0034       /* #13: Limiter4 X-Axis increment. See D2_L */
#define DA1470X_GPU_CORE_D2_L5XADD_OFFSET 0x0038       /* #14: Limiter5 X-Axis increment. See D2_L */
#define DA1470X_GPU_CORE_D2_L6XADD_OFFSET 0x003c       /* #15: Limiter6 X-Axis increment. See D2_L */
#define DA1470X_GPU_CORE_D2_L1YADD_OFFSET 0x0040       /* #16: Limiter1 Y-Axis increment. The yadd */
#define DA1470X_GPU_CORE_D2_L2YADD_OFFSET 0x0044       /* #17: Limiter2 Y-Axis increment. See D2_L */
#define DA1470X_GPU_CORE_D2_L3YADD_OFFSET 0x0048       /* #18: Limiter3 Y-Axis increment. See D2_L */
#define DA1470X_GPU_CORE_D2_L4YADD_OFFSET 0x004c       /* #19: Limiter4 Y-Axis increment. See D2_L */
#define DA1470X_GPU_CORE_D2_L5YADD_OFFSET 0x0050       /* #20: Limiter5 Y-Axis increment. See D2_L */
#define DA1470X_GPU_CORE_D2_L6YADD_OFFSET 0x0054       /* #21: Limiter6 Y-Axis increment. See D2_L */
#define DA1470X_GPU_CORE_D2_L1BAND_OFFSET 0x0058       /* #22: Limiter1 band width parameter. Post */
#define DA1470X_GPU_CORE_D2_L2BAND_OFFSET 0x005c       /* #23: Limiter2 band width parameter. See */
#define DA1470X_GPU_CORE_D2_COLOR1_OFFSET 0x0064       /* #25: Base color register. All color regi */
#define DA1470X_GPU_CORE_D2_COLOR2_OFFSET 0x0068       /* #26: Secondary color register. Secondary */
#define DA1470X_GPU_CORE_D2_PATTERN_OFFSET 0x0074      /* #29: Pattern register. Each bit in the p */
#define DA1470X_GPU_CORE_D2_SIZE_OFFSET 0x0078         /* #30: Bounding box dimension */
#define DA1470X_GPU_CORE_D2_PITCH_OFFSET 0x007c        /* #31: Framebuffer pitch and spanstore del */
#define DA1470X_GPU_CORE_D2_ORIGIN_OFFSET 0x0080       /* #32: Address of the first pixel in frame */
#define DA1470X_GPU_CORE_D2_LUSTART_OFFSET 0x0090      /* #36: U Limiter start value. The start va */
#define DA1470X_GPU_CORE_D2_LUXADD_OFFSET 0x0094       /* #37: U Limiter X-Axis increment. The add */
#define DA1470X_GPU_CORE_D2_LUYADD_OFFSET 0x0098       /* #38: U Limiter Y-Axis increment. The add */
#define DA1470X_GPU_CORE_D2_LVSTARTI_OFFSET 0x009c     /* #39: V Limiter start value integer part */
#define DA1470X_GPU_CORE_D2_LVSTARTF_OFFSET 0x00a0     /* #40: V Limiter start value fractional pa */
#define DA1470X_GPU_CORE_D2_LVXADDI_OFFSET 0x00a4      /* #41: V Limiter X-Axis increment integer */
#define DA1470X_GPU_CORE_D2_LVYADDI_OFFSET 0x00a8      /* #42: V Limiter Y-Axis increment integer */
#define DA1470X_GPU_CORE_D2_LVYXADDF_OFFSET 0x00ac     /* #43: V Limiter X and Y increment fractio */
#define DA1470X_GPU_CORE_D2_TEXPITCH_OFFSET 0x00b4     /* #45: Texels per texture line&Pitch is eq */
#define DA1470X_GPU_CORE_D2_TEXMASK_OFFSET 0x00b8      /* #46: Texture size or texture address mas */
#define DA1470X_GPU_CORE_D2_TEXORIGIN_OFFSET 0x00bc    /* #47: Texture base address. All texture r */
#define DA1470X_GPU_CORE_D2_IRQCTL_OFFSET 0x00c0       /* #48: Interrupt control register. The GPU */
#define DA1470X_GPU_CORE_D2_CACHECTL_OFFSET 0x00c4     /* #49: Cache control register. Internal ca */
#define DA1470X_GPU_CORE_D2_DLISTSTART_OFFSET 0x00c8   /* #50: Displaylist start address. Setting */
#define DA1470X_GPU_CORE_D2_PERFCOUNT1_OFFSET 0x00cc   /* #51: Performance counter. Writing to the */
#define DA1470X_GPU_CORE_D2_PERFCOUNT2_OFFSET 0x00d0   /* #52: Performance counter. Writing to the */
#define DA1470X_GPU_CORE_D2_PERFTRIGGER_OFFSET 0x00d4  /* #53: Performance counters control regist */
#define DA1470X_GPU_CORE_D2_TEXCLUT_OFFSET 0x00d8      /* #54: Color Lookup Table for the indexed */
#define DA1470X_GPU_CORE_D2_TEXCLUT_ADDR_OFFSET 0x00dc /* #55: Color Lookup Table write address fo */
#define DA1470X_GPU_CORE_D2_TEXCLUT_DATA_OFFSET 0x00e0 /* #56: Color Lookup Table write data for t */
#define DA1470X_GPU_CORE_D2_TEXCLUT_OFS_OFFSET 0x00e4  /* #57: Offset to the texture index for the */
#define DA1470X_GPU_CORE_D2_COLKEY_OFFSET 0x00e8       /* #58: Color key value. The R, G, and B co */
#define DA1470X_GPU_CORE_D2_HWREVISION_OFFSET 0x00f0   /* #1: Hardware version and feature set ID. */
#define DA1470X_GPU_CORE_D2_STATUS_OFFSET 0x00f4       /* #0: Status control register. The current */

/* Register Addresses *******************************************************/

#define DA1470X_GPU_CORE_D2_CONTROL (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_CONTROL_OFFSET)
#define DA1470X_GPU_CORE_D2_CONTROL2 (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_CONTROL2_OFFSET)
#define DA1470X_GPU_CORE_D2_CONTROL3 (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_CONTROL3_OFFSET)
#define DA1470X_GPU_CORE_D2_L1START (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_L1START_OFFSET)
#define DA1470X_GPU_CORE_D2_L2START (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_L2START_OFFSET)
#define DA1470X_GPU_CORE_D2_L3START (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_L3START_OFFSET)
#define DA1470X_GPU_CORE_D2_L4START (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_L4START_OFFSET)
#define DA1470X_GPU_CORE_D2_L5START (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_L5START_OFFSET)
#define DA1470X_GPU_CORE_D2_L6START (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_L6START_OFFSET)
#define DA1470X_GPU_CORE_D2_L1XADD (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_L1XADD_OFFSET)
#define DA1470X_GPU_CORE_D2_L2XADD (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_L2XADD_OFFSET)
#define DA1470X_GPU_CORE_D2_L3XADD (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_L3XADD_OFFSET)
#define DA1470X_GPU_CORE_D2_L4XADD (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_L4XADD_OFFSET)
#define DA1470X_GPU_CORE_D2_L5XADD (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_L5XADD_OFFSET)
#define DA1470X_GPU_CORE_D2_L6XADD (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_L6XADD_OFFSET)
#define DA1470X_GPU_CORE_D2_L1YADD (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_L1YADD_OFFSET)
#define DA1470X_GPU_CORE_D2_L2YADD (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_L2YADD_OFFSET)
#define DA1470X_GPU_CORE_D2_L3YADD (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_L3YADD_OFFSET)
#define DA1470X_GPU_CORE_D2_L4YADD (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_L4YADD_OFFSET)
#define DA1470X_GPU_CORE_D2_L5YADD (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_L5YADD_OFFSET)
#define DA1470X_GPU_CORE_D2_L6YADD (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_L6YADD_OFFSET)
#define DA1470X_GPU_CORE_D2_L1BAND (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_L1BAND_OFFSET)
#define DA1470X_GPU_CORE_D2_L2BAND (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_L2BAND_OFFSET)
#define DA1470X_GPU_CORE_D2_COLOR1 (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_COLOR1_OFFSET)
#define DA1470X_GPU_CORE_D2_COLOR2 (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_COLOR2_OFFSET)
#define DA1470X_GPU_CORE_D2_PATTERN (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_PATTERN_OFFSET)
#define DA1470X_GPU_CORE_D2_SIZE (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_SIZE_OFFSET)
#define DA1470X_GPU_CORE_D2_PITCH (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_PITCH_OFFSET)
#define DA1470X_GPU_CORE_D2_ORIGIN (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_ORIGIN_OFFSET)
#define DA1470X_GPU_CORE_D2_LUSTART (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_LUSTART_OFFSET)
#define DA1470X_GPU_CORE_D2_LUXADD (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_LUXADD_OFFSET)
#define DA1470X_GPU_CORE_D2_LUYADD (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_LUYADD_OFFSET)
#define DA1470X_GPU_CORE_D2_LVSTARTI (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_LVSTARTI_OFFSET)
#define DA1470X_GPU_CORE_D2_LVSTARTF (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_LVSTARTF_OFFSET)
#define DA1470X_GPU_CORE_D2_LVXADDI (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_LVXADDI_OFFSET)
#define DA1470X_GPU_CORE_D2_LVYADDI (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_LVYADDI_OFFSET)
#define DA1470X_GPU_CORE_D2_LVYXADDF (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_LVYXADDF_OFFSET)
#define DA1470X_GPU_CORE_D2_TEXPITCH (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_TEXPITCH_OFFSET)
#define DA1470X_GPU_CORE_D2_TEXMASK (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_TEXMASK_OFFSET)
#define DA1470X_GPU_CORE_D2_TEXORIGIN (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_TEXORIGIN_OFFSET)
#define DA1470X_GPU_CORE_D2_IRQCTL (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_IRQCTL_OFFSET)
#define DA1470X_GPU_CORE_D2_CACHECTL (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_CACHECTL_OFFSET)
#define DA1470X_GPU_CORE_D2_DLISTSTART (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_DLISTSTART_OFFSET)
#define DA1470X_GPU_CORE_D2_PERFCOUNT1 (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_PERFCOUNT1_OFFSET)
#define DA1470X_GPU_CORE_D2_PERFCOUNT2 (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_PERFCOUNT2_OFFSET)
#define DA1470X_GPU_CORE_D2_PERFTRIGGER (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_PERFTRIGGER_OFFSET)
#define DA1470X_GPU_CORE_D2_TEXCLUT (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_TEXCLUT_OFFSET)
#define DA1470X_GPU_CORE_D2_TEXCLUT_ADDR (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_TEXCLUT_ADDR_OFFSET)
#define DA1470X_GPU_CORE_D2_TEXCLUT_DATA (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_TEXCLUT_DATA_OFFSET)
#define DA1470X_GPU_CORE_D2_TEXCLUT_OFS (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_TEXCLUT_OFS_OFFSET)
#define DA1470X_GPU_CORE_D2_COLKEY (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_COLKEY_OFFSET)
#define DA1470X_GPU_CORE_D2_HWREVISION (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_HWREVISION_OFFSET)
#define DA1470X_GPU_CORE_D2_STATUS (DA1470X_GPU_CORE_BASE + DA1470X_GPU_CORE_D2_STATUS_OFFSET)

/* Register Bit-field Definitions *******************************************/

/* D2_CONTROL register */

#define GPU_CORE_D2_CONTROL_D2C_LIM1ENABLE (1 << 0)        /* Bit 0 */
#define GPU_CORE_D2_CONTROL_D2C_LIM2ENABLE (1 << 1)        /* Bit 1 */
#define GPU_CORE_D2_CONTROL_D2C_LIM3ENABLE (1 << 2)        /* Bit 2 */
#define GPU_CORE_D2_CONTROL_D2C_LIM4ENABLE (1 << 3)        /* Bit 3 */
#define GPU_CORE_D2_CONTROL_D2C_LIM5ENABLE (1 << 4)        /* Bit 4 */
#define GPU_CORE_D2_CONTROL_D2C_LIM6ENABLE (1 << 5)        /* Bit 5 */
#define GPU_CORE_D2_CONTROL_D2C_QUAD1ENABLE (1 << 6)       /* Bit 6 */
#define GPU_CORE_D2_CONTROL_D2C_QUAD2ENABLE (1 << 7)       /* Bit 7 */
#define GPU_CORE_D2_CONTROL_D2C_QUAD3ENABLE (1 << 8)       /* Bit 8 */
#define GPU_CORE_D2_CONTROL_D2C_LIM1THRESHOLD (1 << 9)     /* Bit 9 */
#define GPU_CORE_D2_CONTROL_D2C_LIM2THRESHOLD (1 << 10)    /* Bit 10 */
#define GPU_CORE_D2_CONTROL_D2C_LIM3THRESHOLD (1 << 11)    /* Bit 11 */
#define GPU_CORE_D2_CONTROL_D2C_LIM4THRESHOLD (1 << 12)    /* Bit 12 */
#define GPU_CORE_D2_CONTROL_D2C_LIM5THRESHOLD (1 << 13)    /* Bit 13 */
#define GPU_CORE_D2_CONTROL_D2C_LIM6THRESHOLD (1 << 14)    /* Bit 14 */
#define GPU_CORE_D2_CONTROL_D2C_BAND1ENABLE (1 << 15)      /* Bit 15 */
#define GPU_CORE_D2_CONTROL_D2C_BAND2ENABLE (1 << 16)      /* Bit 16 */
#define GPU_CORE_D2_CONTROL_D2C_UNION12 (1 << 17)          /* Bit 17 */
#define GPU_CORE_D2_CONTROL_D2C_UNION34 (1 << 18)          /* Bit 18 */
#define GPU_CORE_D2_CONTROL_D2C_UNION56 (1 << 19)          /* Bit 19 */
#define GPU_CORE_D2_CONTROL_D2C_UNIONAB (1 << 20)          /* Bit 20 */
#define GPU_CORE_D2_CONTROL_D2C_UNIONCD (1 << 21)          /* Bit 21 */
#define GPU_CORE_D2_CONTROL_D2C_SPANABORT (1 << 22)        /* Bit 22 */
#define GPU_CORE_D2_CONTROL_D2C_SPANSTORE (1 << 23)        /* Bit 23 */
#define GPU_CORE_D2_CONTROL_D2C_LIMITERPRECISION (1 << 24) /* Bit 24 */

/* D2_CONTROL2 register */

#define GPU_CORE_D2_CONTROL2_D2C_PATTERNENABLE (1 << 0)   /* Bit 0 */
#define GPU_CORE_D2_CONTROL2_D2C_TEXTUREENABLE (1 << 1)   /* Bit 1 */
#define GPU_CORE_D2_CONTROL2_D2C_PATTERNSOURCEL5 (1 << 2) /* Bit 2 */
#define GPU_CORE_D2_CONTROL2_USE_ACB (1 << 3)             /* Bit 3 */
#define GPU_CORE_D2_CONTROL2_D2C_READFORMAT3 (1 << 4)     /* Bit 4 */
#define GPU_CORE_D2_CONTROL2_D2C_READFORMAT4 (1 << 5)     /* Bit 5 */
#define GPU_CORE_D2_CONTROL2_D2C_BSFA (1 << 6)            /* Bit 6 */
#define GPU_CORE_D2_CONTROL2_D2C_BDFA (1 << 7)            /* Bit 7 */
#define GPU_CORE_D2_CONTROL2_D2C_WRITEFORMAT3 (1 << 8)    /* Bit 8 */
#define GPU_CORE_D2_CONTROL2_D2C_BSF (1 << 9)             /* Bit 9 */
#define GPU_CORE_D2_CONTROL2_D2C_BDF (1 << 10)            /* Bit 10 */
#define GPU_CORE_D2_CONTROL2_D2C_BSI (1 << 11)            /* Bit 11 */
#define GPU_CORE_D2_CONTROL2_D2C_BDI (1 << 12)            /* Bit 12 */
#define GPU_CORE_D2_CONTROL2_D2C_BC2 (1 << 13)            /* Bit 13 */
#define GPU_CORE_D2_CONTROL2_D2C_TEXTURECLAMPX (1 << 14)  /* Bit 14 */
#define GPU_CORE_D2_CONTROL2_D2C_TEXTURECLAMPY (1 << 15)  /* Bit 15 */
#define GPU_CORE_D2_CONTROL2_D2C_TEXTUREFILTERX (1 << 16) /* Bit 16 */
#define GPU_CORE_D2_CONTROL2_D2C_TEXTUREFILTERY (1 << 17) /* Bit 17 */
#define GPU_CORE_D2_CONTROL2_D2C_READFORMAT1 (1 << 18)    /* Bit 18 */
#define GPU_CORE_D2_CONTROL2_D2C_READFORMAT2 (1 << 19)    /* Bit 19 */
#define GPU_CORE_D2_CONTROL2_D2C_WRITEFORMAT1 (1 << 20)   /* Bit 20 */
#define GPU_CORE_D2_CONTROL2_D2C_WRITEFORMAT2 (1 << 21)   /* Bit 21 */
#define GPU_CORE_D2_CONTROL2_D2C_WRITEALPHA1 (1 << 22)    /* Bit 22 */
#define GPU_CORE_D2_CONTROL2_D2C_WRITEALPHA2 (1 << 23)    /* Bit 23 */
#define GPU_CORE_D2_CONTROL2_D2C_RLE_ENABLE (1 << 24)     /* Bit 24 */
#define GPU_CORE_D2_CONTROL2_D2C_CLUT_ENABLE (1 << 25)    /* Bit 25 */
#define GPU_CORE_D2_CONTROL2_D2C_COLKEY_ENABLE (1 << 26)  /* Bit 26 */
#define GPU_CORE_D2_CONTROL2_D2C_CLUTFORMAT1 (1 << 27)    /* Bit 27 */
#define GPU_CORE_D2_CONTROL2_D2C_BSIA (1 << 28)           /* Bit 28 */
#define GPU_CORE_D2_CONTROL2_D2C_BDIA (1 << 29)           /* Bit 29 */
#define GPU_CORE_D2_CONTROL2_D2C_RLEFORMAT1 (1 << 30)     /* Bit 30 */
#define GPU_CORE_D2_CONTROL2_D2C_RLEFORMAT2 (1 << 31)     /* Bit 31 */

/* D2_CONTROL3 register */

#define GPU_CORE_D2_CONTROL3_BURSTLENGTH_MFBR_SHIFT (0) /* Bits 0-2 */
#define GPU_CORE_D2_CONTROL3_BURSTLENGTH_MFBR_MASK (0x7 << GPU_CORE_D2_CONTROL3_BURSTLENGTH_MFBR_SHIFT)
#  define GPU_CORE_D2_CONTROL3_BURSTLENGTH_MFBR(n) ((uint32_t)(n) << GPU_CORE_D2_CONTROL3_BURSTLENGTH_MFBR_SHIFT)
#define GPU_CORE_D2_CONTROL3_BURSTLENGTH_MFBW_SHIFT (8) /* Bits 8-10 */
#define GPU_CORE_D2_CONTROL3_BURSTLENGTH_MFBW_MASK (0x7 << GPU_CORE_D2_CONTROL3_BURSTLENGTH_MFBW_SHIFT)
#  define GPU_CORE_D2_CONTROL3_BURSTLENGTH_MFBW(n) ((uint32_t)(n) << GPU_CORE_D2_CONTROL3_BURSTLENGTH_MFBW_SHIFT)
#define GPU_CORE_D2_CONTROL3_BURSTLENGTH_MTX_SHIFT (16) /* Bits 16-18 */
#define GPU_CORE_D2_CONTROL3_BURSTLENGTH_MTX_MASK (0x7 << GPU_CORE_D2_CONTROL3_BURSTLENGTH_MTX_SHIFT)
#  define GPU_CORE_D2_CONTROL3_BURSTLENGTH_MTX(n) ((uint32_t)(n) << GPU_CORE_D2_CONTROL3_BURSTLENGTH_MTX_SHIFT)
#define GPU_CORE_D2_CONTROL3_BURSTLENGTH_MDL_SHIFT (24) /* Bits 24-26 */
#define GPU_CORE_D2_CONTROL3_BURSTLENGTH_MDL_MASK (0x7 << GPU_CORE_D2_CONTROL3_BURSTLENGTH_MDL_SHIFT)
#  define GPU_CORE_D2_CONTROL3_BURSTLENGTH_MDL(n) ((uint32_t)(n) << GPU_CORE_D2_CONTROL3_BURSTLENGTH_MDL_SHIFT)

/* D2_L1START register */

#define GPU_CORE_D2_L1START_L1START_SHIFT (0) /* Bits 0-31 */
#define GPU_CORE_D2_L1START_L1START_MASK (0xffffffff << GPU_CORE_D2_L1START_L1START_SHIFT)
#  define GPU_CORE_D2_L1START_L1START(n) ((uint32_t)(n) << GPU_CORE_D2_L1START_L1START_SHIFT)

/* D2_L2START register */

#define GPU_CORE_D2_L2START_L2START_SHIFT (0) /* Bits 0-31 */
#define GPU_CORE_D2_L2START_L2START_MASK (0xffffffff << GPU_CORE_D2_L2START_L2START_SHIFT)
#  define GPU_CORE_D2_L2START_L2START(n) ((uint32_t)(n) << GPU_CORE_D2_L2START_L2START_SHIFT)

/* D2_L3START register */

#define GPU_CORE_D2_L3START_L3START_SHIFT (0) /* Bits 0-31 */
#define GPU_CORE_D2_L3START_L3START_MASK (0xffffffff << GPU_CORE_D2_L3START_L3START_SHIFT)
#  define GPU_CORE_D2_L3START_L3START(n) ((uint32_t)(n) << GPU_CORE_D2_L3START_L3START_SHIFT)

/* D2_L4START register */

#define GPU_CORE_D2_L4START_L4START_SHIFT (0) /* Bits 0-31 */
#define GPU_CORE_D2_L4START_L4START_MASK (0xffffffff << GPU_CORE_D2_L4START_L4START_SHIFT)
#  define GPU_CORE_D2_L4START_L4START(n) ((uint32_t)(n) << GPU_CORE_D2_L4START_L4START_SHIFT)

/* D2_L5START register */

#define GPU_CORE_D2_L5START_L5START_SHIFT (0) /* Bits 0-31 */
#define GPU_CORE_D2_L5START_L5START_MASK (0xffffffff << GPU_CORE_D2_L5START_L5START_SHIFT)
#  define GPU_CORE_D2_L5START_L5START(n) ((uint32_t)(n) << GPU_CORE_D2_L5START_L5START_SHIFT)

/* D2_L6START register */

#define GPU_CORE_D2_L6START_L6START_SHIFT (0) /* Bits 0-31 */
#define GPU_CORE_D2_L6START_L6START_MASK (0xffffffff << GPU_CORE_D2_L6START_L6START_SHIFT)
#  define GPU_CORE_D2_L6START_L6START(n) ((uint32_t)(n) << GPU_CORE_D2_L6START_L6START_SHIFT)

/* D2_L1XADD register */

#define GPU_CORE_D2_L1XADD_L1XADD_SHIFT (0) /* Bits 0-31 */
#define GPU_CORE_D2_L1XADD_L1XADD_MASK (0xffffffff << GPU_CORE_D2_L1XADD_L1XADD_SHIFT)
#  define GPU_CORE_D2_L1XADD_L1XADD(n) ((uint32_t)(n) << GPU_CORE_D2_L1XADD_L1XADD_SHIFT)

/* D2_L2XADD register */

#define GPU_CORE_D2_L2XADD_L2XADD_SHIFT (0) /* Bits 0-31 */
#define GPU_CORE_D2_L2XADD_L2XADD_MASK (0xffffffff << GPU_CORE_D2_L2XADD_L2XADD_SHIFT)
#  define GPU_CORE_D2_L2XADD_L2XADD(n) ((uint32_t)(n) << GPU_CORE_D2_L2XADD_L2XADD_SHIFT)

/* D2_L3XADD register */

#define GPU_CORE_D2_L3XADD_L3XADD_SHIFT (0) /* Bits 0-31 */
#define GPU_CORE_D2_L3XADD_L3XADD_MASK (0xffffffff << GPU_CORE_D2_L3XADD_L3XADD_SHIFT)
#  define GPU_CORE_D2_L3XADD_L3XADD(n) ((uint32_t)(n) << GPU_CORE_D2_L3XADD_L3XADD_SHIFT)

/* D2_L4XADD register */

#define GPU_CORE_D2_L4XADD_L4XADD_SHIFT (0) /* Bits 0-31 */
#define GPU_CORE_D2_L4XADD_L4XADD_MASK (0xffffffff << GPU_CORE_D2_L4XADD_L4XADD_SHIFT)
#  define GPU_CORE_D2_L4XADD_L4XADD(n) ((uint32_t)(n) << GPU_CORE_D2_L4XADD_L4XADD_SHIFT)

/* D2_L5XADD register */

#define GPU_CORE_D2_L5XADD_L5XADD_SHIFT (0) /* Bits 0-31 */
#define GPU_CORE_D2_L5XADD_L5XADD_MASK (0xffffffff << GPU_CORE_D2_L5XADD_L5XADD_SHIFT)
#  define GPU_CORE_D2_L5XADD_L5XADD(n) ((uint32_t)(n) << GPU_CORE_D2_L5XADD_L5XADD_SHIFT)

/* D2_L6XADD register */

#define GPU_CORE_D2_L6XADD_L6XADD_SHIFT (0) /* Bits 0-31 */
#define GPU_CORE_D2_L6XADD_L6XADD_MASK (0xffffffff << GPU_CORE_D2_L6XADD_L6XADD_SHIFT)
#  define GPU_CORE_D2_L6XADD_L6XADD(n) ((uint32_t)(n) << GPU_CORE_D2_L6XADD_L6XADD_SHIFT)

/* D2_L1YADD register */

#define GPU_CORE_D2_L1YADD_L1YADD_SHIFT (0) /* Bits 0-31 */
#define GPU_CORE_D2_L1YADD_L1YADD_MASK (0xffffffff << GPU_CORE_D2_L1YADD_L1YADD_SHIFT)
#  define GPU_CORE_D2_L1YADD_L1YADD(n) ((uint32_t)(n) << GPU_CORE_D2_L1YADD_L1YADD_SHIFT)

/* D2_L2YADD register */

#define GPU_CORE_D2_L2YADD_L2YADD_SHIFT (0) /* Bits 0-31 */
#define GPU_CORE_D2_L2YADD_L2YADD_MASK (0xffffffff << GPU_CORE_D2_L2YADD_L2YADD_SHIFT)
#  define GPU_CORE_D2_L2YADD_L2YADD(n) ((uint32_t)(n) << GPU_CORE_D2_L2YADD_L2YADD_SHIFT)

/* D2_L3YADD register */

#define GPU_CORE_D2_L3YADD_L3YADD_SHIFT (0) /* Bits 0-31 */
#define GPU_CORE_D2_L3YADD_L3YADD_MASK (0xffffffff << GPU_CORE_D2_L3YADD_L3YADD_SHIFT)
#  define GPU_CORE_D2_L3YADD_L3YADD(n) ((uint32_t)(n) << GPU_CORE_D2_L3YADD_L3YADD_SHIFT)

/* D2_L4YADD register */

#define GPU_CORE_D2_L4YADD_L4YADD_SHIFT (0) /* Bits 0-31 */
#define GPU_CORE_D2_L4YADD_L4YADD_MASK (0xffffffff << GPU_CORE_D2_L4YADD_L4YADD_SHIFT)
#  define GPU_CORE_D2_L4YADD_L4YADD(n) ((uint32_t)(n) << GPU_CORE_D2_L4YADD_L4YADD_SHIFT)

/* D2_L5YADD register */

#define GPU_CORE_D2_L5YADD_L5YADD_SHIFT (0) /* Bits 0-31 */
#define GPU_CORE_D2_L5YADD_L5YADD_MASK (0xffffffff << GPU_CORE_D2_L5YADD_L5YADD_SHIFT)
#  define GPU_CORE_D2_L5YADD_L5YADD(n) ((uint32_t)(n) << GPU_CORE_D2_L5YADD_L5YADD_SHIFT)

/* D2_L6YADD register */

#define GPU_CORE_D2_L6YADD_L6YADD_SHIFT (0) /* Bits 0-31 */
#define GPU_CORE_D2_L6YADD_L6YADD_MASK (0xffffffff << GPU_CORE_D2_L6YADD_L6YADD_SHIFT)
#  define GPU_CORE_D2_L6YADD_L6YADD(n) ((uint32_t)(n) << GPU_CORE_D2_L6YADD_L6YADD_SHIFT)

/* D2_L1BAND register */

#define GPU_CORE_D2_L1BAND_L1BAND_SHIFT (0) /* Bits 0-31 */
#define GPU_CORE_D2_L1BAND_L1BAND_MASK (0xffffffff << GPU_CORE_D2_L1BAND_L1BAND_SHIFT)
#  define GPU_CORE_D2_L1BAND_L1BAND(n) ((uint32_t)(n) << GPU_CORE_D2_L1BAND_L1BAND_SHIFT)

/* D2_L2BAND register */

#define GPU_CORE_D2_L2BAND_L2BAND_SHIFT (0) /* Bits 0-31 */
#define GPU_CORE_D2_L2BAND_L2BAND_MASK (0xffffffff << GPU_CORE_D2_L2BAND_L2BAND_SHIFT)
#  define GPU_CORE_D2_L2BAND_L2BAND(n) ((uint32_t)(n) << GPU_CORE_D2_L2BAND_L2BAND_SHIFT)

/* D2_COLOR1 register */

#define GPU_CORE_D2_COLOR1_COLOR1_SHIFT (0) /* Bits 0-31 */
#define GPU_CORE_D2_COLOR1_COLOR1_MASK (0xffffffff << GPU_CORE_D2_COLOR1_COLOR1_SHIFT)
#  define GPU_CORE_D2_COLOR1_COLOR1(n) ((uint32_t)(n) << GPU_CORE_D2_COLOR1_COLOR1_SHIFT)

/* D2_COLOR2 register */

#define GPU_CORE_D2_COLOR2_COLOR2_SHIFT (0) /* Bits 0-31 */
#define GPU_CORE_D2_COLOR2_COLOR2_MASK (0xffffffff << GPU_CORE_D2_COLOR2_COLOR2_SHIFT)
#  define GPU_CORE_D2_COLOR2_COLOR2(n) ((uint32_t)(n) << GPU_CORE_D2_COLOR2_COLOR2_SHIFT)

/* D2_PATTERN register */

#define GPU_CORE_D2_PATTERN_PATTERN_SHIFT (0) /* Bits 0-31 */
#define GPU_CORE_D2_PATTERN_PATTERN_MASK (0xffffffff << GPU_CORE_D2_PATTERN_PATTERN_SHIFT)
#  define GPU_CORE_D2_PATTERN_PATTERN(n) ((uint32_t)(n) << GPU_CORE_D2_PATTERN_PATTERN_SHIFT)

/* D2_SIZE register */

#define GPU_CORE_D2_SIZE_SIZEX_SHIFT (0)  /* Bits 0-15 */
#define GPU_CORE_D2_SIZE_SIZEX_MASK (0xffff << GPU_CORE_D2_SIZE_SIZEX_SHIFT)
#  define GPU_CORE_D2_SIZE_SIZEX(n) ((uint32_t)(n) << GPU_CORE_D2_SIZE_SIZEX_SHIFT)
#define GPU_CORE_D2_SIZE_SIZEY_SHIFT (16) /* Bits 16-31 */
#define GPU_CORE_D2_SIZE_SIZEY_MASK (0xffff << GPU_CORE_D2_SIZE_SIZEY_SHIFT)
#  define GPU_CORE_D2_SIZE_SIZEY(n) ((uint32_t)(n) << GPU_CORE_D2_SIZE_SIZEY_SHIFT)

/* D2_PITCH register */

#define GPU_CORE_D2_PITCH_PITCH_SHIFT (0) /* Bits 0-15 */
#define GPU_CORE_D2_PITCH_PITCH_MASK (0xffff << GPU_CORE_D2_PITCH_PITCH_SHIFT)
#  define GPU_CORE_D2_PITCH_PITCH(n) ((uint32_t)(n) << GPU_CORE_D2_PITCH_PITCH_SHIFT)
#define GPU_CORE_D2_PITCH_SSD_SHIFT (16)  /* Bits 16-31 */
#define GPU_CORE_D2_PITCH_SSD_MASK (0xffff << GPU_CORE_D2_PITCH_SSD_SHIFT)
#  define GPU_CORE_D2_PITCH_SSD(n) ((uint32_t)(n) << GPU_CORE_D2_PITCH_SSD_SHIFT)

/* D2_ORIGIN register */

#define GPU_CORE_D2_ORIGIN_ORIGIN_SHIFT (0) /* Bits 0-31 */
#define GPU_CORE_D2_ORIGIN_ORIGIN_MASK (0xffffffff << GPU_CORE_D2_ORIGIN_ORIGIN_SHIFT)
#  define GPU_CORE_D2_ORIGIN_ORIGIN(n) ((uint32_t)(n) << GPU_CORE_D2_ORIGIN_ORIGIN_SHIFT)

/* D2_LUSTART register */

#define GPU_CORE_D2_LUSTART_LUSTART_SHIFT (0) /* Bits 0-31 */
#define GPU_CORE_D2_LUSTART_LUSTART_MASK (0xffffffff << GPU_CORE_D2_LUSTART_LUSTART_SHIFT)
#  define GPU_CORE_D2_LUSTART_LUSTART(n) ((uint32_t)(n) << GPU_CORE_D2_LUSTART_LUSTART_SHIFT)

/* D2_LUXADD register */

#define GPU_CORE_D2_LUXADD_LUXADD_SHIFT (0) /* Bits 0-31 */
#define GPU_CORE_D2_LUXADD_LUXADD_MASK (0xffffffff << GPU_CORE_D2_LUXADD_LUXADD_SHIFT)
#  define GPU_CORE_D2_LUXADD_LUXADD(n) ((uint32_t)(n) << GPU_CORE_D2_LUXADD_LUXADD_SHIFT)

/* D2_LUYADD register */

#define GPU_CORE_D2_LUYADD_LUYADD_SHIFT (0) /* Bits 0-31 */
#define GPU_CORE_D2_LUYADD_LUYADD_MASK (0xffffffff << GPU_CORE_D2_LUYADD_LUYADD_SHIFT)
#  define GPU_CORE_D2_LUYADD_LUYADD(n) ((uint32_t)(n) << GPU_CORE_D2_LUYADD_LUYADD_SHIFT)

/* D2_LVSTARTI register */

#define GPU_CORE_D2_LVSTARTI_LVSTARTI_SHIFT (0) /* Bits 0-31 */
#define GPU_CORE_D2_LVSTARTI_LVSTARTI_MASK (0xffffffff << GPU_CORE_D2_LVSTARTI_LVSTARTI_SHIFT)
#  define GPU_CORE_D2_LVSTARTI_LVSTARTI(n) ((uint32_t)(n) << GPU_CORE_D2_LVSTARTI_LVSTARTI_SHIFT)

/* D2_LVSTARTF register */

#define GPU_CORE_D2_LVSTARTF_LVSTARTF_SHIFT (0) /* Bits 0-15 */
#define GPU_CORE_D2_LVSTARTF_LVSTARTF_MASK (0xffff << GPU_CORE_D2_LVSTARTF_LVSTARTF_SHIFT)
#  define GPU_CORE_D2_LVSTARTF_LVSTARTF(n) ((uint32_t)(n) << GPU_CORE_D2_LVSTARTF_LVSTARTF_SHIFT)

/* D2_LVXADDI register */

#define GPU_CORE_D2_LVXADDI_LVXADDI_SHIFT (0) /* Bits 0-31 */
#define GPU_CORE_D2_LVXADDI_LVXADDI_MASK (0xffffffff << GPU_CORE_D2_LVXADDI_LVXADDI_SHIFT)
#  define GPU_CORE_D2_LVXADDI_LVXADDI(n) ((uint32_t)(n) << GPU_CORE_D2_LVXADDI_LVXADDI_SHIFT)

/* D2_LVYADDI register */

#define GPU_CORE_D2_LVYADDI_LVYADDI_SHIFT (0) /* Bits 0-31 */
#define GPU_CORE_D2_LVYADDI_LVYADDI_MASK (0xffffffff << GPU_CORE_D2_LVYADDI_LVYADDI_SHIFT)
#  define GPU_CORE_D2_LVYADDI_LVYADDI(n) ((uint32_t)(n) << GPU_CORE_D2_LVYADDI_LVYADDI_SHIFT)

/* D2_LVYXADDF register */

#define GPU_CORE_D2_LVYXADDF_D2_LVXADDI_FRAC_SHIFT (0)  /* Bits 0-15 */
#define GPU_CORE_D2_LVYXADDF_D2_LVXADDI_FRAC_MASK (0xffff << GPU_CORE_D2_LVYXADDF_D2_LVXADDI_FRAC_SHIFT)
#  define GPU_CORE_D2_LVYXADDF_D2_LVXADDI_FRAC(n) ((uint32_t)(n) << GPU_CORE_D2_LVYXADDF_D2_LVXADDI_FRAC_SHIFT)
#define GPU_CORE_D2_LVYXADDF_D2_LVYADDI_FRAC_SHIFT (16) /* Bits 16-31 */
#define GPU_CORE_D2_LVYXADDF_D2_LVYADDI_FRAC_MASK (0xffff << GPU_CORE_D2_LVYXADDF_D2_LVYADDI_FRAC_SHIFT)
#  define GPU_CORE_D2_LVYXADDF_D2_LVYADDI_FRAC(n) ((uint32_t)(n) << GPU_CORE_D2_LVYXADDF_D2_LVYADDI_FRAC_SHIFT)

/* D2_TEXPITCH register */

#define GPU_CORE_D2_TEXPITCH_TEXPITCH_SHIFT (0) /* Bits 0-31 */
#define GPU_CORE_D2_TEXPITCH_TEXPITCH_MASK (0xffffffff << GPU_CORE_D2_TEXPITCH_TEXPITCH_SHIFT)
#  define GPU_CORE_D2_TEXPITCH_TEXPITCH(n) ((uint32_t)(n) << GPU_CORE_D2_TEXPITCH_TEXPITCH_SHIFT)

/* D2_TEXMASK register */

#define GPU_CORE_D2_TEXMASK_TEXUMASK_SHIFT (0)  /* Bits 0-10 */
#define GPU_CORE_D2_TEXMASK_TEXUMASK_MASK (0x7ff << GPU_CORE_D2_TEXMASK_TEXUMASK_SHIFT)
#  define GPU_CORE_D2_TEXMASK_TEXUMASK(n) ((uint32_t)(n) << GPU_CORE_D2_TEXMASK_TEXUMASK_SHIFT)
#define GPU_CORE_D2_TEXMASK_TEXVMASK_SHIFT (11) /* Bits 11-31 */
#define GPU_CORE_D2_TEXMASK_TEXVMASK_MASK (0x1fffff << GPU_CORE_D2_TEXMASK_TEXVMASK_SHIFT)
#  define GPU_CORE_D2_TEXMASK_TEXVMASK(n) ((uint32_t)(n) << GPU_CORE_D2_TEXMASK_TEXVMASK_SHIFT)

/* D2_TEXORIGIN register */

#define GPU_CORE_D2_TEXORIGIN_TEXORIGIN_SHIFT (0) /* Bits 0-31 */
#define GPU_CORE_D2_TEXORIGIN_TEXORIGIN_MASK (0xffffffff << GPU_CORE_D2_TEXORIGIN_TEXORIGIN_SHIFT)
#  define GPU_CORE_D2_TEXORIGIN_TEXORIGIN(n) ((uint32_t)(n) << GPU_CORE_D2_TEXORIGIN_TEXORIGIN_SHIFT)

/* D2_IRQCTL register */

#define GPU_CORE_D2_IRQCTL_D2IRQCTL_ENABLE_FINISH_ENUM (1 << 0)  /* Bit 0 */
#define GPU_CORE_D2_IRQCTL_D2IRQCTL_ENABLE_FINISH_DLIST (1 << 1) /* Bit 1 */
#define GPU_CORE_D2_IRQCTL_D2IRQCTL_CLR_FINISH_ENUM (1 << 2)     /* Bit 2 */
#define GPU_CORE_D2_IRQCTL_D2IRQCTL_CLR_FINISH_DLIST (1 << 3)    /* Bit 3 */
#define GPU_CORE_D2_IRQCTL_D2IRQCTL_ENABLE_BUS_ERROR (1 << 4)    /* Bit 4 */
#define GPU_CORE_D2_IRQCTL_D2IRQCTL_CLR_BUS_ERROR (1 << 5)       /* Bit 5 */

/* D2_CACHECTL register */

#define GPU_CORE_D2_CACHECTL_D2C_CACHECTL_ENABLE_FB (1 << 0) /* Bit 0 */
#define GPU_CORE_D2_CACHECTL_D2C_CACHECTL_FLUSH_FB (1 << 1)  /* Bit 1 */
#define GPU_CORE_D2_CACHECTL_D2C_CACHECTL_ENABLE_TX (1 << 2) /* Bit 2 */
#define GPU_CORE_D2_CACHECTL_D2C_CACHECTL_FLUSH_TX (1 << 3)  /* Bit 3 */

/* D2_DLISTSTART register */

#define GPU_CORE_D2_DLISTSTART_DLISTSTART_SHIFT (0) /* Bits 0-31 */
#define GPU_CORE_D2_DLISTSTART_DLISTSTART_MASK (0xffffffff << GPU_CORE_D2_DLISTSTART_DLISTSTART_SHIFT)
#  define GPU_CORE_D2_DLISTSTART_DLISTSTART(n) ((uint32_t)(n) << GPU_CORE_D2_DLISTSTART_DLISTSTART_SHIFT)

/* D2_PERFCOUNT1 register */

#define GPU_CORE_D2_PERFCOUNT1_PERFCOUNT1_SHIFT (0) /* Bits 0-31 */
#define GPU_CORE_D2_PERFCOUNT1_PERFCOUNT1_MASK (0xffffffff << GPU_CORE_D2_PERFCOUNT1_PERFCOUNT1_SHIFT)
#  define GPU_CORE_D2_PERFCOUNT1_PERFCOUNT1(n) ((uint32_t)(n) << GPU_CORE_D2_PERFCOUNT1_PERFCOUNT1_SHIFT)

/* D2_PERFCOUNT2 register */

#define GPU_CORE_D2_PERFCOUNT2_PERFCOUNT2_SHIFT (0) /* Bits 0-31 */
#define GPU_CORE_D2_PERFCOUNT2_PERFCOUNT2_MASK (0xffffffff << GPU_CORE_D2_PERFCOUNT2_PERFCOUNT2_SHIFT)
#  define GPU_CORE_D2_PERFCOUNT2_PERFCOUNT2(n) ((uint32_t)(n) << GPU_CORE_D2_PERFCOUNT2_PERFCOUNT2_SHIFT)

/* D2_PERFTRIGGER register */

#define GPU_CORE_D2_PERFTRIGGER_PERFTRIGGER1_SHIFT (0)  /* Bits 0-15 */
#define GPU_CORE_D2_PERFTRIGGER_PERFTRIGGER1_MASK (0xffff << GPU_CORE_D2_PERFTRIGGER_PERFTRIGGER1_SHIFT)
#  define GPU_CORE_D2_PERFTRIGGER_PERFTRIGGER1(n) ((uint32_t)(n) << GPU_CORE_D2_PERFTRIGGER_PERFTRIGGER1_SHIFT)
#define GPU_CORE_D2_PERFTRIGGER_PERFTRIGGER2_SHIFT (16) /* Bits 16-31 */
#define GPU_CORE_D2_PERFTRIGGER_PERFTRIGGER2_MASK (0xffff << GPU_CORE_D2_PERFTRIGGER_PERFTRIGGER2_SHIFT)
#  define GPU_CORE_D2_PERFTRIGGER_PERFTRIGGER2(n) ((uint32_t)(n) << GPU_CORE_D2_PERFTRIGGER_PERFTRIGGER2_SHIFT)

/* D2_TEXCLUT register */

#define GPU_CORE_D2_TEXCLUT_ADDR_TEXCLUT_ADDR_SHIFT (0)     /* Bits 0-7 */
#define GPU_CORE_D2_TEXCLUT_ADDR_TEXCLUT_ADDR_MASK (0xff << GPU_CORE_D2_TEXCLUT_ADDR_TEXCLUT_ADDR_SHIFT)
#  define GPU_CORE_D2_TEXCLUT_ADDR_TEXCLUT_ADDR(n) ((uint32_t)(n) << GPU_CORE_D2_TEXCLUT_ADDR_TEXCLUT_ADDR_SHIFT)
#define GPU_CORE_D2_TEXCLUT_OFFSET_TEXCLUT_OFFSET_SHIFT (0) /* Bits 0-7 */
#define GPU_CORE_D2_TEXCLUT_OFFSET_TEXCLUT_OFFSET_MASK (0xff << GPU_CORE_D2_TEXCLUT_OFFSET_TEXCLUT_OFFSET_SHIFT)
#  define GPU_CORE_D2_TEXCLUT_OFFSET_TEXCLUT_OFFSET(n) ((uint32_t)(n) << GPU_CORE_D2_TEXCLUT_OFFSET_TEXCLUT_OFFSET_SHIFT)
#define GPU_CORE_D2_TEXCLUT_TEXCLUT_RGB_SHIFT (0)           /* Bits 0-23 */
#define GPU_CORE_D2_TEXCLUT_TEXCLUT_RGB_MASK (0xffffff << GPU_CORE_D2_TEXCLUT_TEXCLUT_RGB_SHIFT)
#  define GPU_CORE_D2_TEXCLUT_TEXCLUT_RGB(n) ((uint32_t)(n) << GPU_CORE_D2_TEXCLUT_TEXCLUT_RGB_SHIFT)
#define GPU_CORE_D2_TEXCLUT_DATA_TEXCLUT_ARGB_SHIFT (0)     /* Bits 0-31 */
#define GPU_CORE_D2_TEXCLUT_DATA_TEXCLUT_ARGB_MASK (0xffffffff << GPU_CORE_D2_TEXCLUT_DATA_TEXCLUT_ARGB_SHIFT)
#  define GPU_CORE_D2_TEXCLUT_DATA_TEXCLUT_ARGB(n) ((uint32_t)(n) << GPU_CORE_D2_TEXCLUT_DATA_TEXCLUT_ARGB_SHIFT)
#define GPU_CORE_D2_TEXCLUT_TEXCLUT_INDEX_SHIFT (24)        /* Bits 24-31 */
#define GPU_CORE_D2_TEXCLUT_TEXCLUT_INDEX_MASK (0xff << GPU_CORE_D2_TEXCLUT_TEXCLUT_INDEX_SHIFT)
#  define GPU_CORE_D2_TEXCLUT_TEXCLUT_INDEX(n) ((uint32_t)(n) << GPU_CORE_D2_TEXCLUT_TEXCLUT_INDEX_SHIFT)

/* D2_TEXCLUT_ADDR register */

#define GPU_CORE_D2_TEXCLUT_ADDR_TEXCLUT_ADDR_SHIFT (0) /* Bits 0-7 */
#define GPU_CORE_D2_TEXCLUT_ADDR_TEXCLUT_ADDR_MASK (0xff << GPU_CORE_D2_TEXCLUT_ADDR_TEXCLUT_ADDR_SHIFT)
#  define GPU_CORE_D2_TEXCLUT_ADDR_TEXCLUT_ADDR(n) ((uint32_t)(n) << GPU_CORE_D2_TEXCLUT_ADDR_TEXCLUT_ADDR_SHIFT)

/* D2_TEXCLUT_DATA register */

#define GPU_CORE_D2_TEXCLUT_DATA_TEXCLUT_ARGB_SHIFT (0) /* Bits 0-31 */
#define GPU_CORE_D2_TEXCLUT_DATA_TEXCLUT_ARGB_MASK (0xffffffff << GPU_CORE_D2_TEXCLUT_DATA_TEXCLUT_ARGB_SHIFT)
#  define GPU_CORE_D2_TEXCLUT_DATA_TEXCLUT_ARGB(n) ((uint32_t)(n) << GPU_CORE_D2_TEXCLUT_DATA_TEXCLUT_ARGB_SHIFT)

/* D2_TEXCLUT_OFS register */

#define GPU_CORE_D2_TEXCLUT_OFS_TEXCLUT_OFFSET_SHIFT (0) /* Bits 0-7 */
#define GPU_CORE_D2_TEXCLUT_OFS_TEXCLUT_OFFSET_MASK (0xff << GPU_CORE_D2_TEXCLUT_OFS_TEXCLUT_OFFSET_SHIFT)
#  define GPU_CORE_D2_TEXCLUT_OFS_TEXCLUT_OFFSET(n) ((uint32_t)(n) << GPU_CORE_D2_TEXCLUT_OFS_TEXCLUT_OFFSET_SHIFT)

/* D2_COLKEY register */

#define GPU_CORE_D2_COLKEY_COLKEY_RGB_SHIFT (0) /* Bits 0-23 */
#define GPU_CORE_D2_COLKEY_COLKEY_RGB_MASK (0xffffff << GPU_CORE_D2_COLKEY_COLKEY_RGB_SHIFT)
#  define GPU_CORE_D2_COLKEY_COLKEY_RGB(n) ((uint32_t)(n) << GPU_CORE_D2_COLKEY_COLKEY_RGB_SHIFT)

/* D2_HWREVISION register */

#define GPU_CORE_D2_HWREVISION_HWREVISION_SHIFT (0)              /* Bits 0-7 */
#define GPU_CORE_D2_HWREVISION_HWREVISION_MASK (0xff << GPU_CORE_D2_HWREVISION_HWREVISION_SHIFT)
#  define GPU_CORE_D2_HWREVISION_HWREVISION(n) ((uint32_t)(n) << GPU_CORE_D2_HWREVISION_HWREVISION_SHIFT)
#define GPU_CORE_D2_HWREVISION_HWBRANCH_SHIFT (8)                /* Bits 8-11 */
#define GPU_CORE_D2_HWREVISION_HWBRANCH_MASK (0xf << GPU_CORE_D2_HWREVISION_HWBRANCH_SHIFT)
#  define GPU_CORE_D2_HWREVISION_HWBRANCH(n) ((uint32_t)(n) << GPU_CORE_D2_HWREVISION_HWBRANCH_SHIFT)
#define GPU_CORE_D2_HWREVISION_HWTYPE_SHIFT (12)                 /* Bits 12-15 */
#define GPU_CORE_D2_HWREVISION_HWTYPE_MASK (0xf << GPU_CORE_D2_HWREVISION_HWTYPE_SHIFT)
#  define GPU_CORE_D2_HWREVISION_HWTYPE(n) ((uint32_t)(n) << GPU_CORE_D2_HWREVISION_HWTYPE_SHIFT)
#define GPU_CORE_D2_HWREVISION_FB_SWGPU (1 << 16)                /* Bit 16 */
#define GPU_CORE_D2_HWREVISION_FB_DLR (1 << 17)                  /* Bit 17 */
#define GPU_CORE_D2_HWREVISION_FB_FBCACHE (1 << 18)              /* Bit 18 */
#define GPU_CORE_D2_HWREVISION_FB_TXCACHE (1 << 19)              /* Bit 19 */
#define GPU_CORE_D2_HWREVISION_FB_PERFCOUNT (1 << 20)            /* Bit 20 */
#define GPU_CORE_D2_HWREVISION_FB_TEXCLUT (1 << 21)              /* Bit 21 */
#define GPU_CORE_D2_HWREVISION_FB_FBPREFETCH (1 << 22)           /* Bit 22 */
#define GPU_CORE_D2_HWREVISION_FB_RLEUNIT (1 << 23)              /* Bit 23 */
#define GPU_CORE_D2_HWREVISION_FB_TEXCLUT256 (1 << 24)           /* Bit 24 */
#define GPU_CORE_D2_HWREVISION_FB_COLORKEY (1 << 25)             /* Bit 25 */
#define GPU_CORE_D2_HWREVISION_FB_HILIMITERPRECISION (1 << 26)   /* Bit 26 */
#define GPU_CORE_D2_HWREVISION_FB_ALPHACHANNELBLENDING (1 << 27) /* Bit 27 */
#define GPU_CORE_D2_HWREVISION_FB_BURSTSPLITTING (1 << 28)       /* Bit 28 */

/* D2_STATUS register */

#define GPU_CORE_D2_STATUS_D2C_BUSY_ENUM (1 << 0)          /* Bit 0 */
#define GPU_CORE_D2_STATUS_D2C_BUSY_WRITE (1 << 1)         /* Bit 1 */
#define GPU_CORE_D2_STATUS_D2C_CACHE_DIRTY (1 << 2)        /* Bit 2 */
#define GPU_CORE_D2_STATUS_D2C_DLISTACTIVE (1 << 3)        /* Bit 3 */
#define GPU_CORE_D2_STATUS_D2C_IRQ_ENUM (1 << 4)           /* Bit 4 */
#define GPU_CORE_D2_STATUS_D2C_IRQ_DLIST (1 << 5)          /* Bit 5 */
#define GPU_CORE_D2_STATUS_D2C_IRQ_BUS_ERROR (1 << 6)      /* Bit 6 */
#define GPU_CORE_D2_STATUS_D2C_IRQ_BUS_ERROR_SRC_SHIFT (8) /* Bits 8-10 */
#define GPU_CORE_D2_STATUS_D2C_IRQ_BUS_ERROR_SRC_MASK (0x7 << GPU_CORE_D2_STATUS_D2C_IRQ_BUS_ERROR_SRC_SHIFT)
#  define GPU_CORE_D2_STATUS_D2C_IRQ_BUS_ERROR_SRC(n) ((uint32_t)(n) << GPU_CORE_D2_STATUS_D2C_IRQ_BUS_ERROR_SRC_SHIFT)

#endif /* __ARCH_ARM_SRC_DA1470X_HARDWARE_DA1470X_GPU_CORE_H */
